import type { Place } from '../runtime/types';

export const HK_1988_MAP_ID = 'hk_1988_main';

type CanonicalPlaceInput = Omit<
  Place,
  'aliases' | 'roadAnchors' | 'relatedActorIds' | 'relatedCaseIds' | 'relatedPressureIds' | 'canonical' | 'source' | 'confidence'
> &
  Partial<
    Pick<
      Place,
      'aliases' | 'roadAnchors' | 'relatedActorIds' | 'relatedCaseIds' | 'relatedPressureIds' | 'canonical' | 'source' | 'confidence'
    >
  >;

function canonicalPlace(place: CanonicalPlaceInput): Place {
  return {
    ...place,
    aliases: place.aliases ?? [],
    roadAnchors: place.roadAnchors ?? [],
    relatedActorIds: place.relatedActorIds ?? [],
    relatedCaseIds: place.relatedCaseIds ?? [],
    relatedPressureIds: place.relatedPressureIds ?? [],
    canonical: true,
    source: 'worldpack_canonical',
    confidence: place.confidence ?? 'high',
    visualAnchor: place.visualAnchor
      ? {
          ...place.visualAnchor,
          mapId: HK_1988_MAP_ID,
          source: place.visualAnchor.source ?? 'worldpack_canonical'
        }
      : undefined
  };
}

export const hk1988WorldpackPlaces: Place[] = [
  canonicalPlace({
    placeId: 'place_mong_kok_police_station',
    name: '旺角警署',
    nameZh: '旺角警署',
    nameEn: 'Mong Kok Police Station',
    aliases: ['旺角差馆', 'Mong Kok Station'],
    regionId: 'region_kowloon',
    districtId: 'district_mong_kok',
    type: 'police_station',
    category: 'police',
    summary: '九龙繁忙商业和夜生活街区中的警署，常接触街坊、商户、夜场、游客和社团边缘人物。',
    publicKnowledge: '街坊知道这里是旺角一带报案、巡逻和日常警务的主要入口。',
    currentState: '警署内电话、报案记录和交接脚步声不断。',
    streetAddressText: '旺角一带',
    roadAnchors: ['弥敦道', '亚皆老街', '西洋菜南街'],
    playerKnownSummary: '玩家开局常驻或熟悉的基层警务地点。',
    owningOrganizationId: 'org_hk_police',
    relatedActorIds: ['player'],
    relatedCaseIds: [],
    relatedPressureIds: [],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.55, y: 0.43, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_yau_ma_tei_police_station',
    name: '油麻地警署',
    nameZh: '油麻地警署',
    nameEn: 'Yau Ma Tei Police Station',
    aliases: ['油麻地差馆', 'Yau Ma Tei Station'],
    regionId: 'region_kowloon',
    districtId: 'district_yau_ma_tei',
    type: 'police_station',
    category: 'police',
    summary: '油麻地一带的警务节点，连接庙街、渡船街、旧楼和夜间街市压力。',
    publicKnowledge: '区内居民和商贩知道这里处理报案、巡逻和夜间治安问题。',
    currentState: '报案室常有街坊纠纷、醉酒滋事和夜市相关记录。',
    streetAddressText: '油麻地一带',
    roadAnchors: ['弥敦道', '庙街', '上海街'],
    relatedActorIds: [],
    relatedCaseIds: [],
    relatedPressureIds: [],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.54, y: 0.46, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_tsim_sha_tsui_police_station',
    name: '尖沙咀警署',
    nameZh: '尖沙咀警署',
    nameEn: 'Tsim Sha Tsui Police Station',
    aliases: ['尖沙咀差馆', 'TST Police Station'],
    regionId: 'region_kowloon',
    districtId: 'district_tsim_sha_tsui',
    type: 'police_station',
    category: 'police',
    summary: '尖沙咀旅游、码头、酒店和娱乐场所周边的警务节点。',
    publicKnowledge: '常处理游客、夜场、码头和商业区相关警务。',
    currentState: '白天与夜间压力差异很大，既有游客事务，也有夜间冲突。',
    streetAddressText: '尖沙咀一带',
    roadAnchors: ['梳士巴利道', '弥敦道', '广东道'],
    relatedActorIds: [],
    relatedCaseIds: [],
    relatedPressureIds: [],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.53, y: 0.53, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_wan_chai_police_headquarters',
    name: '湾仔警察总部',
    nameZh: '湾仔警察总部',
    nameEn: 'Police Headquarters, Wan Chai',
    aliases: ['警察总部', '湾仔总部', 'PHQ'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_wan_chai',
    type: 'police_headquarters',
    category: 'police',
    summary: '皇家香港警察的总部级地点，承载高层指挥、行政、行动和跨区协调。',
    publicKnowledge: '市民知道这里不是普通报案地点，而是警队总部和高层系统所在地。',
    currentState: '总部节奏更制度化，信息、命令和压力从这里向各区传导。',
    streetAddressText: '湾仔军器厂街一带',
    roadAnchors: ['军器厂街', '告士打道', '湾仔'],
    relatedActorIds: [],
    relatedCaseIds: [],
    relatedPressureIds: [],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.50, y: 0.62, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_icac_headquarters',
    name: '廉政公署总部',
    nameZh: '廉政公署总部',
    nameEn: 'ICAC Headquarters',
    aliases: ['廉署总部', 'ICAC'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_admiralty_wan_chai',
    type: 'government_agency',
    category: 'oversight',
    summary: '廉政公署的核心办公地点，是警队、政府和商业腐败风险的制度性压力源。',
    publicKnowledge: '市民知道廉署独立调查贪污，警队内部也清楚它的威慑力。',
    currentState: '任何灰色利益、黑钱和异常人情都可能在未来成为风险种子。',
    streetAddressText: '金钟/湾仔一带',
    roadAnchors: ['金钟', '湾仔', '告士打道'],
    relatedActorIds: [],
    relatedCaseIds: [],
    relatedPressureIds: [],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.49, y: 0.62, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_broadcast_drive',
    name: '广播道',
    nameZh: '广播道',
    nameEn: 'Broadcast Drive',
    aliases: ['九龙塘广播道', '五台山'],
    regionId: 'region_kowloon',
    districtId: 'district_kowloon_tong',
    type: 'media_cluster',
    category: 'media_entertainment',
    summary: '九龙塘媒体机构集中地，是电视、电台、娱乐圈与公众舆论交汇的象征地点。',
    publicKnowledge: '普通市民知道这里和电视台、电台、明星新闻有关。',
    currentState: '媒体与娱乐圈消息会从这里扩散，也可能把个别警务事件推向公众视野。',
    streetAddressText: '九龙塘广播道',
    roadAnchors: ['广播道', '窝打老道', '九龙塘'],
    relatedActorIds: [],
    relatedCaseIds: [],
    relatedPressureIds: [],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.57, y: 0.36, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_tsim_sha_tsui_star_ferry_pier',
    name: '尖沙咀天星码头',
    nameZh: '尖沙咀天星码头',
    nameEn: 'Tsim Sha Tsui Star Ferry Pier',
    aliases: ['尖沙咀码头', '天星码头尖沙咀', 'TST Star Ferry Pier'],
    regionId: 'region_kowloon',
    districtId: 'district_tsim_sha_tsui',
    type: 'ferry_pier',
    category: 'transport_landmark',
    summary: '连接九龙与港岛的标志性码头，游客、市民、上班族和夜归人流交错。',
    publicKnowledge: '这是横渡维港的重要公共交通点，也是尖沙咀海旁的标志性地点。',
    currentState: '白天人流密集，夜里仍有游客和夜归人经过。',
    streetAddressText: '尖沙咀海旁',
    roadAnchors: ['梳士巴利道', '尖沙咀海旁'],
    relatedActorIds: [],
    relatedCaseIds: [],
    relatedPressureIds: [],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.52, y: 0.56, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_central_star_ferry_pier',
    name: '中环天星码头',
    nameZh: '中环天星码头',
    nameEn: 'Central Star Ferry Pier',
    aliases: ['中环码头', '天星码头中环', 'Central Ferry Pier'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central',
    type: 'ferry_pier',
    category: 'transport_landmark',
    summary: '港岛中环一侧的重要渡轮节点，连着金融、政府办公和维港交通。',
    publicKnowledge: '市民熟悉的渡海交通点，周边经常有上班族、游客和小贩。',
    currentState: '高峰期人潮明显，晚间较冷清但仍有渡轮往来。',
    streetAddressText: '中环海旁',
    roadAnchors: ['中环海旁', '干诺道中'],
    relatedActorIds: [],
    relatedCaseIds: [],
    relatedPressureIds: [],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.47, y: 0.58, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_temple_street_night_market',
    name: '庙街夜市',
    nameZh: '庙街夜市',
    nameEn: 'Temple Street Night Market',
    aliases: ['庙街', 'Temple Street'],
    regionId: 'region_kowloon',
    districtId: 'district_yau_ma_tei',
    type: 'street_market',
    category: 'street_life',
    summary: '油麻地夜市与街头生活集中地，摊贩、游客、街坊、人情和灰色边缘活动并存。',
    publicKnowledge: '市民知道这里夜里热闹，也知道容易出现争执、扒手和街头纠纷。',
    currentState: '夜色越深，人声、油烟和人情压力越浓。',
    streetAddressText: '油麻地庙街',
    roadAnchors: ['庙街', '佐敦道', '甘肃街'],
    relatedActorIds: [],
    relatedCaseIds: [],
    relatedPressureIds: [],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.54, y: 0.48, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_kowloon_walled_city',
    name: '九龙城寨',
    nameZh: '九龙城寨',
    nameEn: 'Kowloon Walled City',
    aliases: ['城寨', '九龙寨城'],
    regionId: 'region_kowloon',
    districtId: 'district_kowloon_city',
    type: 'dense_enclave',
    category: 'landmark_pressure_zone',
    summary: '高度密集、法律边界和社会关系复杂的城市空间，适合承载医疗、工厂、债务、黑市和治安压力。',
    publicKnowledge: '许多人知道这里复杂、拥挤、难管，也知道它不是普通住宅区。',
    currentState: '内部关系密集，外部制度介入需要谨慎处理。',
    streetAddressText: '九龙城一带',
    roadAnchors: ['九龙城', '东头村道'],
    relatedActorIds: [],
    relatedCaseIds: [],
    relatedPressureIds: [],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.61, y: 0.42, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_shaw_brothers_studio',
    name: '邵氏片场',
    nameZh: '邵氏片场',
    nameEn: 'Shaw Brothers Studio',
    aliases: ['邵氏影城', '清水湾片场'],
    regionId: 'region_new_territories',
    districtId: 'district_clear_water_bay',
    type: 'film_studio',
    category: 'media_entertainment',
    summary: '清水湾一带的电影工业地点，可连接演员、龙虎武师、投资、黑白两道传闻和娱乐圈压力。',
    publicKnowledge: '影迷和业内人士知道这里与港片制作密切相关。',
    currentState: '片场人员复杂，拍摄、投资和江湖传闻偶尔交错。',
    streetAddressText: '清水湾一带',
    roadAnchors: ['清水湾道'],
    relatedActorIds: [],
    relatedCaseIds: [],
    relatedPressureIds: [],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.71, y: 0.47, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_golden_harvest_studio',
    name: '嘉禾片场',
    nameZh: '嘉禾片场',
    nameEn: 'Golden Harvest Studio',
    aliases: ['嘉禾', '嘉禾电影'],
    regionId: 'region_hong_kong',
    districtId: 'district_unknown',
    type: 'film_company',
    category: 'media_entertainment',
    summary: '港片黄金时代的重要电影公司相关地点，适合连接明星、制片、投资和娱乐圈新闻。',
    publicKnowledge: '市民知道嘉禾是重要电影公司，和明星、动作片、票房新闻有关。',
    currentState: '娱乐圈资源、媒体曝光和商业利益可能在此交汇。',
    streetAddressText: '香港电影工业相关地点',
    roadAnchors: [],
    relatedActorIds: [],
    relatedCaseIds: [],
    relatedPressureIds: [],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.63, y: 0.50, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_hong_kong_coliseum',
    name: '香港体育馆',
    nameZh: '香港体育馆',
    nameEn: 'Hong Kong Coliseum',
    aliases: ['红馆', 'Hong Kong Coliseum'],
    regionId: 'region_kowloon',
    districtId: 'district_hung_hom',
    type: 'performance_venue',
    category: 'media_entertainment',
    summary: '红磡大型演出与公众活动场地，连接歌星、粉丝、人群秩序和媒体曝光。',
    publicKnowledge: '市民知道红馆是演唱会和大型活动场地。',
    currentState: '大型活动时人潮、安保和媒体关注会明显上升。',
    streetAddressText: '红磡',
    roadAnchors: ['畅运道', '红磡'],
    relatedActorIds: [],
    relatedCaseIds: [],
    relatedPressureIds: [],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.56, y: 0.53, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_harbour_city',
    name: '海港城',
    nameZh: '海港城',
    nameEn: 'Harbour City',
    aliases: ['Harbour City', '尖沙咀海港城'],
    regionId: 'region_kowloon',
    districtId: 'district_tsim_sha_tsui',
    type: 'shopping_complex',
    category: 'commercial_landmark',
    summary: '尖沙咀大型商业地点，游客、消费、店铺、保安和商业纠纷集中。',
    publicKnowledge: '市民和游客都知道这里是尖沙咀重要购物地点。',
    currentState: '日常人流密集，适合发生消费、盗窃、保安和名人出没相关事件。',
    streetAddressText: '尖沙咀广东道',
    roadAnchors: ['广东道', '尖沙咀'],
    relatedActorIds: [],
    relatedCaseIds: [],
    relatedPressureIds: [],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.51, y: 0.53, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_central_police_station',
    name: '中区警署',
    nameZh: '中区警署',
    nameEn: 'Central Police Station',
    aliases: ['中区差馆', 'Central Station'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central',
    type: 'police_station',
    category: 'police',
    summary: '中环旧城与商业核心之间的警务锚点，连接金融区、苏豪、码头和殖民地行政核心。',
    publicKnowledge: '市民知道这里是中区一带报案和警务处理的重要入口。',
    currentState: '商业区白天节奏紧，夜间则有酒吧、码头和旧街区压力。',
    streetAddressText: '中环荷李活道一带',
    roadAnchors: ['荷李活道', '中环', '摆花街'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.45, y: 0.62, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_western_police_station',
    name: '西区警署',
    nameZh: '西区警署',
    nameEn: 'Western Police Station',
    aliases: ['西区差馆'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_sheung_wan_sai_ying_pun',
    type: 'police_station',
    category: 'police',
    summary: '上环至西营盘一带的警务节点，靠近旧楼、海味街、码头和医院生活圈。',
    publicKnowledge: '附近居民知道这里处理西区街坊、商铺和码头周边事务。',
    currentState: '旧区人情、店铺纠纷和海旁交通问题经常交织。',
    streetAddressText: '西营盘/上环一带',
    roadAnchors: ['德辅道西', '皇后大道西', '西营盘'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.40, y: 0.63, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_aberdeen_police_station',
    name: '香港仔警署',
    nameZh: '香港仔警署',
    nameEn: 'Aberdeen Police Station',
    aliases: ['香港仔差馆'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_aberdeen',
    type: 'police_station',
    category: 'police',
    summary: '港岛南区的警务节点，连接渔港、水上社区、工业仓库和海边旅游压力。',
    publicKnowledge: '南区街坊和渔民熟悉这里处理港湾、船家和社区纠纷。',
    currentState: '渔港、码头、旅游和旧式社区压力混在一起。',
    streetAddressText: '香港仔一带',
    roadAnchors: ['香港仔大道', '鸭脷洲', '避风塘'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.44, y: 0.77, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_wan_chai_police_station',
    name: '湾仔警署',
    nameZh: '湾仔警署',
    nameEn: 'Wan Chai Police Station',
    aliases: ['湾仔差馆'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_wan_chai',
    type: 'police_station',
    category: 'police',
    summary: '湾仔街面警务节点，处理酒吧区、商厦、旧楼、码头和会展前身地带的复杂人流。',
    publicKnowledge: '湾仔居民、夜场人员和上班族都知道这里是常见报案入口。',
    currentState: '白天商业人流和夜间酒吧压力转换明显。',
    streetAddressText: '湾仔军器厂街/告士打道一带',
    roadAnchors: ['军器厂街', '洛克道', '告士打道'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.52, y: 0.63, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_north_point_police_station',
    name: '北角警署',
    nameZh: '北角警署',
    nameEn: 'North Point Police Station',
    aliases: ['北角差馆'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_north_point',
    type: 'police_station',
    category: 'police',
    summary: '港岛东旧社区与码头交通交界的警务节点，连接电车线、住宅、戏院和小商户。',
    publicKnowledge: '北角街坊知道这里处理东区日常治安和街面纠纷。',
    currentState: '居民区、商铺和交通节点让事件常带街坊人情。',
    streetAddressText: '北角英皇道一带',
    roadAnchors: ['英皇道', '北角码头', '电气道'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.63, y: 0.64, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_chai_wan_police_station',
    name: '柴湾警署',
    nameZh: '柴湾警署',
    nameEn: 'Chai Wan Police Station',
    aliases: ['柴湾差馆'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_chai_wan',
    type: 'police_station',
    category: 'police',
    summary: '港岛东端屋邨、工厦、地铁和海旁社区的警务锚点。',
    publicKnowledge: '区内居民知道这里处理屋邨、工业区和交通相关事务。',
    currentState: '新市镇边缘、工厦和住宅区问题经常交叉。',
    streetAddressText: '柴湾一带',
    roadAnchors: ['柴湾道', '小西湾', '港铁柴湾站'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.73, y: 0.66, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_sham_shui_po_police_station',
    name: '深水埗警署',
    nameZh: '深水埗警署',
    nameEn: 'Sham Shui Po Police Station',
    aliases: ['深水埗差馆'],
    regionId: 'region_kowloon',
    districtId: 'district_sham_shui_po',
    type: 'police_station',
    category: 'police',
    summary: '旧楼、电子街、基层家庭和街市密集区的警务锚点。',
    publicKnowledge: '街坊知道这里常处理小贩、盗窃、家庭和旧区治安问题。',
    currentState: '贫困、旧楼、街市和小生意让警务带强烈基层质感。',
    streetAddressText: '深水埗一带',
    roadAnchors: ['长沙湾道', '鸭寮街', '福华街'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.48, y: 0.38, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_kowloon_city_police_station',
    name: '九龙城警署',
    nameZh: '九龙城警署',
    nameEn: 'Kowloon City Police Station',
    aliases: ['九龙城差馆'],
    regionId: 'region_kowloon',
    districtId: 'district_kowloon_city',
    type: 'police_station',
    category: 'police',
    summary: '靠近城寨、启德航道和旧区餐馆街的警务节点。',
    publicKnowledge: '区内居民知道这里面对城寨外围、旧楼和机场周边压力。',
    currentState: '城寨、机场噪音、旧楼餐馆和街坊网络让辖区复杂。',
    streetAddressText: '九龙城一带',
    roadAnchors: ['太子道东', '衙前围道', '九龙城'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.61, y: 0.44, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_hung_hom_police_station',
    name: '红磡警署',
    nameZh: '红磡警署',
    nameEn: 'Hung Hom Police Station',
    aliases: ['红磡差馆'],
    regionId: 'region_kowloon',
    districtId: 'district_hung_hom',
    type: 'police_station',
    category: 'police',
    summary: '车站、红馆、船坞旧区和海底隧道人流交界处的警务节点。',
    publicKnowledge: '居民和旅客知道红磡警务常牵涉交通、人群和旧区事务。',
    currentState: '演出、火车站、隧道口和住宅旧区让事件变化快。',
    streetAddressText: '红磡一带',
    roadAnchors: ['畅运道', '红磡站', '漆咸道北'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.57, y: 0.52, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_kwun_tong_police_station',
    name: '观塘警署',
    nameZh: '观塘警署',
    nameEn: 'Kwun Tong Police Station',
    aliases: ['观塘差馆'],
    regionId: 'region_kowloon',
    districtId: 'district_kwun_tong',
    type: 'police_station',
    category: 'police',
    summary: '东九龙工业与屋邨密集区的警务节点，连接工厂、码头、旧楼和基层家庭。',
    publicKnowledge: '观塘工人和居民知道这里处理工业区与屋邨治安。',
    currentState: '厂区下班、屋邨人情和运输压力常常叠在一起。',
    streetAddressText: '观塘道一带',
    roadAnchors: ['观塘道', '开源道', '牛头角'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.67, y: 0.49, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_tsuen_wan_police_station',
    name: '荃湾警署',
    nameZh: '荃湾警署',
    nameEn: 'Tsuen Wan Police Station',
    aliases: ['荃湾差馆'],
    regionId: 'region_new_territories',
    districtId: 'district_tsuen_wan',
    type: 'police_station',
    category: 'police',
    summary: '新界西工业、住宅和交通交汇地的警务锚点。',
    publicKnowledge: '荃湾居民和厂区工人知道这里处理新市镇与工业区事务。',
    currentState: '工厂、屋邨、地铁和货运把新界西压力带到警署。',
    streetAddressText: '荃湾一带',
    roadAnchors: ['青山公路', '荃湾站', '杨屋道'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.35, y: 0.30, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_sha_tin_police_station',
    name: '沙田警署',
    nameZh: '沙田警署',
    nameEn: 'Sha Tin Police Station',
    aliases: ['沙田差馆'],
    regionId: 'region_new_territories',
    districtId: 'district_sha_tin',
    type: 'police_station',
    category: 'police',
    summary: '新市镇、马场、大学和东铁线交汇区域的警务节点。',
    publicKnowledge: '沙田居民知道这里处理新市镇家庭、交通和大型活动事务。',
    currentState: '新屋邨、铁路、商场和马场活动会制造不同节奏的警务压力。',
    streetAddressText: '沙田一带',
    roadAnchors: ['沙田站', '城门河', '大涌桥路'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.57, y: 0.24, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_yuen_long_police_station',
    name: '元朗警署',
    nameZh: '元朗警署',
    nameEn: 'Yuen Long Police Station',
    aliases: ['元朗差馆'],
    regionId: 'region_new_territories',
    districtId: 'district_yuen_long',
    type: 'police_station',
    category: 'police',
    summary: '新界西北墟市、乡事、人情和跨境边缘活动的警务节点。',
    publicKnowledge: '元朗居民知道这里处理墟市、村落、交通和地方势力相关事务。',
    currentState: '乡情、商铺、货运和地方网络让事件不只是街面纠纷。',
    streetAddressText: '元朗市中心一带',
    roadAnchors: ['青山公路元朗段', '元朗大马路'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.21, y: 0.24, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_tuen_mun_police_station',
    name: '屯门警署',
    nameZh: '屯门警署',
    nameEn: 'Tuen Mun Police Station',
    aliases: ['屯门差馆'],
    regionId: 'region_new_territories',
    districtId: 'district_tuen_mun',
    type: 'police_station',
    category: 'police',
    summary: '新界西大型屋邨、新市镇边缘和海旁交通的警务锚点。',
    publicKnowledge: '屯门居民知道这里处理屋邨、轻工业和新市镇治安。',
    currentState: '远离市区的距离感，让家庭、青年和交通问题更集中。',
    streetAddressText: '屯门市中心一带',
    roadAnchors: ['屯门公路', '屯门市中心', '青山湾'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.14, y: 0.30, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_central_magistracy',
    name: '中央裁判司署',
    nameZh: '中央裁判司署',
    nameEn: 'Central Magistracy',
    aliases: ['中区裁判司署', 'Central Magistrates Court'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central',
    type: 'magistracy',
    category: 'government_legal',
    summary: '旧中区司法建筑，连接警务、检控、保释、羁押和殖民地法律秩序。',
    publicKnowledge: '市民知道案件从警署走向法庭，往往会在这里出现。',
    currentState: '法庭、警车、律师和家属等待构成压抑的制度场面。',
    streetAddressText: '中环荷李活道一带',
    roadAnchors: ['荷李活道', '亚毕诺道', '中区警署'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.45, y: 0.61, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_supreme_court_building',
    name: '最高法院大楼',
    nameZh: '最高法院大楼',
    nameEn: 'Supreme Court Building',
    aliases: ['最高法院', 'High Court / Supreme Court'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_admiralty',
    type: 'court',
    category: 'government_legal',
    summary: '殖民地法律系统的高层司法锚点，适合承载重大案件、政治敏感争议和制度压力。',
    publicKnowledge: '市民知道这里代表更高层级的法庭和法律权威。',
    currentState: '律师、记者、警员和当事人让这里天然带有紧张感。',
    streetAddressText: '金钟/中环一带',
    roadAnchors: ['金钟道', '法院道', '皇后大道中'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.48, y: 0.61, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_government_house',
    name: '总督府',
    nameZh: '总督府',
    nameEn: 'Government House',
    aliases: ['港督府'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central',
    type: 'government_residence',
    category: 'government_legal',
    summary: '港英行政权力的象征性高地，日常距离玩家很远，但会通过政策和高层命令形成背景压力。',
    publicKnowledge: '市民知道这里是港督及高层行政象征。',
    currentState: '通常只在重大事件、礼宾、安全和高层政治压力中进入故事。',
    streetAddressText: '中环上亚厘毕道',
    roadAnchors: ['上亚厘毕道', '花园道', '中环'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.46, y: 0.60, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_murray_building',
    name: '美利大厦',
    nameZh: '美利大厦',
    nameEn: 'Murray Building',
    aliases: ['Murray Building'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central_admiralty',
    type: 'government_office',
    category: 'government_legal',
    summary: '中环政府办公锚点，适合承载部门文件、行政命令和跨部门协调。',
    publicKnowledge: '市民对具体办公室未必熟悉，但知道中环政府机关集中。',
    currentState: '行政文书和内部命令在这里显得冷静而有距离。',
    streetAddressText: '花园道一带',
    roadAnchors: ['花园道', '红棉路', '中环'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.47, y: 0.60, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_victoria_prison',
    name: '域多利监狱',
    nameZh: '域多利监狱',
    nameEn: 'Victoria Prison',
    aliases: ['Victoria Gaol', '中区监狱'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central',
    type: 'prison',
    category: 'government_legal',
    summary: '旧中区惩教设施，与警署、裁判司署和殖民地法律秩序形成制度三角。',
    publicKnowledge: '市民知道这里和羁押、惩教及旧中区司法建筑有关。',
    currentState: '高墙、铁门和等候家属让这里有强烈压迫感。',
    streetAddressText: '中环荷李活道一带',
    roadAnchors: ['荷李活道', '奥卑利街', '中区警署'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.445, y: 0.615, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_hong_kong_city_hall',
    name: '香港大会堂',
    nameZh: '香港大会堂',
    nameEn: 'Hong Kong City Hall',
    aliases: ['大会堂', 'City Hall'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central',
    type: 'civic_venue',
    category: 'civic_landmark',
    summary: '中环公共文化和市政活动锚点，连接演出、集会、婚姻登记和政府礼仪。',
    publicKnowledge: '市民熟悉这里的演出、市政和公共活动功能。',
    currentState: '白天正式、晚上带文化场馆人流，适合公共事件和媒体场面。',
    streetAddressText: '中环爱丁堡广场',
    roadAnchors: ['爱丁堡广场', '皇后像广场', '大会堂'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.475, y: 0.595, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_hsbc_main_building',
    name: '汇丰总行大厦',
    nameZh: '汇丰总行大厦',
    nameEn: 'HSBC Main Building',
    aliases: ['汇丰总行', 'HSBC Headquarters'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central',
    type: 'bank_headquarters',
    category: 'finance_commercial',
    summary: '中环金融权力的核心符号，连接银行、地产、外汇、商业贷款和上层社交。',
    publicKnowledge: '市民知道汇丰总行是香港金融中心最醒目的银行地标之一。',
    currentState: '白天人流和钱流极密，任何异常都会牵动商业和制度神经。',
    streetAddressText: '中环皇后大道中一号',
    roadAnchors: ['皇后大道中', '德辅道中', '遮打道'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.47, y: 0.60, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_exchange_square',
    name: '交易广场',
    nameZh: '交易广场',
    nameEn: 'Exchange Square',
    aliases: ['交易广场', 'Exchange Square Central'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central',
    type: 'office_finance_complex',
    category: 'finance_commercial',
    summary: '中环交易、金融办公室和巴士总站交汇的现代商业锚点。',
    publicKnowledge: '市民知道这里是中环金融与交通节点之一。',
    currentState: '证券、地产、银行和通勤人流把这里变成消息密集区。',
    streetAddressText: '中环康乐广场一带',
    roadAnchors: ['康乐广场', '交易广场', '中环巴士总站'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.465, y: 0.585, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_jardine_house',
    name: '怡和大厦',
    nameZh: '怡和大厦',
    nameEn: 'Jardine House',
    aliases: ['康乐大厦', 'Jardine House'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central',
    type: 'office_tower',
    category: 'finance_commercial',
    summary: '中环老牌英资商业权力地标，适合连接洋行、航运、地产和金融消息。',
    publicKnowledge: '许多市民知道它是中环醒目的商厦地标。',
    currentState: '外资公司、律师、银行和地产人流在这里交错。',
    streetAddressText: '中环康乐广场',
    roadAnchors: ['康乐广场', '干诺道中', '中环'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.468, y: 0.59, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_hang_seng_bank_headquarters',
    name: '恒生银行总行',
    nameZh: '恒生银行总行',
    nameEn: 'Hang Seng Bank Headquarters',
    aliases: ['恒生总行'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central_sheung_wan',
    type: 'bank_headquarters',
    category: 'finance_commercial',
    summary: '本地银行网络的重要锚点，连接中小商户、按揭、存款和家庭经济压力。',
    publicKnowledge: '市民熟悉恒生作为本地重要银行品牌。',
    currentState: '柜台、贷款、商户账户和家庭存款让它贴近日常金融。',
    streetAddressText: '中环/上环一带',
    roadAnchors: ['德辅道中', '中环', '上环'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.455, y: 0.60, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_standard_chartered_bank_building',
    name: '渣打银行大厦',
    nameZh: '渣打银行大厦',
    nameEn: 'Standard Chartered Bank Building',
    aliases: ['渣打银行', 'Standard Chartered'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central',
    type: 'bank_office',
    category: 'finance_commercial',
    summary: '中环另一处外资银行锚点，适合连接国际账户、商业信用和殖民地商业网络。',
    publicKnowledge: '市民知道渣打是香港主要发钞银行之一。',
    currentState: '外资银行的冷静秩序和本地商户压力在这里交叉。',
    streetAddressText: '中环德辅道中一带',
    roadAnchors: ['德辅道中', '毕打街', '中环'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.472, y: 0.602, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_the_landmark_central',
    name: '置地广场',
    nameZh: '置地广场',
    nameEn: 'The Landmark',
    aliases: ['置地', 'Landmark Central'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central',
    type: 'luxury_shopping_complex',
    category: 'finance_commercial',
    summary: '中环高端消费和商业社交地点，连接洋行、律师、银行家和名流消费。',
    publicKnowledge: '市民知道这里是中环高级商场和写字楼地标。',
    currentState: '体面、金钱和阶层距离感在这里非常明显。',
    streetAddressText: '中环置地广场',
    roadAnchors: ['毕打街', '皇后大道中', '置地广场'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.468, y: 0.605, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_admiralty_commercial_district',
    name: '金钟商业区',
    nameZh: '金钟商业区',
    nameEn: 'Admiralty Commercial District',
    aliases: ['金钟', 'Admiralty offices'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_admiralty',
    type: 'office_government_district',
    category: 'finance_commercial',
    summary: '政府、商厦、酒店和交通换乘交织的港岛核心节点。',
    publicKnowledge: '市民知道金钟是上班、换乘和政府商业机构密集的地方。',
    currentState: '西装人流、警车、巴士和地铁站让这里节奏紧凑。',
    streetAddressText: '金钟一带',
    roadAnchors: ['金钟道', '夏悫道', '海富中心'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.50, y: 0.61, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_sogo_causeway_bay',
    name: '崇光百货铜锣湾',
    nameZh: '崇光百货铜锣湾',
    nameEn: 'SOGO Causeway Bay',
    aliases: ['铜锣湾崇光', 'SOGO'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_causeway_bay',
    type: 'department_store',
    category: 'finance_commercial',
    summary: '铜锣湾大型百货消费锚点，连接购物人流、广告、游客和扒窃保安事务。',
    publicKnowledge: '市民知道铜锣湾崇光是热闹购物地标。',
    currentState: '节假日和傍晚人潮特别密集，消费纠纷和保安压力明显。',
    streetAddressText: '铜锣湾轩尼诗道一带',
    roadAnchors: ['轩尼诗道', '怡和街', '铜锣湾'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.56, y: 0.63, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_kwun_tong_industrial_area',
    name: '观塘工业区',
    nameZh: '观塘工业区',
    nameEn: 'Kwun Tong Industrial Area',
    aliases: ['观塘工厦区'],
    regionId: 'region_kowloon',
    districtId: 'district_kwun_tong',
    type: 'industrial_area',
    category: 'industrial_logistics',
    summary: '东九龙工厂、货仓和工厦密集区，适合承载劳资、欠薪、工伤、仓库和灰色加工。',
    publicKnowledge: '市民知道观塘有大量工厦和工厂岗位。',
    currentState: '机器声、货车、夜班和工人饭堂构成基层工业质感。',
    streetAddressText: '观塘开源道/巧明街一带',
    roadAnchors: ['开源道', '巧明街', '观塘道'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.68, y: 0.49, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_san_po_kong_industrial_area',
    name: '新蒲岗工业区',
    nameZh: '新蒲岗工业区',
    nameEn: 'San Po Kong Industrial Area',
    aliases: ['新蒲岗工厂区'],
    regionId: 'region_kowloon',
    districtId: 'district_san_po_kong',
    type: 'industrial_area',
    category: 'industrial_logistics',
    summary: '旧式轻工业和工厦街区，适合电子、塑胶、制衣、仓储和劳工纠纷。',
    publicKnowledge: '许多工人和街坊知道这里有密集工厂和货车出入。',
    currentState: '工厦楼梯、货梯、茶水间和临时仓库很适合发生小型事件。',
    streetAddressText: '新蒲岗一带',
    roadAnchors: ['大有街', '景福街', '彩虹道'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.62, y: 0.39, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_cheung_sha_wan_garment_district',
    name: '长沙湾制衣区',
    nameZh: '长沙湾制衣区',
    nameEn: 'Cheung Sha Wan Garment District',
    aliases: ['长沙湾制衣', '长沙湾工厂'],
    regionId: 'region_kowloon',
    districtId: 'district_cheung_sha_wan',
    type: 'garment_industry_district',
    category: 'industrial_logistics',
    summary: '制衣、批发、货车和工人家庭压力集中的西九龙工业锚点。',
    publicKnowledge: '市民知道长沙湾和制衣、批发、工厂有关。',
    currentState: '赶货、欠薪、样板房和夜班女工很容易成为剧情素材。',
    streetAddressText: '长沙湾道一带',
    roadAnchors: ['长沙湾道', '青山道', '荔枝角道'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.45, y: 0.37, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_lai_chi_kok_industrial_area',
    name: '荔枝角工业区',
    nameZh: '荔枝角工业区',
    nameEn: 'Lai Chi Kok Industrial Area',
    aliases: ['荔枝角工厦区'],
    regionId: 'region_kowloon',
    districtId: 'district_lai_chi_kok',
    type: 'industrial_area',
    category: 'industrial_logistics',
    summary: '西九龙工厦、批发、仓库和交通交接的工业地点。',
    publicKnowledge: '工人、司机和批发商熟悉这一带的货物流动。',
    currentState: '仓库、货车、工人饭盒和电梯排队带来强烈工业日常。',
    streetAddressText: '荔枝角一带',
    roadAnchors: ['荔枝角道', '青山道', '美孚'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.42, y: 0.36, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_tsuen_wan_industrial_area',
    name: '荃湾工业区',
    nameZh: '荃湾工业区',
    nameEn: 'Tsuen Wan Industrial Area',
    aliases: ['荃湾工厂区'],
    regionId: 'region_new_territories',
    districtId: 'district_tsuen_wan',
    type: 'industrial_area',
    category: 'industrial_logistics',
    summary: '新界西工厂、货仓和屋邨就业网络的工业锚点。',
    publicKnowledge: '市民知道荃湾有大量工厂和工业大厦。',
    currentState: '上下班潮、货运和工人家庭压力共同构成基层社会面。',
    streetAddressText: '荃湾柴湾角/杨屋道一带',
    roadAnchors: ['柴湾角街', '杨屋道', '荃湾'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.34, y: 0.32, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_kwai_chung_container_terminal',
    name: '葵涌货柜码头',
    nameZh: '葵涌货柜码头',
    nameEn: 'Kwai Chung Container Terminal',
    aliases: ['葵涌码头', '货柜码头'],
    regionId: 'region_new_territories',
    districtId: 'district_kwai_chung',
    type: 'container_terminal',
    category: 'industrial_logistics',
    summary: '香港货物流动和走私传闻的重量级锚点，连接司机、码头工、货代和海关风险。',
    publicKnowledge: '市民知道葵涌码头是大型货柜和物流重地。',
    currentState: '货柜、吊机、夜班和私货传闻让这里有强烈灰色潜力。',
    streetAddressText: '葵涌货柜码头',
    roadAnchors: ['葵涌', '货柜码头路', '青葵公路'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.31, y: 0.36, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_yau_tong_shipyard_area',
    name: '油塘船厂区',
    nameZh: '油塘船厂区',
    nameEn: 'Yau Tong Shipyard Area',
    aliases: ['油塘船厂', '油塘工业海旁'],
    regionId: 'region_kowloon',
    districtId: 'district_yau_tong',
    type: 'shipyard_industrial_area',
    category: 'industrial_logistics',
    summary: '东九龙海旁船厂和工业边缘地点，适合维修、海运、人情债和夜间冲突。',
    publicKnowledge: '附近工人和街坊知道这里与船厂、货仓和工业海旁有关。',
    currentState: '海风、铁锈、机油和夜班工人让这里有低调危险感。',
    streetAddressText: '油塘海旁一带',
    roadAnchors: ['茶果岭', '油塘', '观塘避风塘'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.69, y: 0.54, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_tai_kok_tsui_factory_blocks',
    name: '大角咀旧厂厦区',
    nameZh: '大角咀旧厂厦区',
    nameEn: 'Tai Kok Tsui Factory Blocks',
    aliases: ['大角咀厂厦', '大角咀工厂区'],
    regionId: 'region_kowloon',
    districtId: 'district_tai_kok_tsui',
    type: 'old_factory_blocks',
    category: 'industrial_logistics',
    summary: '西九龙旧厂厦、车房、仓库和旧楼混杂地带，适合临时藏身和劳工纠纷。',
    publicKnowledge: '街坊知道这里有不少旧式工业楼和车房。',
    currentState: '楼梯昏暗、货梯迟缓、车房和小仓库形成旧工业气味。',
    streetAddressText: '大角咀洋松街一带',
    roadAnchors: ['洋松街', '埃华街', '大角咀'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.53, y: 0.40, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_to_kwa_wan_workshops',
    name: '土瓜湾工场街区',
    nameZh: '土瓜湾工场街区',
    nameEn: 'To Kwa Wan Workshop Streets',
    aliases: ['土瓜湾车房', '土瓜湾工场'],
    regionId: 'region_kowloon',
    districtId: 'district_to_kwa_wan',
    type: 'workshop_district',
    category: 'industrial_logistics',
    summary: '车房、五金、小厂和旧住宅混在一起的九龙东南街区。',
    publicKnowledge: '附近居民知道这里有许多维修工场和小工业单位。',
    currentState: '铁闸、机油、旧楼天台和熟人网络让事件容易转入巷内。',
    streetAddressText: '土瓜湾一带',
    roadAnchors: ['马头角道', '土瓜湾道', '浙江街'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.60, y: 0.50, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_yau_ma_tei_fruit_market',
    name: '油麻地果栏',
    nameZh: '油麻地果栏',
    nameEn: 'Yau Ma Tei Fruit Market',
    aliases: ['果栏', '油麻地水果批发市场'],
    regionId: 'region_kowloon',
    districtId: 'district_yau_ma_tei',
    type: 'wholesale_market',
    category: 'industrial_logistics',
    summary: '夜间运货、批发、货车和街坊江湖气很重的水果批发锚点。',
    publicKnowledge: '市民知道果栏清晨和深夜最忙，货车和工人很多。',
    currentState: '木箱、水迹、货车灯和粗口声让这里很适合夜间事件。',
    streetAddressText: '油麻地窝打老道/石龙街一带',
    roadAnchors: ['窝打老道', '石龙街', '油麻地'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.535, y: 0.45, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_tv_city_clear_water_bay',
    name: '清水湾电视城',
    nameZh: '清水湾电视城',
    nameEn: 'TV City, Clear Water Bay',
    aliases: ['电视城', 'TVB电视城', '清水湾TV City'],
    regionId: 'region_new_territories',
    districtId: 'district_clear_water_bay',
    type: 'television_studio_complex',
    category: 'media_entertainment',
    summary: '电视制作、明星、布景、艺员和媒体工业的新兴锚点，适合连接娱乐圈与商业压力。',
    publicKnowledge: '市民知道电视台和明星制作与清水湾、广播道等地点有关。',
    currentState: '片场、通告、保安和记者让消息流动很快。',
    streetAddressText: '清水湾道一带',
    roadAnchors: ['清水湾道', '电视城', '将军澳边缘'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.72, y: 0.45, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_commercial_radio_broadcast_drive',
    name: '商业电台广播道',
    nameZh: '商业电台广播道',
    nameEn: 'Commercial Radio, Broadcast Drive',
    aliases: ['商台', '香港商业电台'],
    regionId: 'region_kowloon',
    districtId: 'district_kowloon_tong',
    type: 'radio_station',
    category: 'media_entertainment',
    summary: '电台节目、新闻、广告和娱乐圈消息交汇处。',
    publicKnowledge: '市民熟悉电台广播，也知道广播道聚集媒体机构。',
    currentState: '录音室、主持人、广告客户和听众热线让这里消息密集。',
    streetAddressText: '九龙塘广播道',
    roadAnchors: ['广播道', '窝打老道', '九龙塘'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.565, y: 0.355, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_rthk_broadcasting_house',
    name: '香港电台广播大厦',
    nameZh: '香港电台广播大厦',
    nameEn: 'RTHK Broadcasting House',
    aliases: ['香港电台', 'RTHK'],
    regionId: 'region_kowloon',
    districtId: 'district_kowloon_tong',
    type: 'public_broadcaster',
    category: 'media_entertainment',
    summary: '公共广播、新闻、文化节目和政府信息传播的重要锚点。',
    publicKnowledge: '市民知道香港电台是重要广播机构。',
    currentState: '新闻稿、采访、政府口径和文化节目在这里交错。',
    streetAddressText: '九龙塘广播道',
    roadAnchors: ['广播道', '香港电台', '九龙塘'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.575, y: 0.355, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_atv_broadcast_drive',
    name: '亚洲电视广播道',
    nameZh: '亚洲电视广播道',
    nameEn: 'ATV Broadcast Drive',
    aliases: ['亚视', 'ATV'],
    regionId: 'region_kowloon',
    districtId: 'district_kowloon_tong',
    type: 'television_station',
    category: 'media_entertainment',
    summary: '电视新闻、娱乐节目和艺员圈的媒体锚点。',
    publicKnowledge: '市民知道亚视是电视台之一，和新闻、剧集、艺人有关。',
    currentState: '电视台门口经常有记者、艺员车和等待消息的人。',
    streetAddressText: '九龙塘广播道',
    roadAnchors: ['广播道', '亚视', '九龙塘'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.558, y: 0.365, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_queen_elizabeth_stadium',
    name: '伊利沙伯体育馆',
    nameZh: '伊利沙伯体育馆',
    nameEn: 'Queen Elizabeth Stadium',
    aliases: ['伊馆', 'Queen Elizabeth Stadium'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_wan_chai',
    type: 'performance_sports_venue',
    category: 'media_entertainment',
    summary: '湾仔室内活动场地，连接演出、体育、集会、人群控制和媒体曝光。',
    publicKnowledge: '市民知道这里会举办演出、比赛和公众活动。',
    currentState: '大型活动时警务、票务、艺人和粉丝压力会集中。',
    streetAddressText: '湾仔爱群道一带',
    roadAnchors: ['爱群道', '湾仔', '皇后大道东'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.525, y: 0.645, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_lee_theatre',
    name: '利舞台',
    nameZh: '利舞台',
    nameEn: 'Lee Theatre',
    aliases: ['利舞台戏院'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_causeway_bay',
    type: 'theatre',
    category: 'media_entertainment',
    summary: '铜锣湾娱乐演出地标，连接歌星、戏院、名流和消费人流。',
    publicKnowledge: '老香港市民知道利舞台是重要表演与娱乐地标。',
    currentState: '演出前后人流密集，记者、粉丝和黄牛都可能出现。',
    streetAddressText: '铜锣湾波斯富街一带',
    roadAnchors: ['波斯富街', '轩尼诗道', '铜锣湾'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.565, y: 0.635, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_sunbeam_theatre',
    name: '新光戏院',
    nameZh: '新光戏院',
    nameEn: 'Sunbeam Theatre',
    aliases: ['新光', '新光戏院大剧场'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_north_point',
    type: 'opera_theatre',
    category: 'media_entertainment',
    summary: '粤剧、戏曲和旧派观众文化的重要锚点。',
    publicKnowledge: '北角街坊和戏迷知道新光戏院与粤剧演出有关。',
    currentState: '老观众、票房、后台和戏班人情构成独特娱乐圈支线。',
    streetAddressText: '北角英皇道一带',
    roadAnchors: ['英皇道', '北角', '书局街'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.625, y: 0.635, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_lan_kwai_fong',
    name: '兰桂坊',
    nameZh: '兰桂坊',
    nameEn: 'Lan Kwai Fong',
    aliases: ['LKF', '中环兰桂坊'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central',
    type: 'bar_nightlife_district',
    category: 'media_entertainment',
    summary: '中环夜生活、外籍社交、酒吧和商业人脉的集中地。',
    publicKnowledge: '市民知道这里夜晚热闹，常见酒吧、外籍人士和白领社交。',
    currentState: '酒精、金钱、语言差异和社交身份容易把小冲突放大。',
    streetAddressText: '中环兰桂坊一带',
    roadAnchors: ['兰桂坊', '德己立街', '云咸街'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.455, y: 0.615, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_wan_chai_lockhart_road_bars',
    name: '湾仔洛克道酒吧区',
    nameZh: '湾仔洛克道酒吧区',
    nameEn: 'Wan Chai Lockhart Road Bars',
    aliases: ['洛克道酒吧', '湾仔夜场'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_wan_chai',
    type: 'nightlife_district',
    category: 'media_entertainment',
    summary: '湾仔夜场、酒吧、外籍客、陪酒和警务边界复杂的街区。',
    publicKnowledge: '市民知道湾仔夜晚酒吧和娱乐场所集中。',
    currentState: '醉酒、金钱、性别、黑白两道人情和外籍身份容易交织。',
    streetAddressText: '湾仔洛克道一带',
    roadAnchors: ['洛克道', '谢斐道', '湾仔'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.52, y: 0.635, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_ocean_park',
    name: '海洋公园',
    nameZh: '海洋公园',
    nameEn: 'Ocean Park',
    aliases: ['香港海洋公园'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_wong_chuk_hang_aberdeen',
    type: 'theme_park',
    category: 'media_entertainment',
    summary: '港岛南大型游乐与旅游地标，连接家庭、游客、保安和公共意外。',
    publicKnowledge: '市民和游客都知道海洋公园是大型游乐地点。',
    currentState: '游客、学生、家庭和保安系统让这里适合轻重皆可的事件。',
    streetAddressText: '黄竹坑/南朗山一带',
    roadAnchors: ['黄竹坑', '南朗山', '香港仔隧道'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.51, y: 0.78, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_chungking_mansions',
    name: '重庆大厦',
    nameZh: '重庆大厦',
    nameEn: 'Chungking Mansions',
    aliases: ['重庆森林大厦', 'Chungking'],
    regionId: 'region_kowloon',
    districtId: 'district_tsim_sha_tsui',
    type: 'mixed_use_mansion',
    category: 'street_life',
    summary: '尖沙咀多国商贩、廉价旅馆、兑换、餐厅和灰色交易交织的高密度大厦。',
    publicKnowledge: '市民知道这里人员复杂、店铺密集，也常有旅客和外籍商贩。',
    currentState: '电梯、狭窄走廊、货币兑换和多语言人流让这里天然复杂。',
    streetAddressText: '尖沙咀弥敦道',
    roadAnchors: ['弥敦道', '尖沙咀', '么地道'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.525, y: 0.525, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_portland_street',
    name: '钵兰街',
    nameZh: '钵兰街',
    nameEn: 'Portland Street',
    aliases: ['旺角钵兰街'],
    regionId: 'region_kowloon',
    districtId: 'district_mong_kok_yau_ma_tei',
    type: 'red_light_street',
    category: 'street_life',
    summary: '旺角至油麻地夜场、旅馆、灰色生意和街头人情浓度很高的街道。',
    publicKnowledge: '许多市民知道钵兰街夜间复杂，不是普通商业街。',
    currentState: '霓虹、短租房、看场人和巡逻警让这里危险又日常。',
    streetAddressText: '旺角/油麻地钵兰街',
    roadAnchors: ['钵兰街', '登打士街', '亚皆老街'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.545, y: 0.445, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_fa_yuen_street',
    name: '花园街',
    nameZh: '花园街',
    nameEn: 'Fa Yuen Street',
    aliases: ['波鞋街', '花园街市集'],
    regionId: 'region_kowloon',
    districtId: 'district_mong_kok',
    type: 'street_market',
    category: 'street_life',
    summary: '旺角摊档、运动用品、游客、街坊和小贩管理压力集中的街道。',
    publicKnowledge: '市民知道花园街热闹、摊档密集、消费人流多。',
    currentState: '人群密度高，扒窃、争执和小贩执法都容易发生。',
    streetAddressText: '旺角花园街',
    roadAnchors: ['花园街', '亚皆老街', '旺角道'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.555, y: 0.425, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_tung_choi_street_ladies_market',
    name: '女人街',
    nameZh: '女人街',
    nameEn: 'Ladies Market, Tung Choi Street',
    aliases: ['通菜街', 'Ladies Market'],
    regionId: 'region_kowloon',
    districtId: 'district_mong_kok',
    type: 'street_market',
    category: 'street_life',
    summary: '旺角游客、小贩、假货传闻、扒手和街坊消费交织的街市锚点。',
    publicKnowledge: '市民和游客都知道女人街是旺角著名市集。',
    currentState: '摊档密、议价声高，人流一乱就容易发生纠纷。',
    streetAddressText: '旺角通菜街',
    roadAnchors: ['通菜街', '登打士街', '亚皆老街'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.552, y: 0.438, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_apliu_street_market',
    name: '鸭寮街',
    nameZh: '鸭寮街',
    nameEn: 'Apliu Street Market',
    aliases: ['鸭寮街电子街'],
    regionId: 'region_kowloon',
    districtId: 'district_sham_shui_po',
    type: 'electronics_street_market',
    category: 'street_life',
    summary: '旧电器、零件、二手货、基层商贩和可疑物品流动的深水埗街市锚点。',
    publicKnowledge: '市民知道鸭寮街可以买到各种电子零件和二手货。',
    currentState: '摊档、旧电器、修理师傅和问价人群构成低成本城市质感。',
    streetAddressText: '深水埗鸭寮街',
    roadAnchors: ['鸭寮街', '福华街', '桂林街'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.475, y: 0.385, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_graham_street_market',
    name: '嘉咸街街市',
    nameZh: '嘉咸街街市',
    nameEn: 'Graham Street Market',
    aliases: ['中环街市街', '嘉咸街'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central',
    type: 'wet_market_street',
    category: 'street_life',
    summary: '中环旧式街市、摊贩、上班族和旧街坊交错的生活锚点。',
    publicKnowledge: '附近居民和上班族知道这里有传统街市和熟食气味。',
    currentState: '金融区背后仍有湿滑路面、菜档和老街坊人情。',
    streetAddressText: '中环嘉咸街',
    roadAnchors: ['嘉咸街', '结志街', '中环'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.455, y: 0.62, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_sham_shui_po_street_markets',
    name: '深水埗街市群',
    nameZh: '深水埗街市群',
    nameEn: 'Sham Shui Po Street Markets',
    aliases: ['深水埗街市', '北河街街市'],
    regionId: 'region_kowloon',
    districtId: 'district_sham_shui_po',
    type: 'working_class_market_cluster',
    category: 'street_life',
    summary: '基层街市、排档、旧楼和家庭经济压力浓厚的街区。',
    publicKnowledge: '市民知道深水埗街市便宜、热闹，也很拥挤。',
    currentState: '街坊消息、赊账、人情和治安小案容易在这里自然发生。',
    streetAddressText: '深水埗北河街/福华街一带',
    roadAnchors: ['北河街', '福华街', '基隆街'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.485, y: 0.39, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_stanley_market',
    name: '赤柱市集',
    nameZh: '赤柱市集',
    nameEn: 'Stanley Market',
    aliases: ['赤柱市场'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_stanley',
    type: 'tourist_market',
    category: 'street_life',
    summary: '港岛南游客、市集、海边餐厅和外籍居民交错地点。',
    publicKnowledge: '游客和本地人都知道赤柱市集适合买纪念品和逛海边。',
    currentState: '旅游、外籍社区和远离市区的地理感形成独特节奏。',
    streetAddressText: '赤柱市集道一带',
    roadAnchors: ['赤柱市集道', '赤柱大街', '赤柱海旁'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.59, y: 0.84, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_causeway_bay_shopping_streets',
    name: '铜锣湾购物街区',
    nameZh: '铜锣湾购物街区',
    nameEn: 'Causeway Bay Shopping Streets',
    aliases: ['铜锣湾', '怡和街购物区'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_causeway_bay',
    type: 'shopping_street_cluster',
    category: 'street_life',
    summary: '百货、戏院、路面电车和密集消费人流构成的港岛商业街区。',
    publicKnowledge: '市民知道铜锣湾是购物、看电影和约人的热闹地点。',
    currentState: '傍晚和周末人潮极密，适合保安、扒窃、名人和街头冲突。',
    streetAddressText: '铜锣湾怡和街/轩尼诗道一带',
    roadAnchors: ['怡和街', '轩尼诗道', '记利佐治街'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.565, y: 0.625, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_queen_elizabeth_hospital',
    name: '伊利沙伯医院',
    nameZh: '伊利沙伯医院',
    nameEn: 'Queen Elizabeth Hospital',
    aliases: ['伊院', 'QEH'],
    regionId: 'region_kowloon',
    districtId: 'district_yau_ma_tei',
    type: 'public_hospital',
    category: 'healthcare',
    summary: '九龙大型公立医院，连接急症、伤人案、交通意外、家属等待和医护压力。',
    publicKnowledge: '市民知道伊利沙伯医院是九龙重要医院。',
    currentState: '急症室、警员录口供、家属焦急和医护疲劳经常同场。',
    streetAddressText: '加士居道一带',
    roadAnchors: ['加士居道', '伊利沙伯医院', '油麻地'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.545, y: 0.485, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_queen_mary_hospital',
    name: '玛丽医院',
    nameZh: '玛丽医院',
    nameEn: 'Queen Mary Hospital',
    aliases: ['玛丽', 'QMH'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_pok_fu_lam',
    type: 'public_hospital',
    category: 'healthcare',
    summary: '港岛大型医院与大学医学系统锚点，适合重大伤病、医疗人脉和制度压力。',
    publicKnowledge: '市民知道玛丽医院是港岛重要公立医院。',
    currentState: '山边医院、救护车、医学院和焦急家属形成沉重氛围。',
    streetAddressText: '薄扶林道一带',
    roadAnchors: ['薄扶林道', '香港大学', '玛丽医院'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.36, y: 0.67, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_kwong_wah_hospital',
    name: '广华医院',
    nameZh: '广华医院',
    nameEn: 'Kwong Wah Hospital',
    aliases: ['广华'],
    regionId: 'region_kowloon',
    districtId: 'district_yau_ma_tei_mong_kok',
    type: 'public_hospital',
    category: 'healthcare',
    summary: '旺角油麻地交界的医院锚点，连接街头伤人、家庭病痛和基层医疗压力。',
    publicKnowledge: '九龙街坊熟悉广华医院。',
    currentState: '急症、探病、街坊求助和警员跟进常常交错。',
    streetAddressText: '窝打老道一带',
    roadAnchors: ['窝打老道', '登打士街', '广华医院'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.545, y: 0.44, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_tung_wah_hospital',
    name: '东华医院',
    nameZh: '东华医院',
    nameEn: 'Tung Wah Hospital',
    aliases: ['东华'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_sheung_wan',
    type: 'public_hospital',
    category: 'healthcare',
    summary: '上环旧区医院和华人慈善医疗传统的锚点。',
    publicKnowledge: '市民知道东华医院历史悠久，和旧区医疗有关。',
    currentState: '老街坊、病房、慈善系统和家庭压力让这里人情很重。',
    streetAddressText: '上环普仁街一带',
    roadAnchors: ['普仁街', '荷李活道', '上环'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.425, y: 0.62, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_prince_of_wales_hospital',
    name: '威尔斯亲王医院',
    nameZh: '威尔斯亲王医院',
    nameEn: 'Prince of Wales Hospital',
    aliases: ['威院', 'PWH'],
    regionId: 'region_new_territories',
    districtId: 'district_sha_tin',
    type: 'teaching_hospital',
    category: 'healthcare',
    summary: '新界东大型医院和教学医疗锚点，连接沙田新市镇、大学和急症转送。',
    publicKnowledge: '新界东居民知道这里是大型医院。',
    currentState: '急症、医学生、救护车和新市镇家庭压力集中。',
    streetAddressText: '沙田银城街一带',
    roadAnchors: ['银城街', '沙田', '中文大学'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.59, y: 0.25, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_st_teresas_hospital',
    name: '圣德肋撒医院',
    nameZh: '圣德肋撒医院',
    nameEn: "St. Teresa's Hospital",
    aliases: ['法国医院', 'St Teresa Hospital'],
    regionId: 'region_kowloon',
    districtId: 'district_kowloon_city',
    type: 'private_hospital',
    category: 'healthcare',
    summary: '九龙私家医院锚点，适合连接中产、名人、私密医疗和警务保密需求。',
    publicKnowledge: '市民知道这是一所较有名的私家医院。',
    currentState: '私家病房、家属避人耳目和医院保安让这里适合低调剧情。',
    streetAddressText: '九龙城太子道西一带',
    roadAnchors: ['太子道西', '九龙城', '界限街'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.59, y: 0.43, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_hong_kong_sanatorium',
    name: '养和医院',
    nameZh: '养和医院',
    nameEn: 'Hong Kong Sanatorium & Hospital',
    aliases: ['养和', '跑马地养和'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_happy_valley',
    type: 'private_hospital',
    category: 'healthcare',
    summary: '港岛私家医疗锚点，连接富裕阶层、名流、隐私和高端医疗资源。',
    publicKnowledge: '市民知道养和是著名私家医院。',
    currentState: '安静、保密和身份差距让这里不同于公立急症室。',
    streetAddressText: '跑马地山村道一带',
    roadAnchors: ['山村道', '跑马地', '成和道'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.55, y: 0.66, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_kai_tak_airport',
    name: '启德机场',
    nameZh: '启德机场',
    nameEn: 'Kai Tak Airport',
    aliases: ['启德', '香港国际机场启德'],
    regionId: 'region_kowloon',
    districtId: 'district_kowloon_city_kai_tak',
    type: 'airport',
    category: 'transport_landmark',
    summary: '1988 年香港国际空港，连接旅客、走私传闻、航空货运、移民和城市噪音。',
    publicKnowledge: '市民知道启德机场就在九龙城旁边，飞机低飞是城市景观。',
    currentState: '航班、货运、接机人群和机场警务让这里信息密度很高。',
    streetAddressText: '九龙城启德一带',
    roadAnchors: ['太子道东', '启德机场', '九龙城'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.64, y: 0.44, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_hung_hom_station',
    name: '红磡车站',
    nameZh: '红磡车站',
    nameEn: 'Hung Hom Station',
    aliases: ['九龙车站', '红磡火车站'],
    regionId: 'region_kowloon',
    districtId: 'district_hung_hom',
    type: 'railway_station',
    category: 'transport_landmark',
    summary: '东铁、跨境铁路和红馆人流交汇的九龙交通锚点。',
    publicKnowledge: '市民知道红磡站是铁路和跨境交通重要节点。',
    currentState: '旅客、行李、月台广播和警员巡逻让这里天然适合相遇与追踪。',
    streetAddressText: '红磡畅运道',
    roadAnchors: ['畅运道', '红磡站', '红馆'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.555, y: 0.525, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_lo_wu_station',
    name: '罗湖站',
    nameZh: '罗湖站',
    nameEn: 'Lo Wu Station',
    aliases: ['罗湖口岸', 'Lo Wu Border'],
    regionId: 'region_new_territories',
    districtId: 'district_north',
    type: 'border_rail_station',
    category: 'transport_landmark',
    summary: '新界北跨境铁路和边境检查锚点，连接探亲、贸易、走私和身份压力。',
    publicKnowledge: '市民知道罗湖是前往内地的重要口岸。',
    currentState: '证件、行李、边境执法和两地人情让这里非常敏感。',
    streetAddressText: '新界北罗湖',
    roadAnchors: ['东铁线', '罗湖', '边境禁区'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.54, y: 0.08, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_macau_ferry_terminal',
    name: '港澳码头',
    nameZh: '港澳码头',
    nameEn: 'Macau Ferry Terminal',
    aliases: ['信德中心港澳码头', '港澳客轮码头'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_sheung_wan',
    type: 'ferry_terminal',
    category: 'transport_landmark',
    summary: '往来澳门的客运码头，连接赌业、旅客、现金、走私传闻和跨境人脉。',
    publicKnowledge: '市民知道这里是去澳门的重要码头。',
    currentState: '行李、现金、船票、旅客和社团传闻让这里很适合灰色线索。',
    streetAddressText: '上环信德中心',
    roadAnchors: ['干诺道中', '信德中心', '上环'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.43, y: 0.59, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_cross_harbour_tunnel',
    name: '海底隧道',
    nameZh: '海底隧道',
    nameEn: 'Cross-Harbour Tunnel',
    aliases: ['红隧', '海隧'],
    regionId: 'region_harbour',
    districtId: 'district_hung_hom_causeway_bay',
    type: 'road_tunnel',
    category: 'transport_landmark',
    summary: '连接红磡与港岛的关键道路隧道，影响跨海追车、交通堵塞和紧急行车时间。',
    publicKnowledge: '司机和市民都知道红隧是过海交通核心。',
    currentState: '堵车、收费亭、事故和警车过海会显著影响行动节奏。',
    streetAddressText: '红磡至铜锣湾海底隧道',
    roadAnchors: ['红磡', '铜锣湾', '康庄道'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.56, y: 0.58, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_mtr_central_station',
    name: '中环地铁站',
    nameZh: '中环地铁站',
    nameEn: 'MTR Central Station',
    aliases: ['中环站'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central',
    type: 'mtr_station',
    category: 'transport_landmark',
    summary: '港岛核心地铁站，连接中环金融区、上班人流和换乘压力。',
    publicKnowledge: '市民知道中环站是港岛最重要的地铁站之一。',
    currentState: '上下班时人流密集，追踪、失散和偶遇都很自然。',
    streetAddressText: '中环地铁站',
    roadAnchors: ['德辅道中', '毕打街', '中环站'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.465, y: 0.605, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_mtr_admiralty_station',
    name: '金钟地铁站',
    nameZh: '金钟地铁站',
    nameEn: 'MTR Admiralty Station',
    aliases: ['金钟站'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_admiralty',
    type: 'mtr_station',
    category: 'transport_landmark',
    summary: '港岛线与荃湾线换乘节点，连接政府、商业和过海人流。',
    publicKnowledge: '市民知道金钟站是重要换乘站。',
    currentState: '换乘人潮、出口选择和警员巡逻让这里容易错身而过。',
    streetAddressText: '金钟地铁站',
    roadAnchors: ['金钟道', '夏悫道', '金钟站'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.50, y: 0.615, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_mtr_kowloon_tong_station',
    name: '九龙塘地铁站',
    nameZh: '九龙塘地铁站',
    nameEn: 'MTR Kowloon Tong Station',
    aliases: ['九龙塘站'],
    regionId: 'region_kowloon',
    districtId: 'district_kowloon_tong',
    type: 'mtr_kcr_interchange',
    category: 'transport_landmark',
    summary: '地铁与九广铁路交汇节点，连接学校、广播道、新界东和市区。',
    publicKnowledge: '市民知道九龙塘站是重要换乘点。',
    currentState: '学生、上班族、铁路旅客和媒体区人流交错。',
    streetAddressText: '九龙塘站一带',
    roadAnchors: ['窝打老道', '九龙塘站', '广播道'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.565, y: 0.36, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_mtr_tsuen_wan_station',
    name: '荃湾地铁站',
    nameZh: '荃湾地铁站',
    nameEn: 'MTR Tsuen Wan Station',
    aliases: ['荃湾站'],
    regionId: 'region_new_territories',
    districtId: 'district_tsuen_wan',
    type: 'mtr_station',
    category: 'transport_landmark',
    summary: '荃湾线终端及新界西市镇交通锚点。',
    publicKnowledge: '市民知道荃湾站连接市区和新界西。',
    currentState: '上下班潮、商场人流和巴士换乘让这里消息流动快。',
    streetAddressText: '荃湾站一带',
    roadAnchors: ['荃湾站', '青山公路', '大河道'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.35, y: 0.31, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_wan_chai_star_ferry_pier',
    name: '湾仔天星码头',
    nameZh: '湾仔天星码头',
    nameEn: 'Wan Chai Star Ferry Pier',
    aliases: ['湾仔码头', 'Wan Chai Ferry Pier'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_wan_chai',
    type: 'ferry_pier',
    category: 'transport_landmark',
    summary: '湾仔海旁渡轮节点，连接会展前身地带、酒吧区、上班族和维港交通。',
    publicKnowledge: '市民知道湾仔码头可过海，也常作为约人地标。',
    currentState: '晚上海风、渡轮班次和酒吧区人流形成独特节奏。',
    streetAddressText: '湾仔海旁',
    roadAnchors: ['湾仔码头', '告士打道', '会议道'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.525, y: 0.585, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_happy_valley_racecourse',
    name: '跑马地马场',
    nameZh: '跑马地马场',
    nameEn: 'Happy Valley Racecourse',
    aliases: ['马场', '跑马地'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_happy_valley',
    type: 'racecourse',
    category: 'civic_landmark',
    summary: '赛马、投注、名流、司机和夜间人流的港岛标志性场所。',
    publicKnowledge: '市民知道跑马地马场和赛马、马会、投注有关。',
    currentState: '赛马日人潮、现金和情绪都会急剧升高。',
    streetAddressText: '跑马地马场',
    roadAnchors: ['黄泥涌道', '跑马地', '礼顿道'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.55, y: 0.65, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_victoria_park',
    name: '维多利亚公园',
    nameZh: '维多利亚公园',
    nameEn: 'Victoria Park',
    aliases: ['维园'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_causeway_bay',
    type: 'public_park',
    category: 'civic_landmark',
    summary: '港岛大型公共公园，连接晨运、市民活动、集会、人群和节庆。',
    publicKnowledge: '市民知道维园是铜锣湾重要公共公园。',
    currentState: '白天市民日常，节庆或集会时则会变成公共秩序焦点。',
    streetAddressText: '铜锣湾维多利亚公园',
    roadAnchors: ['高士威道', '兴发街', '铜锣湾'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.585, y: 0.62, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_university_of_hong_kong',
    name: '香港大学',
    nameZh: '香港大学',
    nameEn: 'University of Hong Kong',
    aliases: ['港大', 'HKU'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_pok_fu_lam_mid_levels',
    type: 'university',
    category: 'civic_landmark',
    summary: '港岛高等教育与医生、律师、学生活动、人脉阶层的重要锚点。',
    publicKnowledge: '市民知道港大是香港历史悠久的大学。',
    currentState: '学生、教授、校友和社会议题让这里具备知识分子网络。',
    streetAddressText: '薄扶林道',
    roadAnchors: ['薄扶林道', '般咸道', '港大'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.38, y: 0.66, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_chinese_university_of_hong_kong',
    name: '香港中文大学',
    nameZh: '香港中文大学',
    nameEn: 'Chinese University of Hong Kong',
    aliases: ['中大', 'CUHK'],
    regionId: 'region_new_territories',
    districtId: 'district_sha_tin_ma_liu_shui',
    type: 'university',
    category: 'civic_landmark',
    summary: '新界东大学山城，连接学生、知识界、铁路、医院和新市镇发展。',
    publicKnowledge: '市民知道中大位于沙田马料水一带。',
    currentState: '校园距离市区较远，学生网络与社会议题可能自然发酵。',
    streetAddressText: '沙田马料水',
    roadAnchors: ['马料水', '大学站', '吐露港'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.61, y: 0.22, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_peak_tram_lower_terminus',
    name: '山顶缆车花园道总站',
    nameZh: '山顶缆车花园道总站',
    nameEn: 'Peak Tram Lower Terminus',
    aliases: ['山顶缆车总站', '花园道缆车站'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central_mid_levels',
    type: 'tram_terminus',
    category: 'transport_landmark',
    summary: '连接中环与太平山顶的旅游和上流住宅交通锚点。',
    publicKnowledge: '市民和游客都知道山顶缆车是香港标志交通。',
    currentState: '游客、司机、豪宅住户和山路巡逻可以在这里接上。',
    streetAddressText: '花园道',
    roadAnchors: ['花园道', '红棉路', '山顶缆车'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.455, y: 0.64, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_repulse_bay',
    name: '浅水湾',
    nameZh: '浅水湾',
    nameEn: 'Repulse Bay',
    aliases: ['浅水湾海滩'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_repulse_bay',
    type: 'beach_residential_area',
    category: 'civic_landmark',
    summary: '港岛南海滩、豪宅、游客和司机路线的地标。',
    publicKnowledge: '市民知道浅水湾是著名海滩和高尚住宅区。',
    currentState: '白天旅游轻松，夜里则显得远离市区、道路幽静。',
    streetAddressText: '浅水湾海滩一带',
    roadAnchors: ['浅水湾道', '南湾道', '赤柱峡道'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.54, y: 0.80, precision: 'district_only' }
  }),
  canonicalPlace({
    placeId: 'place_queens_pier',
    name: '皇后码头',
    nameZh: '皇后码头',
    nameEn: "Queen's Pier",
    aliases: ['皇后码头', 'Queen Pier'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_central',
    type: 'ceremonial_pier',
    category: 'civic_landmark',
    summary: '中环海旁礼宾和公共记忆锚点，连接政府仪式、渡海、游客和城市象征。',
    publicKnowledge: '市民知道皇后码头是中环海旁重要码头地标。',
    currentState: '码头海风、礼宾记忆和市民等待让这里适合安静会面。',
    streetAddressText: '中环爱丁堡广场海旁',
    roadAnchors: ['爱丁堡广场', '中环海旁', '大会堂'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.47, y: 0.585, precision: 'approximate' }
  }),
  canonicalPlace({
    placeId: 'place_aberdeen_typhoon_shelter',
    name: '香港仔避风塘',
    nameZh: '香港仔避风塘',
    nameEn: 'Aberdeen Typhoon Shelter',
    aliases: ['香港仔渔港', 'Aberdeen Harbour'],
    regionId: 'region_hong_kong_island',
    districtId: 'district_aberdeen',
    type: 'typhoon_shelter',
    category: 'industrial_logistics',
    summary: '水上人、渔船、海鲜酒家、游客船和海上灰色路线的港岛南锚点。',
    publicKnowledge: '市民知道香港仔避风塘有船家和渔港景观。',
    currentState: '船灯、海水味、旅游舢舨和熟人水路让这里有独特叙事价值。',
    streetAddressText: '香港仔避风塘',
    roadAnchors: ['香港仔海旁', '鸭脷洲', '避风塘'],
    visualAnchor: { mapId: HK_1988_MAP_ID, x: 0.43, y: 0.78, precision: 'approximate' }
  })
];
