import type {
  ScreenCharacterCategory,
  ScreenCharacterMedium,
  ScreenCharacterSeedCard
} from './screenCharacterSeedTypes';
import { hkScreenCharacterCrimeExpansion } from './hkScreenCharacterCrimeExpansion';
import { hkScreenCharacterSocietyExpansion } from './hkScreenCharacterSocietyExpansion';

interface ScreenWork {
  id: string;
  title: string;
  titleEn?: string;
  medium: ScreenCharacterMedium;
  worldpackAvailableFromYear: number;
}

interface CharacterDraft {
  id: string;
  displayName: string;
  englishName?: string;
  aliases?: string[];
  gender: ScreenCharacterSeedCard['gender'];
  ageRange: ScreenCharacterSeedCard['ageRange'];
  category: ScreenCharacterCategory;
  currentIdentity?: ScreenCharacterSeedCard['currentIdentity'];
  publicIdentity: string;
  actualIdentitySummary?: string;
  profileSummary: string;
  personality: string;
  speechStyle: string;
  motivation: string;
  values: string;
  relationshipAnchors?: string[];
  sectors?: string[];
  usualPlaceIds?: ScreenCharacterSeedCard['usualPlaceIds'];
  accessRoutes?: string[];
  promptHooks?: string[];
  appearanceAnchor?: string;
  clothingAnchor?: string;
  capabilityProfile?: string;
  importance?: number;
}

const works = {
  policeCadet: {
    id: 'work_tv_police_cadet',
    title: '新扎师兄',
    titleEn: 'The Police Cadet',
    medium: 'television',
    worldpackAvailableFromYear: 1984
  },
  feudBrothers: {
    id: 'work_tv_feud_brothers',
    title: '流氓大亨',
    medium: 'television',
    worldpackAvailableFromYear: 1986
  },
  lookingBack: {
    id: 'work_tv_looking_back',
    title: '义不容情',
    titleEn: 'Looking Back in Anger',
    medium: 'television',
    worldpackAvailableFromYear: 1989
  },
  goodAndEvil: {
    id: 'work_tv_good_and_evil',
    title: '我本善良',
    titleEn: 'Blood of Good and Evil',
    medium: 'television',
    worldpackAvailableFromYear: 1990
  },
  grayWeb: {
    id: 'work_tv_gray_web',
    title: '灰网',
    medium: 'television',
    worldpackAvailableFromYear: 1991
  },
  greedOfMan: {
    id: 'work_tv_greed_of_man',
    title: '大时代',
    titleEn: 'The Greed of Man',
    medium: 'television',
    worldpackAvailableFromYear: 1992
  },
  filesOfJustice: {
    id: 'work_tv_files_of_justice',
    title: '壹号皇庭',
    titleEn: 'The File of Justice',
    medium: 'television',
    worldpackAvailableFromYear: 1992
  },
  silverTycoon: {
    id: 'work_tv_silver_tycoon',
    title: '银狐',
    titleEn: 'The Silver Tycoon',
    medium: 'television',
    worldpackAvailableFromYear: 1993
  },
  instinct: {
    id: 'work_tv_instinct',
    title: '笑看风云',
    titleEn: 'Instinct',
    medium: 'television',
    worldpackAvailableFromYear: 1994
  },
  detectiveFiles: {
    id: 'work_tv_detective_files',
    title: '刑事侦缉档案',
    titleEn: 'Detective Investigation Files',
    medium: 'television',
    worldpackAvailableFromYear: 1995
  },
  coldBloodWarmHeart: {
    id: 'work_tv_cold_blood_warm_heart',
    title: '天地男儿',
    titleEn: 'Cold Blood Warm Heart',
    medium: 'television',
    worldpackAvailableFromYear: 1996
  },
  acesGoPlaces: {
    id: 'work_film_aces_go_places',
    title: '最佳拍档',
    titleEn: 'Aces Go Places',
    medium: 'film',
    worldpackAvailableFromYear: 1982
  },
  longArmLaw: {
    id: 'work_film_long_arm_law',
    title: '省港旗兵',
    titleEn: 'Long Arm of the Law',
    medium: 'film',
    worldpackAvailableFromYear: 1984
  },
  policeStory: {
    id: 'work_film_police_story',
    title: '警察故事',
    titleEn: 'Police Story',
    medium: 'film',
    worldpackAvailableFromYear: 1985
  },
  betterTomorrow: {
    id: 'work_film_better_tomorrow',
    title: '英雄本色',
    titleEn: 'A Better Tomorrow',
    medium: 'film',
    worldpackAvailableFromYear: 1986
  },
  prisonOnFire: {
    id: 'work_film_prison_on_fire',
    title: '监狱风云',
    titleEn: 'Prison on Fire',
    medium: 'film',
    worldpackAvailableFromYear: 1987
  },
  asTearsGoBy: {
    id: 'work_film_as_tears_go_by',
    title: '旺角卡门',
    titleEn: 'As Tears Go By',
    medium: 'film',
    worldpackAvailableFromYear: 1988
  },
  godOfGamblers: {
    id: 'work_film_god_of_gamblers',
    title: '赌神',
    titleEn: 'God of Gamblers',
    medium: 'film',
    worldpackAvailableFromYear: 1989
  },
  killer: {
    id: 'work_film_killer',
    title: '喋血双雄',
    titleEn: 'The Killer',
    medium: 'film',
    worldpackAvailableFromYear: 1989
  },
  momentRomance: {
    id: 'work_film_moment_romance',
    title: '天若有情',
    titleEn: 'A Moment of Romance',
    medium: 'film',
    worldpackAvailableFromYear: 1990
  },
  fightBackSchool: {
    id: 'work_film_fight_back_school',
    title: '逃学威龙',
    titleEn: 'Fight Back to School',
    medium: 'film',
    worldpackAvailableFromYear: 1991
  },
  onceAThief: {
    id: 'work_film_once_a_thief',
    title: '纵横四海',
    titleEn: 'Once a Thief',
    medium: 'film',
    worldpackAvailableFromYear: 1991
  },
  hardBoiled: {
    id: 'work_film_hard_boiled',
    title: '辣手神探',
    titleEn: 'Hard Boiled',
    medium: 'film',
    worldpackAvailableFromYear: 1992
  },
  chungkingExpress: {
    id: 'work_film_chungking_express',
    title: '重庆森林',
    titleEn: 'Chungking Express',
    medium: 'film',
    worldpackAvailableFromYear: 1994
  },
  hesWoman: {
    id: 'work_film_hes_woman',
    title: '金枝玉叶',
    titleEn: "He's a Woman, She's a Man",
    medium: 'film',
    worldpackAvailableFromYear: 1994
  },
  fromBeijingLove: {
    id: 'work_film_from_beijing',
    title: '国产凌凌漆',
    titleEn: 'From Beijing with Love',
    medium: 'film',
    worldpackAvailableFromYear: 1994
  },
  youngDangerous: {
    id: 'work_film_young_dangerous',
    title: '古惑仔之人在江湖',
    titleEn: 'Young and Dangerous',
    medium: 'film',
    worldpackAvailableFromYear: 1996
  },
  comrades: {
    id: 'work_film_comrades',
    title: '甜蜜蜜',
    titleEn: 'Comrades: Almost a Love Story',
    medium: 'film',
    worldpackAvailableFromYear: 1996
  }
} as const satisfies Record<string, ScreenWork>;

const categoryDefaults: Record<
  ScreenCharacterCategory,
  Pick<ScreenCharacterSeedCard, 'sectors' | 'appearanceAnchor' | 'clothingAnchor' | 'capabilityProfile'>
> = {
  police_law: {
    sectors: ['police', 'law', 'case', 'investigation'],
    appearanceAnchor: '神态与体态应符合长期执法、调查或法庭工作的职业习惯，并按角色自身年龄与经历生成。',
    clothingAnchor: '按当时岗位穿警服、便装或法庭职业服装，服饰随场景变化。',
    capabilityProfile: '侦查、观察、行动和制度判断较强，具体六维由当前年龄、职级与经历生成。'
  },
  triad_crime: {
    sectors: ['triad', 'crime', 'nightlife', 'street'],
    appearanceAnchor: '外观体现街面经历、风险意识与个人地位，并按角色自身年龄与经历生成。',
    clothingAnchor: '按身份穿街头便装、夜场服装或讲究西装，避免人人同款黑西装。',
    capabilityProfile: '街面判断、行动、谈判或意志突出，具体六维随其层级与经历生成。'
  },
  business_finance: {
    sectors: ['business', 'finance', 'contract', 'office'],
    appearanceAnchor: '外观体现商界身份、压力与个人控制力，并按角色自身年龄与经历生成。',
    clothingAnchor: '以八九十年代香港商务服装为主，正式程度按场合和财富变化。',
    capabilityProfile: '思考、谈判、资源整合或风险判断突出，具体六维随职位与经历生成。'
  },
  media_entertainment: {
    sectors: ['media', 'entertainment', 'film', 'music'],
    appearanceAnchor: '外观体现传媒或娱乐行业的职业形象，并按角色自身年龄与经历生成。',
    clothingAnchor: '按通告、舞台、片场或私人场景选择有年代感的服装。',
    capabilityProfile: '表达、观察、社交或专业创作能力突出，具体六维随职业经历生成。'
  },
  civilian_relationship: {
    sectors: ['civilian', 'family', 'community', 'workplace'],
    appearanceAnchor: '外观体现其生活阶层、职业与精神状态，并按角色自身年龄与经历生成。',
    clothingAnchor: '使用符合职业、收入和场合的八九十年代香港日常服装。',
    capabilityProfile: '能力分布贴近其职业与人生经历，不因角色知名度自动全能。'
  }
};

const categoryAccessRoutes: Record<ScreenCharacterCategory, string[]> = {
  police_law: ['案件协作或报案', '警署、法庭或律师楼工作关系', '可靠线索牵连'],
  triad_crime: ['街面冲突或夜场关系', '债务、保护或中间人牵线', '案件线索自然指向'],
  business_finance: ['公司、银行或交易关系', '合约、债务或投资纠纷', '职业人脉介绍'],
  media_entertainment: ['片场、电视台或唱片公司工作关系', '采访、通告或合约纠纷', '朋友与行业人脉介绍'],
  civilian_relationship: ['工作、住所或社区关系', '亲友转介', '突发事件或长期生活压力']
};

function identityHooks(name: string, identity: ScreenCharacterSeedCard['currentIdentity']): ScreenCharacterSeedCard['identityHooks'] {
  const identityLabel = identity === 'police' ? '警务或法律岗位' : identity === 'gang_member' ? '街面或社团身份' : '社会身份';
  return {
    police: `只有案件、报案、工作或可靠线索自然涉及${name}时才建立接触；按其${identityLabel}处理，不得因资料入选而默认在场。`,
    civilian: `只有工作、住所、亲友或社会事件自然涉及${name}时才建立接触；按其${identityLabel}处理，不得强行安排偶遇。`,
    gang_member: `只有街面关系、利益、债务、冲突或中间人自然涉及${name}时才建立接触；按其${identityLabel}处理，不得自动写成同一社团成员。`
  };
}

function character(work: ScreenWork, draft: CharacterDraft): ScreenCharacterSeedCard {
  const defaults = categoryDefaults[draft.category];
  const currentIdentity = draft.currentIdentity ?? 'civilian';
  return {
    type: 'ScreenCharacterSeedCard',
    id: draft.id,
    canonicalCharacterId: draft.id,
    displayName: draft.displayName,
    englishName: draft.englishName,
    recognitionAliases: Array.from(new Set(draft.aliases ?? [])),
    sourceWorkId: work.id,
    sourceWorkTitle: work.title,
    sourceWorkTitleEn: work.titleEn,
    medium: work.medium,
    availableYears: { from: work.worldpackAvailableFromYear, to: 1996 },
    category: draft.category,
    sectors: Array.from(new Set([...defaults.sectors, ...(draft.sectors ?? [])])),
    eraTags: [work.title, work.medium === 'film' ? '香港电影角色' : '香港电视角色'],
    usualPlaceIds: [...(draft.usualPlaceIds ?? [])],
    gender: draft.gender,
    ageRange: { ...draft.ageRange },
    currentIdentity,
    publicIdentity: draft.publicIdentity,
    actualIdentitySummary: draft.actualIdentitySummary ?? draft.publicIdentity,
    positionSummary: draft.publicIdentity,
    profileSummary: draft.profileSummary,
    appearanceAnchor: draft.appearanceAnchor ?? defaults.appearanceAnchor,
    clothingAnchor: draft.clothingAnchor ?? defaults.clothingAnchor,
    personality: draft.personality,
    speechStyle: draft.speechStyle,
    motivation: draft.motivation,
    longTermGoal: draft.motivation,
    values: draft.values,
    capabilityProfile: draft.capabilityProfile ?? defaults.capabilityProfile,
    relationshipAnchors: [...(draft.relationshipAnchors ?? [])],
    accessRoutes: Array.from(new Set([...(draft.accessRoutes ?? []), ...categoryAccessRoutes[draft.category]])).slice(0, 6),
    promptHooks: Array.from(new Set(draft.promptHooks ?? [])).slice(0, 4),
    identityHooks: identityHooks(draft.displayName, currentIdentity),
    importance: draft.importance ?? 80,
    sourceConfidence: 'high'
  };
}

const televisionCharacters: ScreenCharacterSeedCard[] = [
  character(works.policeCadet, {
    id: 'screen_tv_police_cadet_cheung_wai_kit',
    displayName: '张伟杰',
    aliases: ['杰佬'],
    gender: 'male',
    ageRange: { min: 20, max: 28 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '由基层训练成长的年轻警员',
    profileSummary: '单亲家庭出身，警校磨炼令他逐渐成熟；工作责任、家庭裂痕与感情选择经常彼此拉扯。',
    personality: '认真、倔强、讲原则，年轻时容易把工作压力带进私人关系。',
    speechStyle: '直接克制，执行任务时利落，面对亲友时常把关心说得生硬。',
    motivation: '证明自己能成为可靠警员，同时不让复杂家庭决定自己的人生。',
    values: '责任、伙伴、公平、靠自己争取尊严。',
    relationshipAnchors: ['谢颖之：青梅竹马与感情牵挂', '倪峰：警校同学与生死好友', '乔志豪：同学、朋友与竞争者'],
    promptHooks: ['一次行动失误令同伴受伤', '家庭秘密与警务调查重叠', '升迁机会要求他牺牲私人生活'],
    importance: 90
  }),
  character(works.policeCadet, {
    id: 'screen_tv_police_cadet_tse_wing_chi',
    displayName: '谢颖之',
    englishName: 'Grace',
    aliases: ['阿之'],
    gender: 'female',
    ageRange: { min: 20, max: 27 },
    category: 'civilian_relationship',
    publicIdentity: '独立工作的年轻职业女性',
    profileSummary: '与张伟杰一同长大，却不愿永远只在他的警察人生旁边等待；温和外表下有清楚的自我要求。',
    personality: '体贴、敏感、有分寸，长期被忽略后会果断保护自己。',
    speechStyle: '语气温和但立场明确，不爱大吵，失望时反而更安静。',
    motivation: '建立不依附任何人的职业与生活，也希望重要的人真正看见她。',
    values: '尊重、互相照顾、个人选择、稳定生活。',
    relationshipAnchors: ['张伟杰：青梅竹马与长期感情', '乔志豪：给予关注的追求者'],
    promptHooks: ['被警务工作一再打断的约定', '职业机会要求离开熟悉社区', '无意听见朋友不愿公开的秘密']
  }),
  character(works.policeCadet, {
    id: 'screen_tv_police_cadet_ngai_fung',
    displayName: '倪峰',
    aliases: ['Fit佬'],
    gender: 'male',
    ageRange: { min: 21, max: 30 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '体能出众的年轻警员',
    actualIdentitySummary: '受伤与离队风险会把他推向危险的灰色工作，但是否越线取决于当前剧情。',
    profileSummary: '警校体能尖子，重朋友也重自尊；一旦职业身份被伤病夺走，极容易把能力投向更危险的道路。',
    personality: '豪爽、好胜、重义气，自尊受损时会封闭和冒险。',
    speechStyle: '爽快带玩笑，真正受伤时少说话，不愿接受怜悯。',
    motivation: '维持作为强者和可靠伙伴的尊严，找到受伤后仍能掌控的人生。',
    values: '兄弟、能力、尊严、说到做到。',
    relationshipAnchors: ['张伟杰：警校好友与行动搭档', '张嘉汶：真心爱慕他的伴侣'],
    promptHooks: ['因公受伤后的职业抉择', '有人利用他的身手招揽危险工作', '朋友必须判断他是否已经越线'],
    importance: 88
  }),
  character(works.policeCadet, {
    id: 'screen_tv_police_cadet_kiu_chi_ho',
    displayName: '乔志豪',
    aliases: ['好姐'],
    gender: 'male',
    ageRange: { min: 20, max: 29 },
    category: 'business_finance',
    publicIdentity: '警校出身、后来进入家族生意的年轻商人',
    profileSummary: '出身优渥却缺乏胆量，被送进警校磨炼；回到商界后常在感情、家族利益与守法底线之间摇摆。',
    personality: '圆滑、怕事、重感情，也会为了保住家人而作出错误选择。',
    speechStyle: '讲究体面，善用轻松话缓和冲突，被逼急时容易语无伦次。',
    motivation: '证明自己不是只靠家族，也想保护给予他安全感的人。',
    values: '家庭、体面、友情、避免正面冲突。',
    relationshipAnchors: ['张伟杰：同学与感情竞争者', '谢颖之：真心追求的对象', '乔创基：必须面对其错误的叔父'],
    promptHooks: ['家族账目迫使他包庇亲人', '旧警校同学查到他的公司', '感情选择与商业利益冲突']
  }),
  character(works.feudBrothers, {
    id: 'screen_tv_feud_fong_kan_cheong',
    displayName: '方谨昌',
    aliases: ['阿昌'],
    gender: 'male',
    ageRange: { min: 28, max: 38 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '由基层奋斗晋升的督察',
    profileSummary: '在中下阶层家庭长大，凭勤奋成为警官；血缘、事业与亲情的冲突会反复考验他对程序和家人的忠诚。',
    personality: '沉稳、坚韧、顾家，遭受不公时仍努力守住底线。',
    speechStyle: '朴实有耐性，办案时追问细节，对家人说话更柔软。',
    motivation: '保护养育自己的家庭，并让权势者也接受法律约束。',
    values: '养育之恩、守法、勤奋、对弱者负责。',
    relationshipAnchors: ['钟伟舜：血缘兄弟与危险对手', '林月明：稳定而重要的伴侣', '宋楚翘：事业与情感上的关键伙伴'],
    promptHooks: ['调查对象与自己有血缘关系', '被权势者设计停职', '家庭成员成为报复目标'],
    importance: 91
  }),
  character(works.feudBrothers, {
    id: 'screen_tv_feud_chung_wai_shun',
    displayName: '钟伟舜',
    gender: 'male',
    ageRange: { min: 26, max: 36 },
    category: 'business_finance',
    publicIdentity: '富商家庭中受器重的年轻继承人',
    actualIdentitySummary: '擅长利用财富、法律与人际弱点排除威胁，真实手段远比公开形象冷酷。',
    profileSummary: '外表斯文、善于经营可信形象，内里把血缘和感情都视为可交换资源。',
    personality: '聪明、虚荣、控制欲强，遇到身份威胁时会迅速升级手段。',
    speechStyle: '礼貌周全，习惯把威胁包装成建议，从不轻易失态。',
    motivation: '保住财富继承与体面身份，抹去任何能揭穿来历的人和证据。',
    values: '地位、控制、结果、只信可利用的关系。',
    relationshipAnchors: ['方谨昌：血缘兄弟与最大威胁', '钟赞：必须维持信任的养父', '方学宁：被他利用感情的人'],
    promptHooks: ['公司证据与身世秘密相连', '用律师和财富反压调查', '安排第三者替自己承担风险'],
    importance: 88
  }),
  character(works.feudBrothers, {
    id: 'screen_tv_feud_lam_yuet_ming',
    displayName: '林月明',
    gender: 'female',
    ageRange: { min: 25, max: 35 },
    category: 'civilian_relationship',
    publicIdentity: '有稳定职业与判断力的都市女性',
    profileSummary: '长期陪伴方谨昌，从不把支持等同于盲从；在婚姻承诺与现实风险之间保持清醒。',
    personality: '理性、温柔、有韧性，面对危机能够独立决定。',
    speechStyle: '平静、实在，善于指出别人回避的问题。',
    motivation: '守住自己与伴侣的正常生活，不让权势和案件吞没一切。',
    values: '诚实、互相承担、家庭安全、个人尊严。',
    relationshipAnchors: ['方谨昌：长期伴侣', '钟伟舜：令她警觉的权势人物'],
    promptHooks: ['婚期被案件一再推迟', '掌握一项不愿交给警方的私人证据', '必须选择留下还是暂时离开']
  }),
  character(works.feudBrothers, {
    id: 'screen_tv_feud_sung_cho_kiu',
    displayName: '宋楚翘',
    aliases: ['楚翘'],
    gender: 'female',
    ageRange: { min: 27, max: 38 },
    category: 'business_finance',
    publicIdentity: '企业管理层女性',
    profileSummary: '见惯商场权力与人情交换，外冷内热；能在危机中给出资源，也会为自己的情感承担代价。',
    personality: '能干、克制、敏锐，越在意越不愿轻易表露。',
    speechStyle: '简洁专业，谈判时不浪费字句，私人场合偶尔露出疲惫。',
    motivation: '保住企业与身边可信的人，同时摆脱家族权力安排。',
    values: '能力、忠诚、选择权、对承诺负责。',
    relationshipAnchors: ['方谨昌：事业伙伴与深厚情感', '宋氏企业：责任与束缚并存的家业'],
    promptHooks: ['董事会利用私人关系施压', '公司内部账目牵出刑案', '她必须公开支持被停职的警官']
  }),
  character(works.lookingBack, {
    id: 'screen_tv_looking_back_ting_yau_kin',
    displayName: '丁有健',
    englishName: 'Alex Ting',
    aliases: ['阿健'],
    gender: 'male',
    ageRange: { min: 25, max: 38 },
    category: 'business_finance',
    publicIdentity: '由大牌档起步的自立商人',
    profileSummary: '从贫困与家庭悲剧中长大，能吃苦、有生意头脑，却对弟弟过度保护，容易把仁厚变成纵容。',
    personality: '善良、坚忍、重亲情，面对至亲时判断会失衡。',
    speechStyle: '朴素真诚，谈生意讲信用，劝家人时常先退让。',
    motivation: '让家人脱离贫困并维持一个完整的家。',
    values: '亲情、勤劳、信用、给人改过机会。',
    relationshipAnchors: ['丁有康：弟弟与最大软肋', '倪楚君：理解他却要求他面对现实的伴侣', '李华：亲人般的旧感情'],
    promptHooks: ['替弟弟承担不应承担的责任', '创业扩张暴露旧日人情债', '善意被人设计成法律风险'],
    importance: 90
  }),
  character(works.lookingBack, {
    id: 'screen_tv_looking_back_ting_yau_hong',
    displayName: '丁有康',
    englishName: 'Ben Ting',
    aliases: ['阿康'],
    gender: 'male',
    ageRange: { min: 22, max: 34 },
    category: 'business_finance',
    publicIdentity: '受过法律教育、善于进入上流圈子的年轻人',
    actualIdentitySummary: '为地位和脱离贫困可以持续欺骗、灭口与嫁祸，悔意只会在后果真正落到自己身上时出现。',
    profileSummary: '聪明体面、极懂得迎合权势；对贫穷有强烈恐惧，把亲情视为可以反复透支的保护网。',
    personality: '自私、机敏、善于伪装，危机中不断用更大的谎言补前一个谎言。',
    speechStyle: '对上谦恭、对下冷淡，受质疑时擅长转移责任和诉苦。',
    motivation: '不惜代价进入有钱有势的阶层，并摆脱所有旧日身份。',
    values: '地位、利益、自保、别人对他的利用价值。',
    relationshipAnchors: ['丁有健：反复利用的兄长', '倪楚君：能看穿他的旁观者', '冯美欣：财富与婚姻的跳板'],
    promptHooks: ['用专业话术掩盖刑事风险', '逼兄长再次替他收拾残局', '旧案证人突然出现'],
    importance: 91
  }),
  character(works.lookingBack, {
    id: 'screen_tv_looking_back_ngai_cho_kwan',
    displayName: '倪楚君',
    englishName: 'Sandy Ngai',
    aliases: ['阿君'],
    gender: 'female',
    ageRange: { min: 25, max: 38 },
    category: 'business_finance',
    publicIdentity: '家族企业继承人',
    profileSummary: '出身富裕却不轻视草根生活，重感情也重原则；能够帮助丁有健，但不会无限容忍他纵容家人。',
    personality: '明快、果断、有同理心，触及底线时立场坚定。',
    speechStyle: '直率清楚，愿意倾听，但不会用漂亮话回避责任。',
    motivation: '建立不被家族与错误亲情绑架的关系和事业。',
    values: '坦诚、责任、独立判断、保护无辜。',
    relationshipAnchors: ['丁有健：相爱但价值选择不断受考验', '丁有康：始终保持警惕的小叔', '倪氏集团：资源与家族责任'],
    promptHooks: ['董事会与亲情发生冲突', '要求伴侣在家人与正义间表态', '用企业资源保护受害者']
  }),
  character(works.lookingBack, {
    id: 'screen_tv_looking_back_lee_wah',
    displayName: '李华',
    englishName: 'Connie Lee',
    gender: 'female',
    ageRange: { min: 22, max: 34 },
    category: 'civilian_relationship',
    publicIdentity: '重视家庭与感情承诺的年轻女性',
    profileSummary: '在亲族与爱情之间反复受伤，外柔内刚；她需要的是明确选择，而不是永远被当成可以等待的人。',
    personality: '温柔、敏感、执着，受伤后容易把痛苦留给自己。',
    speechStyle: '含蓄克制，习惯先照顾别人情绪，真正决绝时不再解释。',
    motivation: '得到稳定、诚实且不被牺牲的亲密关系。',
    values: '忠诚、家庭、被尊重、承诺必须兑现。',
    relationshipAnchors: ['丁有健：亲人般的旧爱', '丁有康：曾经误判其为可以信任的人'],
    promptHooks: ['家族事故令她掌握关键证词', '一场婚约被旧案打断', '在离开香港前必须作出最后选择']
  }),
  character(works.goodAndEvil, {
    id: 'screen_tv_good_evil_chai_ho_nam',
    displayName: '齐浩男',
    aliases: ['浩少', '浩男', '蒋子聪'],
    gender: 'male',
    ageRange: { min: 26, max: 38 },
    category: 'business_finance',
    publicIdentity: '齐氏集团执行经理',
    actualIdentitySummary: '养父与生父分处犯罪嫌疑和警务调查两端，他既熟悉商界灰色手段，也保留选择善恶的能力。',
    profileSummary: '在富裕家族长大，冷静能干，身世与养父罪行令他长期处于忠诚和良知冲突。',
    personality: '深沉、骄傲、重情，表面冷硬但不愿伤害无辜。',
    speechStyle: '低调简练，极少解释自己，情绪越强烈语气越平静。',
    motivation: '保护在意的人，并证明自己不必复制养父的道路。',
    values: '选择胜过出身、忠诚、尊严、承担后果。',
    relationshipAnchors: ['石伊明：让他愿意面对真实自己的伴侣', '齐乔正：养父、恩人也是道德枷锁', '蒋定邦：生父与追查齐家的警官'],
    promptHooks: ['养父要求他处理一项不能回头的任务', '警方用身世换取合作', '商界行动可能伤害石伊明'],
    importance: 92
  }),
  character(works.goodAndEvil, {
    id: 'screen_tv_good_evil_shek_yi_ming',
    displayName: '石伊明',
    gender: 'female',
    ageRange: { min: 24, max: 35 },
    category: 'media_entertainment',
    publicIdentity: '调查与社会新闻记者',
    profileSummary: '在海外成长后回港当记者，独立、敏锐，不会因爱情放弃追问事实。',
    personality: '爽朗、正直、好奇，有同情心但不轻易被感情操控。',
    speechStyle: '提问尖锐而有礼，私下坦率，发现谎言时会直接追根究底。',
    motivation: '查明权势背后的事实，同时保护家人和自己的判断。',
    values: '真相、独立、职业伦理、感情中的诚实。',
    relationshipAnchors: ['齐浩男：相爱却被秘密反复考验', '石家豪：同父异母的警察弟弟', '齐乔正：新闻调查中的危险权势人物'],
    promptHooks: ['记者资料与警方证据不一致', '爱人的家族阻止报道', '采访对象在见面前遇袭'],
    importance: 88
  }),
  character(works.goodAndEvil, {
    id: 'screen_tv_good_evil_tseung_ting_bong',
    displayName: '蒋定邦',
    aliases: ['乒乓邦'],
    gender: 'male',
    ageRange: { min: 42, max: 58 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '经验丰富的总督察',
    profileSummary: '长期追查齐氏企业，办案意志强，私人关系却与调查目标纠缠；必须在父亲身份和警官职责间保持清醒。',
    personality: '强硬、耐心、疑心重，对同僚讲规矩，对家人有迟来的愧疚。',
    speechStyle: '老练、带审讯节奏，常用短问题逼对方自己露出漏洞。',
    motivation: '完成多年调查，弥补过去对家庭造成的伤害。',
    values: '证据、警察职责、迟到也必须承担的亲情责任。',
    relationshipAnchors: ['齐浩男：亲生儿子与调查目标家族成员', '齐乔正：多年对手', '石家豪：可依赖的下属'],
    promptHooks: ['关键证据来自自己的儿子', '上级因政治压力要求收案', '旧日感情被对手利用'],
    importance: 89
  }),
  character(works.goodAndEvil, {
    id: 'screen_tv_good_evil_chai_kiu_ching',
    displayName: '齐乔正',
    gender: 'male',
    ageRange: { min: 48, max: 65 },
    category: 'business_finance',
    publicIdentity: '齐氏集团主席',
    actualIdentitySummary: '以企业与慈父形象掩护暴力、灭口和长期非法利益。',
    profileSummary: '白手起家的集团掌权者，能给予家人真切关怀，也会毫不犹豫地消灭威胁。',
    personality: '威严、精明、占有欲强，把恩情和服从混为一谈。',
    speechStyle: '沉稳有礼，习惯以长辈口吻下命令，威胁从不提高音量。',
    motivation: '保住齐氏集团、家庭秩序与自己不受追究的权力。',
    values: '家族控制、利益、恩威并施、秘密不能外泄。',
    relationshipAnchors: ['齐浩男：最器重的养子', '蒋定邦：持续追查他的警官', '简慧心：家庭与旧情的核心'],
    promptHooks: ['公司高层准备向警方合作', '用家庭恩情要求养子越线', '旧案证物重新出现'],
    importance: 90
  }),
  character(works.grayWeb, {
    id: 'screen_tv_gray_web_ching_ho',
    displayName: '程浩',
    gender: 'male',
    ageRange: { min: 27, max: 39 },
    category: 'triad_crime',
    publicIdentity: '往返东南亚航线、努力与家人重建生活的海员',
    actualIdentitySummary: '在亲情受挫和经济压力下被卷入毒品运输，越想补偿家人越被犯罪网络控制。',
    profileSummary: '屋邨出身，少年时替朋友顶罪；重情、能吃苦，却习惯独自承担，失去退路后容易用冒险解决问题。',
    personality: '沉默、义气、执拗，面对背叛会从克制转为极端。',
    speechStyle: '话少直接，不爱辩解；承诺时很重，绝望时语气反而平静。',
    motivation: '夺回与家人的关系，并让自己不再被过去和贫穷摆布。',
    values: '情义、家庭、偿还、被逼到绝境时的生存。',
    relationshipAnchors: ['姚家诚：一同长大的兄弟', '杨志标：把他拖入毒网的旧友', '王君妍：仍愿意相信他的女性'],
    promptHooks: ['一批走私货被临时换成毒品', '旧友要求他为少年往事再顶一次罪', '家人被债主当作筹码'],
    importance: 88
  }),
  character(works.grayWeb, {
    id: 'screen_tv_gray_web_yiu_ka_shing',
    displayName: '姚家诚',
    gender: 'male',
    ageRange: { min: 27, max: 39 },
    category: 'business_finance',
    publicIdentity: '小型贸易公司负责人',
    profileSummary: '从屋邨少年重新站稳脚跟，务实、顾家，愿意帮旧友，却不愿自己的事业和婚姻被犯罪拖垮。',
    personality: '稳健、念旧、有原则，压力大时会显得过分现实。',
    speechStyle: '说话有生意人的分寸，对旧友仍保留熟稔和劝告口吻。',
    motivation: '守住正当生意、家庭和自己来之不易的体面。',
    values: '合法经营、家人安全、旧情有界限、承担现实后果。',
    relationshipAnchors: ['程浩：无法轻易割舍的兄弟', '杨志标：必须保持距离的旧友', '王君妍：伴侣与道德提醒'],
    promptHooks: ['贸易公司现金流突然断裂', '警方要求提供旧友的货运记录', '一笔救命订单来源可疑']
  }),
  character(works.grayWeb, {
    id: 'screen_tv_gray_web_yeung_chi_biu',
    displayName: '杨志标',
    gender: 'male',
    ageRange: { min: 27, max: 40 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '经营灰色货运与夜场生意的街面人物',
    actualIdentitySummary: '把旧友和航线当作毒品网络的运输节点，遇到风险会先牺牲别人。',
    profileSummary: '从少年时期便习惯走捷径，熟悉货路、人情和地下交易；擅长把利用包装成兄弟互助。',
    personality: '圆滑、贪婪、记仇，表面热络，实际不断计算退路。',
    speechStyle: '满口兄弟情义与发财机会，涉及责任时迅速含糊或反咬。',
    motivation: '扩大毒品与走私网络，同时让风险永远由别人承担。',
    values: '金钱、控制、可替代的盟友、绝不自己坐牢。',
    relationshipAnchors: ['程浩：可用的运输与替罪人', '姚家诚：可洗白资金的生意渠道'],
    promptHooks: ['用旧情逼朋友接最后一票货', '货仓里少了一批货', '准备向警方推出替罪人'],
    importance: 84
  }),
  character(works.grayWeb, {
    id: 'screen_tv_gray_web_wong_kwan_yin',
    displayName: '王君妍',
    gender: 'female',
    ageRange: { min: 24, max: 35 },
    category: 'civilian_relationship',
    publicIdentity: '由补习教师转入跨国集团行政工作的年轻女性',
    profileSummary: '家庭稳定、观察细致，愿意理解出身复杂的人，但不会把同情等同于纵容犯罪。',
    personality: '温和、理智、有耐性，真正受骗后会明确抽身。',
    speechStyle: '平静而具体，常追问事实和时间，不用激烈语言逼人。',
    motivation: '维持独立生活，并帮助重要的人在越界前回头。',
    values: '诚实、安全、教育与自我选择。',
    relationshipAnchors: ['姚家诚：可靠却承受旧友压力的伴侣', '程浩：令她同情又警惕的人'],
    promptHooks: ['无意发现公司货运单异常', '孩子的补习家庭与毒网相连', '必须决定是否向警方交出证据']
  }),
  character(works.greedOfMan, {
    id: 'screen_tv_greed_fong_chin_bok',
    displayName: '方展博',
    aliases: ['展博'],
    gender: 'male',
    ageRange: { min: 24, max: 36 },
    category: 'business_finance',
    publicIdentity: '由失意青年成长起来的股票投资者',
    profileSummary: '家破人亡后长期逃避，凭数学直觉、市场触觉和师友帮助重返股市；复仇与保护家人同时驱动他。',
    personality: '聪明、敏感、倔强，平时散漫，真正投入时近乎偏执。',
    speechStyle: '不拘小节，谈市场时思路突然清晰；触及家仇会直接而尖锐。',
    motivation: '在股市击败丁家，重建方家尊严并保护仍在身边的人。',
    values: '家人、兑现承诺、以规则击败强权、不能再逃。',
    relationshipAnchors: ['丁蟹：毁掉方家的仇人', '阮梅：令他重新珍惜生活的人', '陈滔滔：亦师亦友的市场盟友', '罗慧玲：抚养方家子女的长辈'],
    sectors: ['stock_exchange'],
    promptHooks: ['恒生指数异常波动', '丁家资金来源出现破绽', '复仇交易与亲人安全发生冲突'],
    importance: 96
  }),
  character(works.greedOfMan, {
    id: 'screen_tv_greed_ting_hai',
    displayName: '丁蟹',
    aliases: ['蟹哥'],
    gender: 'male',
    ageRange: { min: 42, max: 58 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '以拳头和旧江湖声望维持影响力的中年人',
    actualIdentitySummary: '将暴力、占有和自我开脱解释成正义，坚信所有灾难都是别人逼他造成。',
    profileSummary: '力气过人、情绪极端，拥有一套只对自己有利的道德逻辑；越被反驳越确信自己受了委屈。',
    personality: '自恋、偏执、暴烈、强烈受害者心态，偶尔的温情也带控制欲。',
    speechStyle: '滔滔不绝地讲道理，反复强调自己问心无愧，随时由劝说转为暴力。',
    motivation: '证明自己永远正确，并让丁家在社会与股市取得压倒性地位。',
    values: '自我正当化、儿子服从、面子、力量就是公道。',
    relationshipAnchors: ['方展博：必须压服的方家后人', '丁孝蟹：最能替他收拾残局的长子', '罗慧玲：被他视为属于自己的旧情人'],
    sectors: ['stock_exchange'],
    promptHooks: ['闯入调解现场坚持自己才是受害者', '命令儿子用股市证明丁家天命', '旧案证人要求他公开道歉'],
    importance: 97
  }),
  character(works.greedOfMan, {
    id: 'screen_tv_greed_ting_hau_hai',
    displayName: '丁孝蟹',
    aliases: ['孝蟹'],
    gender: 'male',
    ageRange: { min: 27, max: 39 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '忠青社话事层核心人物',
    actualIdentitySummary: '外表有礼克制，实际能为父亲和家族执行绑架、威胁与灭口。',
    profileSummary: '丁家长子，沉稳精明，兼具江湖手腕与商业意识；孝道成为他越过底线的永久理由。',
    personality: '冷静、重家族、控制力强，在爱情与父命间仍优先父命。',
    speechStyle: '礼貌简洁，很少失态；真正的威胁通常只说一次。',
    motivation: '保护父亲和弟弟，扩大忠青社与丁家在股市的力量。',
    values: '家族优先、忠孝、组织纪律、对外绝不示弱。',
    relationshipAnchors: ['丁蟹：无法违逆的父亲', '方婷：真心爱过却被家仇撕裂的人', '方展博：家族必须清除的对手'],
    sectors: ['stock_exchange'],
    promptHooks: ['父亲要求他执行一项失控命令', '社团利益与丁家复仇不再一致', '旧爱掌握能毁掉家族的证据'],
    importance: 93
  }),
  character(works.greedOfMan, {
    id: 'screen_tv_greed_yuen_mui',
    displayName: '阮梅',
    aliases: ['悭妹'],
    gender: 'female',
    ageRange: { min: 22, max: 32 },
    category: 'civilian_relationship',
    publicIdentity: '精打细算、独立生活的屋邨年轻女性',
    profileSummary: '因健康和经济不安而极度节俭，嘴硬心软；她珍惜每一分钱，也比许多人更懂得生活真正的代价。',
    personality: '谨慎、善良、固执、怕成为别人负担。',
    speechStyle: '算得清每笔开支，抱怨实际却常默默帮助别人。',
    motivation: '在有限条件下保持尊严，并和方展博拥有不被仇恨吞没的生活。',
    values: '节制、真心、普通日子的安全、不给别人添麻烦。',
    relationshipAnchors: ['方展博：由邻居发展成最重要的伴侣', '罗慧玲：像家人般照顾她的长辈'],
    promptHooks: ['医药费与生活费突然冲突', '发现方展博准备孤注一掷', '一份稳定工作要求她离开熟悉社区'],
    importance: 88
  }),
  character(works.greedOfMan, {
    id: 'screen_tv_greed_chan_to_to',
    displayName: '陈滔滔',
    aliases: ['Totto'],
    gender: 'male',
    ageRange: { min: 30, max: 43 },
    category: 'business_finance',
    publicIdentity: '从海外回港操作资本市场的基金经理',
    profileSummary: '金融训练扎实、作风凌厉，把交易当作精密战争；对背叛敏感，但仍愿意把真正的本事教给可信的人。',
    personality: '自信、果断、好胜，感情受挫时容易把情绪带入交易。',
    speechStyle: '快速、专业、带讽刺，习惯用价格和仓位说明判断。',
    motivation: '在香港资本市场证明实力，并夺回被家族关系伤害的尊严。',
    values: '专业、信息优势、信用、失败必须找到原因。',
    relationshipAnchors: ['方展博：值得培养的市场搭档', '龙纪文：复杂的亲密关系', '丁家：高风险市场对手'],
    sectors: ['stock_exchange'],
    promptHooks: ['发现大户联手操纵股价', '融资渠道在收市前被切断', '盟友要求他为私人恩怨改变仓位'],
    importance: 90
  }),
  character(works.greedOfMan, {
    id: 'screen_tv_greed_law_wai_ling',
    displayName: '罗慧玲',
    aliases: ['玲姐'],
    gender: 'female',
    ageRange: { min: 38, max: 52 },
    category: 'civilian_relationship',
    publicIdentity: '独力照顾方家子女的巴士职员',
    profileSummary: '经历家庭惨变仍撑住生活，以普通收入和极强责任感守护方家；面对丁蟹时恐惧与勇气长期并存。',
    personality: '坚韧、温柔、警觉，情绪创伤深却不轻易放弃家人。',
    speechStyle: '对家人直接务实，面对威胁会颤抖但仍把底线说清楚。',
    motivation: '让方家孩子安全长大，并终止丁蟹对她和家人的控制。',
    values: '照顾、家庭、普通人的尊严、拒绝暴力占有。',
    relationshipAnchors: ['方展博：她抚养成人的方家长子', '丁蟹：长期恐惧的施暴者', '阮梅：视作家人的年轻女性'],
    promptHooks: ['旧施暴者再次出现在住所外', '家中经济压力迫使她多做一份工', '她掌握一段旧案关键记忆'],
    importance: 91
  }),
  character(works.filesOfJustice, {
    id: 'screen_tv_justice_yu_choi_chun',
    displayName: '余在春',
    aliases: ['余大状'],
    gender: 'male',
    ageRange: { min: 29, max: 42 },
    category: 'police_law',
    publicIdentity: '刑事检控官',
    profileSummary: '专业能力扎实，法庭上反应快，私生活却常被感情和朋友关系搅乱；愿意相信程序，也懂程序之外的人情。',
    personality: '机灵、幽默、重情，面对原则问题会收起玩笑。',
    speechStyle: '日常爱打趣，讨论案情时条理清楚，交叉盘问善于抓住措辞漏洞。',
    motivation: '在证据允许的范围内追求公正，并保护身边人的职业与感情边界。',
    values: '程序正义、朋友、专业判断、感情不能替代证据。',
    relationshipAnchors: ['丁柔：工作上互相信任、感情上反复拉扯的上司', '江承宙：法庭上的对手与朋友', '方家琪：共同朋友圈成员'],
    promptHooks: ['关键证人的口供在开庭前改变', '朋友成为案件嫌疑人', '上级要求用较轻控罪换取合作'],
    importance: 88
  }),
  character(works.filesOfJustice, {
    id: 'screen_tv_justice_ting_yau',
    displayName: '丁柔',
    gender: 'female',
    ageRange: { min: 30, max: 43 },
    category: 'police_law',
    publicIdentity: '高级刑事检控官',
    profileSummary: '独立、严谨，习惯在男性主导的法律环境里靠专业赢得尊重；感情会动摇她，却不会轻易改变案件判断。',
    personality: '理性、自律、敏锐，外冷内热，对失信尤其难以原谅。',
    speechStyle: '措辞精确，会议中直接指出证据缺口，私下较克制。',
    motivation: '维持检控独立与职业信誉，也寻找不必牺牲自我的亲密关系。',
    values: '证据、职业操守、平等、清楚的承诺。',
    relationshipAnchors: ['余在春：倚重的下属与复杂感情对象', '江承宙：熟悉的法律界朋友'],
    promptHooks: ['警方证据链存在程序瑕疵', '传媒质疑不起诉决定', '私人关系被辩方用来申请回避'],
    importance: 89
  }),
  character(works.filesOfJustice, {
    id: 'screen_tv_justice_kong_shing_chau',
    displayName: '江承宙',
    aliases: ['Michael Kong'],
    gender: 'male',
    ageRange: { min: 29, max: 43 },
    category: 'police_law',
    publicIdentity: '刑事辩护律师',
    profileSummary: '法庭策略灵活，重视委托人权利，也在朋友和案件冲突时承受压力；他的专业不是替罪行背书。',
    personality: '冷静、聪明、讲义气，竞争心强但有职业底线。',
    speechStyle: '礼貌而有压迫感，习惯把复杂问题拆成能让证人回答的短句。',
    motivation: '成为可靠的刑事律师，在胜诉与良知之间守住可解释的界线。',
    values: '辩护权、保密、专业尊严、朋友之间不干预案件。',
    relationshipAnchors: ['余在春：庭上对手、庭下朋友', '丁柔：彼此尊重的检控官', '方家琪：朋友圈中的亲密关系'],
    promptHooks: ['委托人承认了未被控告的罪行', '警方搜证手续可能违法', '朋友要求他泄露辩护策略']
  }),
  character(works.filesOfJustice, {
    id: 'screen_tv_justice_fong_ka_kei',
    displayName: '方家琪',
    aliases: ['Josephine Fong', 'Jo'],
    gender: 'female',
    ageRange: { min: 23, max: 34 },
    category: 'police_law',
    publicIdentity: '年轻事务律师',
    profileSummary: '处于法律事业起步期，聪敏、独立，既重视朋友也在学习如何不让感情决定职业选择。',
    personality: '活泼、好胜、有正义感，受到轻视时会更拼命证明自己。',
    speechStyle: '语速快、反应直接，和熟人说话带玩笑，处理文件时很认真。',
    motivation: '建立自己的专业位置，而不是只被视作朋友圈里的年轻女孩。',
    values: '成长、独立、友情、案主权益。',
    relationshipAnchors: ['江承宙：工作与感情都存在张力的前辈', '周志辉：愿意耐心支持她的律师'],
    promptHooks: ['第一次独立负责高风险委托', '好友的案件令她必须回避', '律师楼合伙人要求她隐瞒错误']
  }),
  character(works.filesOfJustice, {
    id: 'screen_tv_justice_chow_chi_fai',
    displayName: '周志辉',
    aliases: ['Raymond Chow'],
    gender: 'male',
    ageRange: { min: 26, max: 38 },
    category: 'police_law',
    publicIdentity: '稳健细致的事务律师',
    profileSummary: '不以锋芒取胜，重视准备、承诺与长期信任；在感情中容易迟疑，却不会拿职业当筹码。',
    personality: '温和、可靠、谨慎，面对竞争偶尔缺乏自信。',
    speechStyle: '礼貌耐心，习惯先确认事实再给意见，很少贸然承诺。',
    motivation: '以稳定专业建立事业，也学会在重要关系中主动表达。',
    values: '可靠、程序、长期关系、宁可慢也不误导。',
    relationshipAnchors: ['方家琪：在工作与感情中都关心的同伴', '江承宙：前辈与潜在竞争者'],
    promptHooks: ['一份关键文件在递交期限前失踪', '客户要求他绕过程序', '感情关系可能造成利益冲突']
  }),
  character(works.silverTycoon, {
    id: 'screen_tv_silver_tuen_siu_cheung',
    displayName: '段绍祥',
    gender: 'male',
    ageRange: { min: 30, max: 45 },
    category: 'media_entertainment',
    publicIdentity: '由影院放映员崛起的电影业商人',
    actualIdentitySummary: '以复仇为核心扩张电影事业，善于操纵感情、舆论与资本，逐渐把所有人都当作棋子。',
    profileSummary: '早年遭侵吞家产和夺爱，能吃苦、有商业眼光；成功后仍无法放下屈辱，复仇不断吞噬原有情义。',
    personality: '精明、隐忍、占有欲强，受挫时会精确而残酷地反击。',
    speechStyle: '平静有礼，擅长以合作和报恩包装控制；真正动怒时只讲结果。',
    motivation: '建立自己的电影王国，并让宋家为昔日掠夺付出代价。',
    values: '掌控、复仇、事业胜利、不能再被夺走任何人或东西。',
    relationshipAnchors: ['白羚：事业伙伴、伴侣与占有对象', '宋仕元：朋友、情敌与宋家异类', '颜如玉：被他利用的演员'],
    promptHooks: ['收购院线需要一笔来历复杂的资金', '旧仇人试图操纵旗下明星', '公司内部有人把复仇计划交给记者'],
    importance: 92
  }),
  character(works.silverTycoon, {
    id: 'screen_tv_silver_pak_ling',
    displayName: '白羚',
    gender: 'female',
    ageRange: { min: 24, max: 37 },
    category: 'media_entertainment',
    publicIdentity: '由明星成长为电影公司核心人物的女演员',
    profileSummary: '在电影圈摸爬滚打，重情也有事业判断；她能陪伴一个人度过低谷，却不接受以爱为名的控制。',
    personality: '爽朗、坚韧、有同理心，面对情感勒索会逐渐清醒。',
    speechStyle: '直率温暖，谈工作很实际，真正失望时不再争辩。',
    motivation: '拥有不被男人的仇恨和占有支配的事业与感情。',
    values: '真心、职业尊严、选择自由、不能伤害无辜。',
    relationshipAnchors: ['段绍祥：共同打拼却被复仇改变的伴侣', '宋仕元：在价值选择上更能理解她的人', '颜如玉：同业与可互相提醒的女性'],
    promptHooks: ['片约要求她公开支持一次恶意收购', '发现伴侣利用自己离间对手', '一段私下谈话被小报掌握'],
    importance: 88
  }),
  character(works.silverTycoon, {
    id: 'screen_tv_silver_sung_shi_yuen',
    displayName: '宋仕元',
    gender: 'male',
    ageRange: { min: 27, max: 40 },
    category: 'media_entertainment',
    publicIdentity: '与家族决裂、坚持电影理想的制作人',
    profileSummary: '出身富裕却反感父亲掠夺式作风，重朋友、重作品；他的理想主义并不幼稚，但容易低估家族仇怨的破坏力。',
    personality: '真诚、浪漫、倔强，愿为原则放弃资源。',
    speechStyle: '坦率热情，谈电影时充满想法，面对父亲则变得强硬。',
    motivation: '拍出自己相信的电影，并证明不依赖宋家权力也能立足。',
    values: '创作、朋友、真爱、拒绝用权力占有别人。',
    relationshipAnchors: ['段绍祥：从朋友变成因家仇和爱情撕裂的对手', '白羚：彼此理解却时机错乱的爱人', '宋学礼：必须摆脱的父亲权力'],
    promptHooks: ['拍摄资金被家族暗中切断', '朋友要求他在爱情和事业间退让', '一部电影意外揭开旧案'],
    importance: 87
  }),
  character(works.instinct, {
    id: 'screen_tv_instinct_wong_tin',
    displayName: '黄天',
    aliases: ['天哥'],
    gender: 'male',
    ageRange: { min: 48, max: 63 },
    category: 'business_finance',
    publicIdentity: '中天集团主席',
    profileSummary: '从商多年，洞察人心与资本运作，愿意提携有原则的年轻人；真正的强项是看清局势后仍能等待。',
    personality: '沉着、宽厚、城府深，面对背叛不急于表态。',
    speechStyle: '语速从容，常以旧事和比喻点到即止，让对方自己作选择。',
    motivation: '守住企业信誉，培养值得信任的接班力量，并偿还旧日人情。',
    values: '信誉、识人、长期利益、给人改过机会但不纵容。',
    relationshipAnchors: ['包文龙：欣赏并提携的年轻人', '潘朗清：曾给予机会却逐渐看清的人', '潘仲：多年的朋友'],
    sectors: ['stock_exchange', 'insurance'],
    promptHooks: ['集团遭遇恶意挖角与沽空', '旧友的儿子涉嫌内部舞弊', '他必须决定是否公开一份致命证据'],
    importance: 92
  }),
  character(works.instinct, {
    id: 'screen_tv_instinct_pao_man_lung',
    displayName: '包文龙',
    aliases: ['小龙'],
    gender: 'male',
    ageRange: { min: 27, max: 39 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '商业罪案调查科督察',
    profileSummary: '屋邨家庭长子，正直、行动快，对商业犯罪有敏锐判断；家庭责任和对朋友的信任会令他承担额外风险。',
    personality: '坦率、勇敢、重情，容易为了保护人越过职业分寸。',
    speechStyle: '警务场景简洁直接，和家人朋友说话较热烈，有时先行动后解释。',
    motivation: '查清商业罪案，也让家人和朋友不被权势利用。',
    values: '清白、责任、朋友可以信但证据必须查。',
    relationshipAnchors: ['黄天：忘年知交与事业导师', '潘朗清：一同长大的兄弟、后来最难面对的对手', '林贞烈：令他坚持生活底线的伴侣'],
    sectors: ['commercial_crime', 'stock_exchange'],
    promptHooks: ['调查对象成为愿意合作的企业家', '朋友可能利用他的警务身份', '家人卷入商业诈骗'],
    importance: 90
  }),
  character(works.instinct, {
    id: 'screen_tv_instinct_poon_long_ching',
    displayName: '潘朗清',
    aliases: ['朗清'],
    gender: 'male',
    ageRange: { min: 26, max: 38 },
    category: 'business_finance',
    publicIdentity: '由保险业务进入中天集团的年轻经理',
    actualIdentitySummary: '强烈羞耻感与向上欲令他不断利用亲友、伪造交易并消灭证据。',
    profileSummary: '从小寄住包家，对贫穷和父亲坐牢深感羞耻；聪明、肯拼，却把成功误解为必须压过所有帮助过他的人。',
    personality: '自卑、野心勃勃、善于伪装，得到机会后迅速把恩情转化为筹码。',
    speechStyle: '面对上位者谦恭有规划，面对亲近者会用旧情和委屈施压。',
    motivation: '进入香港商界核心，切断贫穷出身的痕迹并让所有人承认他的价值。',
    values: '地位、体面、结果、没有利用价值的关系可以舍弃。',
    relationshipAnchors: ['包文龙：最熟悉他、也最可能揭穿他的旧友', '黄天：崇拜并企图取代的企业家', '潘仲：被他视作耻辱又可利用的父亲'],
    sectors: ['insurance', 'stock_exchange'],
    promptHooks: ['亏损迫使他伪造客户签名', '父亲发现一份犯罪文件', '旧友拒绝替他承担责任'],
    importance: 90
  }),
  character(works.instinct, {
    id: 'screen_tv_instinct_lam_ching_lit',
    displayName: '林贞烈',
    aliases: ['阿烈'],
    gender: 'female',
    ageRange: { min: 24, max: 35 },
    category: 'civilian_relationship',
    publicIdentity: '在普通工作与家庭关系中坚持自立的年轻女性',
    profileSummary: '外表活泼、会讲善意小谎，真正面对危险和承诺时异常坚定；不因伴侣落难而逃避。',
    personality: '善良、开朗、勇敢，感情上坦率并有牺牲精神。',
    speechStyle: '轻快、带玩笑，安慰别人时不说空话，遇到不公会直接反驳。',
    motivation: '和包文龙建立真实稳定的生活，并保护包家不被阴谋拆散。',
    values: '真心、患难相守、家庭温度、勇敢面对结果。',
    relationshipAnchors: ['包文龙：愿共同承担低谷的伴侣', '潘朗清：由熟人变成必须警惕的人', '黄天：像长辈般信任她的人'],
    promptHooks: ['探访时无意听见交易秘密', '伴侣被诬告后她寻找证人', '家中出现来历不明的文件']
  }),
  character(works.detectiveFiles, {
    id: 'screen_tv_detective_cheung_tai_yung',
    displayName: '张大勇',
    aliases: ['勇Sir'],
    gender: 'male',
    ageRange: { min: 28, max: 40 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '重案组督察',
    profileSummary: '凭观察、耐性和团队协作破案，工作上沉着，感情上却常因不善表达造成误会。',
    personality: '正直、细心、坚持，面对亲近者牵涉案件也会先查事实。',
    speechStyle: '询问循序渐进，语气不高却会反复核对矛盾；私下略显笨拙。',
    motivation: '把复杂案件查到证据闭合，并让重要的人理解警务责任。',
    values: '事实、团队、受害者、不能用感情替嫌疑人开脱。',
    relationshipAnchors: ['高婕：记者、线索伙伴与感情对象', '李忠义：互相信任的警队搭档', '容金枝：旧有感情与团队关系的纠葛'],
    promptHooks: ['记者抢先掌握凶案线索', '旧情人出现在证人名单', '同组警员的判断与证据冲突'],
    importance: 91
  }),
  character(works.detectiveFiles, {
    id: 'screen_tv_detective_ko_chit',
    displayName: '高婕',
    aliases: ['Jessie Ko'],
    gender: 'female',
    ageRange: { min: 25, max: 37 },
    category: 'media_entertainment',
    publicIdentity: '社会新闻记者',
    profileSummary: '调查欲强、胆子大，能从人情和细节发现警方忽略的线索；职业竞争与保护消息源常令她和警察发生摩擦。',
    personality: '聪敏、好奇、倔强、有正义感，不喜欢被以安全为由排除。',
    speechStyle: '问题快而具体，常从对方回避处追问；私下坦率有幽默感。',
    motivation: '查清值得公众知道的事实，同时证明记者不是警方附属。',
    values: '真相、消息源、独立调查、无辜者不应被舆论定罪。',
    relationshipAnchors: ['张大勇：互相帮助也互相限制的警察', '李忠义：熟悉的重案组成员'],
    promptHooks: ['收到匿名录音带', '报社要求抢发尚未核实的嫌疑人姓名', '消息源在约见前失踪'],
    importance: 89
  }),
  character(works.detectiveFiles, {
    id: 'screen_tv_detective_lee_chung_yee',
    displayName: '李忠义',
    aliases: ['忠义'],
    gender: 'male',
    ageRange: { min: 25, max: 37 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '重案组探员',
    profileSummary: '行动可靠、重朋友，能在张大勇专注推理时补足街面接触与团队照应；感情问题偶尔影响判断。',
    personality: '随和、忠诚、务实，受刺激时会冲动。',
    speechStyle: '口语化、反应快，和搭档交流直接，审问时更像从日常谈话切入。',
    motivation: '做好警察、保护搭档，也让私人生活不再被案件牵着走。',
    values: '兄弟、行动责任、保护证人、承认错误。',
    relationshipAnchors: ['张大勇：最信任的搭档', '容金枝：复杂而反复的感情对象', '雷肖凤：警队同僚'],
    promptHooks: ['线人只肯私下与他交易', '感情对象被列入调查范围', '追捕行动与上级命令冲突']
  }),
  character(works.detectiveFiles, {
    id: 'screen_tv_detective_yung_kam_chi',
    displayName: '容金枝',
    aliases: ['Gigi Yung'],
    gender: 'female',
    ageRange: { min: 25, max: 37 },
    category: 'civilian_relationship',
    publicIdentity: '与警队朋友圈关系密切的都市女性',
    profileSummary: '重视生活条件和情感安全，选择有时显得现实，却不是没有真心；她不愿永远被过去的关系定义。',
    personality: '精明、敏感、爱面子，面对真正危险时仍会保护身边人。',
    speechStyle: '生活化、直率，争执时容易翻旧账，冷静后愿意说实话。',
    motivation: '得到稳定关系与被尊重的生活，不再夹在旧爱和新感情之间。',
    values: '安全、体面、感情确认、生活必须有选择。',
    relationshipAnchors: ['张大勇：无法完全切断的旧关系', '李忠义：真心与现实反复拉扯的伴侣'],
    promptHooks: ['背囊被调换后卷入命案', '旧关系令她成为舆论焦点', '她记起一处被忽略的不在场细节']
  }),
  character(works.detectiveFiles, {
    id: 'screen_tv_detective_lui_siu_fung',
    displayName: '雷肖凤',
    aliases: ['雷警司'],
    gender: 'female',
    ageRange: { min: 34, max: 48 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '重案组管理层警官',
    profileSummary: '经验与纪律并重，能给年轻探员空间，也会在风险失控前收紧行动；熟悉案件压力对团队关系的影响。',
    personality: '冷静、干练、护短但不纵容，对外部干预保持警惕。',
    speechStyle: '指令简短、问题准确，复盘时要求每个人说明依据。',
    motivation: '让重案组依法有效办案，并避免团队因私人关系崩裂。',
    values: '纪律、证据链、人员安全、上级压力不能改写事实。',
    relationshipAnchors: ['张大勇：倚重但需要约束的下属', '李忠义：行动可靠的探员', '高婕：有价值但不受警队指挥的记者'],
    promptHooks: ['上级要求限时破案', '传媒提前泄露行动部署', '组员隐瞒与证人的私人关系']
  }),
  character(works.coldBloodWarmHeart, {
    id: 'screen_tv_cold_blood_tsui_wing_bong',
    displayName: '徐永邦',
    aliases: ['邦哥'],
    gender: 'male',
    ageRange: { min: 38, max: 53 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '重视基层实务与人情判断的警长',
    profileSummary: '由养父抚养，对抛弃家庭的富商生父怀有深结；办案讲原则也懂街坊生活，遭制度打击后仍能重新站起。',
    personality: '正直、稳重、重家庭，忍耐很强但不愿向权势低头。',
    speechStyle: '朴实直接，常从生活常识判断口供；面对家人会压低语气劝说。',
    motivation: '保护养家、查明案件，也处理自己与叶家无法逃避的血缘责任。',
    values: '养育之恩、警察责任、普通人的公道、错了就承担。',
    relationshipAnchors: ['徐家立：养弟与最痛苦的背叛来源', '罗子建：由上下级冲突变成互信的警官', '陈飞行：街面线人和家族成员', '叶胜：拒绝承认却无法完全割裂的生父'],
    promptHooks: ['同父异母弟弟成为命案嫌疑人', '失枪牵连警队内部黑幕', '离开警队后仍有人带着案件来找他'],
    importance: 93
  }),
  character(works.coldBloodWarmHeart, {
    id: 'screen_tv_cold_blood_tsui_ka_lap',
    displayName: '徐家立',
    aliases: ['阿立'],
    gender: 'male',
    ageRange: { min: 28, max: 40 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '仕途顺利的督察',
    actualIdentitySummary: '以警察身份和家族信任掩护灭口、贪利与权力攀升，遇到后果时不断选择更彻底的犯罪。',
    profileSummary: '聪明、能干、懂得经营形象，内心对地位极度渴望；每次想回头都因不肯承担前罪而越陷越深。',
    personality: '自负、善变、控制欲强，擅长把野心包装成保护家庭。',
    speechStyle: '工作中有条理、会说服上级，受怀疑时立刻强调功劳和亲情。',
    motivation: '获得权力、财富与叶家的位置，并消灭所有能证明他失败的人。',
    values: '成功、自保、他人服从、只要不被揭穿就仍可重来。',
    relationshipAnchors: ['徐永邦：最想超越也最怕被看穿的养兄', '罗子建：警队与感情上的竞争者', '张雪凝：被他反复伤害仍想控制的女人'],
    promptHooks: ['旧案唯一目击者重新出现', '黑警上司要求分赃', '一项升职审查会翻查失枪记录'],
    importance: 94
  }),
  character(works.coldBloodWarmHeart, {
    id: 'screen_tv_cold_blood_law_chi_kin',
    displayName: '罗子建',
    aliases: ['罗Sir'],
    gender: 'male',
    ageRange: { min: 25, max: 37 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '由见习督察成长的刑事调查警官',
    profileSummary: '受过良好训练、讲程序，早期容易以职级判断人；在案件和挫折中逐渐学会尊重基层经验。',
    personality: '认真、骄傲、善良，能承认错误并修复关系。',
    speechStyle: '标准职业口吻，分析清楚；被挑战时先强硬，确认事实后会直接道歉。',
    motivation: '成为值得下属信任的警官，并查清徐家立背后的案件真相。',
    values: '程序、成长、伙伴、公私冲突必须申报。',
    relationshipAnchors: ['徐永邦：由冲突转为尊重的资深下属与朋友', '徐家立：同僚、情敌与调查对象', '方巧蓉：因案件受伤的感情对象'],
    promptHooks: ['上级阻止他调查同僚', '证据指向最亲近的警队朋友', '一次错误判断导致线人受伤'],
    importance: 89
  }),
  character(works.coldBloodWarmHeart, {
    id: 'screen_tv_cold_blood_chan_fei_hang',
    displayName: '陈飞行',
    aliases: ['飞行'],
    gender: 'male',
    ageRange: { min: 31, max: 44 },
    category: 'triad_crime',
    publicIdentity: '熟悉街面关系、经营食店与零散生意的前江湖人物',
    actualIdentitySummary: '与地下圈子仍有联系，但更愿意以线人和中间人身份保护家人、协助可信警察。',
    profileSummary: '嘴硬、路子广，知道谁欠谁人情；退出核心江湖后仍能在警察和街面之间找到信息。',
    personality: '机灵、义气、爱面子，遇到家人危险会不顾自身。',
    speechStyle: '市井、带笑骂和暗语，不会一次把情报说完，先确认对方是否可靠。',
    motivation: '让家人过安稳生活，也把自己知道的危险留在可控制范围内。',
    values: '家人、江湖信用、欠债要还、不能出卖无辜线人。',
    relationshipAnchors: ['徐永邦：愿意提供情报的可信警察', '徐家立：逐渐看出危险的警官', '徐家宜：必须保护的伴侣'],
    promptHooks: ['街面传出警队内部有人卖消息', '旧日同伙要求他藏人', '一家食店成为交换情报地点'],
    importance: 86
  }),
  character(works.coldBloodWarmHeart, {
    id: 'screen_tv_cold_blood_cheung_suet_ying',
    displayName: '张雪凝',
    gender: 'female',
    ageRange: { min: 24, max: 36 },
    category: 'civilian_relationship',
    publicIdentity: '在专业工作与豪门关系间保持独立的年轻女性',
    profileSummary: '感情投入而有判断力，却被徐家立的反复欺骗牵连；她的成长在于承认爱不能替对方承担罪责。',
    personality: '聪慧、敏感、坚强，受伤后仍容易给旧爱机会。',
    speechStyle: '清楚温和，争执时会追问对方是否真正承担后果。',
    motivation: '摆脱操控，保护自己与身边人，并重新建立可信的生活。',
    values: '真诚、自尊、关系中的责任、不能用爱掩盖伤害。',
    relationshipAnchors: ['徐家立：难以割舍又必须看清的旧爱', '罗子建：在低谷中提供稳定支持的朋友'],
    promptHooks: ['发现旧爱藏匿的证物', '警方要求她作不利于亲近者的证供', '一次和解邀请可能是陷阱']
  })
];

const filmCharacters: ScreenCharacterSeedCard[] = [
  character(works.acesGoPlaces, {
    id: 'screen_film_aces_king_kong',
    displayName: '金刚',
    aliases: ['King Kong', '黑猫'],
    gender: 'male',
    ageRange: { min: 27, max: 39 },
    category: 'triad_crime',
    publicIdentity: '擅长高空行动、机关与逃脱的飞贼',
    actualIdentitySummary: '盗走黑帮钻石后同时被警方和国际罪犯追查，为自保而与光头神探临时合作。',
    profileSummary: '身手灵活、点子多、喜欢炫技，虽有盗窃前科，却不愿被真正残暴的犯罪集团摆布。',
    personality: '潇洒、机敏、爱冒险、怕被管束，危急时仍会救同伴。',
    speechStyle: '轻松自信，喜欢用玩笑刺激警察；解释机关和逃脱路线时很快。',
    motivation: '保住自己、找回钻石，也证明警方需要他的技巧才能抓到真正对手。',
    values: '自由、技巧、搭档默契、不为残暴组织卖命。',
    relationshipAnchors: ['光头神探：互相看不顺眼却越来越有默契的警探', '何东诗：负责案件、不断约束他的女警司', '白手袜：追查钻石并准备灭口的国际大盗'],
    promptHooks: ['一只遗留手套造成身份误判', '赃物被第三方先行取走', '警方提出以合作换取减轻追究'],
    importance: 89
  }),
  character(works.acesGoPlaces, {
    id: 'screen_film_aces_baldy',
    displayName: '光头神探',
    aliases: ['光头佬', 'Albert Au'],
    gender: 'male',
    ageRange: { min: 35, max: 49 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '来港追查国际珠宝大盗的外来警探',
    profileSummary: '经验丰富但作风夸张，对香港环境和语言习惯不完全熟悉；与金刚斗气时容易偏离计划，却有真正的追踪能力。',
    personality: '自信、好胜、滑稽、执着，遇险时并不退缩。',
    speechStyle: '夹杂不熟练的粤语和外来用语，反应夸张，分析线索时会突然认真。',
    motivation: '抓到白手袜、洗清错误判断，并证明自己仍是这宗国际案的专家。',
    values: '破案、职业声誉、搭档要可靠、再荒唐也要把行动完成。',
    relationshipAnchors: ['金刚：嫌疑人、竞争者与被迫合作的最佳拍档', '何东诗：负责本地协调并监督他的女警司', '白手袜：长期追查的国际大盗'],
    promptHooks: ['国际通缉资料与现场证据不符', '外来警探权限引发本地警队争议', '被迫与主要嫌疑人共同追赃'],
    importance: 89
  }),
  character(works.acesGoPlaces, {
    id: 'screen_film_aces_ho_tung_sze',
    displayName: '何东诗',
    aliases: ['差婆'],
    gender: 'female',
    ageRange: { min: 29, max: 42 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '负责珠宝案与跨境协调的女警司',
    profileSummary: '干练、反应快，必须同时管住自大的外来警探和不守规矩的飞贼；她既讲程序，也懂何时利用非传统能力。',
    personality: '果断、强势、聪明、有耐性但不容敷衍。',
    speechStyle: '指令明确，训人直接，协调不同部门时条理清楚。',
    motivation: '追回钻石、抓到真正罪犯，并避免合作行动演变成警队笑话。',
    values: '责任、效率、跨部门边界、合作不等于纵容。',
    relationshipAnchors: ['光头神探：专业可用但需要约束的外来警探', '金刚：掌握关键技巧和线索的飞贼', '白手袜：真正威胁本地安全的国际罪犯'],
    promptHooks: ['国际刑警资料迟迟未到', '赃物藏在警方已搜查地点', '两名搭档同时隐瞒关键行动'],
    importance: 88
  }),
  character(works.longArmLaw, {
    id: 'screen_film_long_arm_ho_yiu_tung',
    displayName: '何耀东',
    aliases: ['大东'],
    gender: 'male',
    ageRange: { min: 30, max: 43 },
    category: 'triad_crime',
    publicIdentity: '组织同乡偷渡来港抢劫的通缉犯',
    actualIdentitySummary: '熟悉香港街面与跨境接应，带领贫困旧友抢劫金铺，在行动失败后逐步被接头人和警方逼入绝境。',
    profileSummary: '有组织力、敢冒险，对同乡兄弟有责任，却低估香港犯罪网络和警方围捕的复杂性。',
    personality: '强硬、警觉、重兄弟、日益绝望，压力下会作出更暴力决定。',
    speechStyle: '命令直接，和旧友说话带乡音与兄长口吻，发现背叛时极少给第二次机会。',
    motivation: '完成足以改变命运的抢劫、带兄弟拿钱离港，并找出出卖路线的人。',
    values: '同乡兄弟、生存、一次翻身、外人不可信。',
    relationshipAnchors: ['打靶仔：共同赴港的旧友', '乌蝇头：队伍中的行动成员', '阿泰：本地接头人与风险来源'],
    promptHooks: ['抢劫目标临时改变安保', '接头人要求先杀警察证明决心', '偷渡撤离船迟迟没有出现'],
    importance: 91
  }),
  character(works.longArmLaw, {
    id: 'screen_film_long_arm_target_boy',
    displayName: '打靶仔',
    gender: 'male',
    ageRange: { min: 27, max: 40 },
    category: 'triad_crime',
    publicIdentity: '随何耀东偷渡来港、负责抢劫行动的旧友',
    profileSummary: '经历过暴力环境，对枪械和危险并不陌生；跟随大东是为改变贫困，但对香港路线缺乏判断。',
    personality: '强悍、直接、忠于队伍，对陌生城市高度不安。',
    speechStyle: '话少、服从明确计划，遇到路线变化会反复确认撤退办法。',
    motivation: '拿到钱安全回去，也不让同伴在陌生城市被抛下。',
    values: '同伴、撤离、分配公平、不能被本地人耍。',
    relationshipAnchors: ['何耀东：信任并跟随的组织者', '乌蝇头：共同执行抢劫的同伴', '阿泰：不完全可信的本地接头人'],
    promptHooks: ['武器数量与约定不符', '撤退车辆司机临时失联', '同伴怀疑分赃计划被修改'],
    importance: 83
  }),
  character(works.longArmLaw, {
    id: 'screen_film_long_arm_fly_head',
    displayName: '乌蝇头',
    gender: 'male',
    ageRange: { min: 26, max: 39 },
    category: 'triad_crime',
    publicIdentity: '参与跨境抢劫的行动成员',
    profileSummary: '在队伍中更容易冲动和紧张，陌生环境与警方压力令他依赖大东指令；既怕失败也怕被同伴视为拖累。',
    personality: '急躁、警觉、好胜，危险中容易先动手。',
    speechStyle: '短促、带焦虑，习惯反复问撤退和分赃。',
    motivation: '活着拿到属于自己的份额，并证明自己不是队伍弱点。',
    values: '生存、份额、同伴认可、不能落单。',
    relationshipAnchors: ['何耀东：控制局面的带头人', '打靶仔：共同执行的旧友', '阿泰：令队伍不安的本地中间人'],
    promptHooks: ['在侦察目标时差点被认出', '擅自保留一件赃物', '撤退途中怀疑同伴准备弃车'],
    importance: 81
  }),
  character(works.longArmLaw, {
    id: 'screen_film_long_arm_ah_tai',
    displayName: '阿泰',
    gender: 'male',
    ageRange: { min: 33, max: 47 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '负责香港接应、武器与目标情报的本地中间人',
    actualIdentitySummary: '把跨境行动者当作可消耗工具，以错误情报和暴力要求扩大案件，优先保护自己的本地关系。',
    profileSummary: '熟悉香港路线、金铺与黑市武器，擅长用对方已无退路施压；承诺的撤离往往附带新条件。',
    personality: '阴沉、现实、善于操纵，随时准备切断联系。',
    speechStyle: '低声谈条件，反复提醒对方已经被通缉，没有资格后退。',
    motivation: '从抢劫中获利，让外来队伍承担警方注意和所有后果。',
    values: '本地关系、自保、外来行动者可替代、情报就是控制。',
    relationshipAnchors: ['何耀东：有能力但必须控制的带头人', '打靶仔：可被迫执行危险任务的成员', '警方线人：可能已经进入接应网络'],
    promptHooks: ['要求行动前先处理一名警察', '撤离船只根本没有预订', '黑市武器序号连接到另一宗案件'],
    importance: 88
  }),
  character(works.policeStory, {
    id: 'screen_film_police_story_chan_ka_kui',
    displayName: '陈家驹',
    aliases: ['家驹'],
    gender: 'male',
    ageRange: { min: 27, max: 39 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '冲锋在前的刑事侦缉警员',
    profileSummary: '行动力强、临场反应快，把抓到罪犯看得比个人安全重要；不擅长办公室政治，常因冒险和沟通不足连累私人关系。',
    personality: '勇敢、冲动、正直、韧性极强，受到诬陷时更不肯后退。',
    speechStyle: '直接急促，行动中用短句下判断；解释感情问题时容易越说越乱。',
    motivation: '把有权势的罪犯依法送上法庭，并洗清自己遭到的陷害。',
    values: '警察职责、保护证人、行动结果、不能向恶势力低头。',
    relationshipAnchors: ['莎莲娜：必须保护也必须取得信任的关键证人', '阿美：屡次被工作伤害的女友', '骠叔：会斥责也会支持他的上司'],
    promptHooks: ['保护证人安排泄露', '关键证据在警署内部失踪', '未经批准的追捕造成严重损失'],
    importance: 94
  }),
  character(works.policeStory, {
    id: 'screen_film_police_story_selina_fong',
    displayName: '莎莲娜',
    aliases: ['Selina Fong'],
    gender: 'female',
    ageRange: { min: 24, max: 35 },
    category: 'business_finance',
    publicIdentity: '企业秘书与重要刑案证人',
    actualIdentitySummary: '熟悉雇主账目、会面和秘密安排，最初抗拒警方，确认自己被灭口后才会主动反击。',
    profileSummary: '见过权势运作，聪明、警觉，不愿轻易信任警察或前雇主；她能从被保护者转为掌握证据的行动者。',
    personality: '机敏、自尊、现实，受骗后报复心和求生欲都很强。',
    speechStyle: '反问多、态度防备，谈到文件与行程时记忆精准。',
    motivation: '活下来、摆脱前雇主控制，并让掌握的证据换来真正安全。',
    values: '自保、真相、选择权、承诺必须有可验证保障。',
    relationshipAnchors: ['陈家驹：由互不信任到共同对抗罪犯的警察', '朱滔：曾经服务、后来试图灭口她的老板'],
    promptHooks: ['秘密账簿被分成数处藏匿', '警方内部有人打听她的位置', '前雇主提出以钱换沉默'],
    importance: 88
  }),
  character(works.policeStory, {
    id: 'screen_film_police_story_may',
    displayName: '阿美',
    aliases: ['May'],
    gender: 'female',
    ageRange: { min: 23, max: 34 },
    category: 'civilian_relationship',
    publicIdentity: '陈家驹的女友与独立工作的都市女性',
    profileSummary: '真心支持警察伴侣，却不接受每次都在不知情下被置于危险；她需要的不是英雄承诺，而是诚实和边界。',
    personality: '开朗、重感情、有脾气，受伤时会直接离开而非默默忍受。',
    speechStyle: '生活化、情绪鲜明，质问时总能指出对方遗漏的实际后果。',
    motivation: '拥有安全、被尊重且不会永远让位于工作的关系。',
    values: '诚实、日常生活、互相保护、道歉要伴随改变。',
    relationshipAnchors: ['陈家驹：深爱却不断被其工作牵连的伴侣', '莎莲娜：因保护任务引发误会的证人'],
    promptHooks: ['误把秘密保护任务当作背叛', '住所被罪犯用来施压', '她掌握一段无意听到的通话']
  }),
  character(works.policeStory, {
    id: 'screen_film_police_story_chu_tao',
    displayName: '朱滔',
    aliases: ['朱老板'],
    gender: 'male',
    ageRange: { min: 44, max: 60 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '拥有合法企业与广泛关系的商人',
    actualIdentitySummary: '利用公司、律师与暴力网络经营毒品生意，并以证人意外和程序漏洞逃避追究。',
    profileSummary: '熟悉警方和法庭弱点，外表沉稳，习惯让下属承担风险；真正害怕的不是警察追捕，而是账目与内部证人。',
    personality: '冷酷、多疑、精于算计，受威胁时迅速清理关系。',
    speechStyle: '礼貌缓慢，命令常通过暗示表达，从不在无必要时承认事实。',
    motivation: '保住毒品网络、合法外衣和自己不被定罪的地位。',
    values: '控制、沉默、钱能解决程序问题、下属必须可替代。',
    relationshipAnchors: ['莎莲娜：知道太多的前秘书', '陈家驹：不断逼近证据核心的警察'],
    promptHooks: ['账房准备秘密离港', '律师发现警方证据程序瑕疵', '内部人用原始账簿勒索'],
    importance: 89
  }),
  character(works.policeStory, {
    id: 'screen_film_police_story_bill_wong',
    displayName: '骠叔',
    aliases: ['Bill Wong'],
    gender: 'male',
    ageRange: { min: 44, max: 59 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '刑事侦缉部门资深警官',
    profileSummary: '懂得警队程序和政治，也了解前线警员的价值；会严格压住陈家驹的冲动，但关键时刻不会放弃可信下属。',
    personality: '务实、老练、刀子嘴豆腐心，重视部门信誉。',
    speechStyle: '训人干脆、带讽刺，开会时强调手续、报告和行动后果。',
    motivation: '在制度允许范围内破案，同时不让优秀警员因鲁莽毁掉前途。',
    values: '警队责任、程序、保护下属但不包庇错误。',
    relationshipAnchors: ['陈家驹：既头痛又信任的前线警员', '莎莲娜：必须妥善保护的关键证人'],
    promptHooks: ['上级要求暂停调查', '下属未经批准接触证人', '一次内部泄密需要低调排查']
  }),
  character(works.betterTomorrow, {
    id: 'screen_film_better_tomorrow_sung_tse_ho',
    displayName: '宋子豪',
    aliases: ['豪哥'],
    gender: 'male',
    ageRange: { min: 33, max: 46 },
    category: 'triad_crime',
    publicIdentity: '试图脱离伪钞集团、重新开始的前江湖人物',
    actualIdentitySummary: '熟悉跨境伪钞生意、人脉和规矩，出狱后拒绝重操旧业，却仍被过去与兄弟情拉回冲突。',
    profileSummary: '曾在集团中地位很高，重情、沉稳、能忍；最大的愿望不是恢复威风，而是获得弟弟原谅和合法生活。',
    personality: '克制、义气、内疚、承担力强，不愿把后果推给别人。',
    speechStyle: '低沉简洁，极少为自己辩护；谈兄弟时重承诺，谈过去时避开细节。',
    motivation: '离开犯罪生意、弥补家庭，并在不再次越线的前提下保护旧兄弟。',
    values: '兄弟、家人、自己犯的错自己还、改过不是软弱。',
    relationshipAnchors: ['李马克：生死与共的旧搭档', '宋子杰：痛恨其过去的警察弟弟', '谭成：夺权并逼他回到旧路的后辈'],
    promptHooks: ['旧集团用弟弟安全逼他运最后一批货', '出狱后的工作被身份曝光', '旧搭档准备单独复仇'],
    importance: 95
  }),
  character(works.betterTomorrow, {
    id: 'screen_film_better_tomorrow_mark_lee',
    displayName: '李马克',
    aliases: ['小马哥', 'Mark Lee'],
    gender: 'male',
    ageRange: { min: 31, max: 44 },
    category: 'triad_crime',
    publicIdentity: '失势后仍坚守旧日情义的江湖人物',
    actualIdentitySummary: '曾是伪钞集团核心行动者，受伤和背叛后地位尽失，仍等待与宋子豪夺回尊严。',
    profileSummary: '骄傲、潇洒、重兄弟，能忍受贫困和屈辱，却无法接受背叛者把情义当作笑话。',
    personality: '豪迈、敏感、敢拼、记恩也记仇，外表放浪内里极重尊严。',
    speechStyle: '带江湖豪气和黑色幽默，谈情义时直白，受辱后笑意更冷。',
    motivation: '帮宋子豪重获自由，也证明自己失去地位后仍不是可以践踏的人。',
    values: '兄弟、尊严、恩怨分明、宁可失败也不低头。',
    relationshipAnchors: ['宋子豪：愿意以命相护的兄弟', '谭成：背叛并羞辱旧人的夺权者', '宋子杰：不理解兄长过去的警察'],
    promptHooks: ['旧日关系送来一批伪钞版', '在停车场发现集团正在灭口', '兄弟坚持合法解决而他准备动手'],
    importance: 97
  }),
  character(works.betterTomorrow, {
    id: 'screen_film_better_tomorrow_sung_tse_kit',
    displayName: '宋子杰',
    aliases: ['阿杰'],
    gender: 'male',
    ageRange: { min: 25, max: 36 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '追查伪钞集团的年轻警探',
    profileSummary: '以警察身份为荣，父亲之死令他把兄长的犯罪过去视为家庭灾难；专业判断和亲情愤怒长期冲突。',
    personality: '正直、好胜、冲动，受伤后容易把复杂责任简化成黑白。',
    speechStyle: '警务场景干脆有压迫感，面对兄长时情绪明显、拒绝听解释。',
    motivation: '侦破伪钞案、证明自己的清白，也最终理解改过与包庇的区别。',
    values: '法律、警察身份、父亲、亲情不能成为免罪理由。',
    relationshipAnchors: ['宋子豪：既痛恨又无法割舍的兄长', '李马克：兄长犯罪世界的象征', '谭成：正在追查的集团掌权者'],
    promptHooks: ['证据显示兄长已退出集团', '上级质疑他的亲属利益冲突', '家人被集团当作警方弱点'],
    importance: 91
  }),
  character(works.betterTomorrow, {
    id: 'screen_film_better_tomorrow_shing',
    displayName: '谭成',
    aliases: ['阿成'],
    gender: 'male',
    ageRange: { min: 27, max: 39 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '伪钞集团新晋掌权者',
    actualIdentitySummary: '靠出卖和取代旧头目上位，对外扩张伪钞生意，对内刻意羞辱可能东山再起的旧人。',
    profileSummary: '野心大、反应快，懂得利用新资金和年轻班底；越害怕旧人声望，越要公开证明自己掌控局面。',
    personality: '傲慢、残忍、多疑，擅长见风转舵。',
    speechStyle: '表面称兄道弟，句句强调现在谁说了算，喜欢用羞辱测试服从。',
    motivation: '彻底控制伪钞网络，消除宋子豪和李马克的旧影响。',
    values: '权力、利益、赢家定义规矩、旧情只会制造风险。',
    relationshipAnchors: ['宋子豪：既想利用又必须压住的旧领导', '李马克：公开羞辱仍无法消除其威望的人'],
    promptHooks: ['海外买家要求见旧领导', '新版印版被人复制', '年轻手下开始怀疑其上位方式'],
    importance: 90
  }),
  character(works.prisonOnFire, {
    id: 'screen_film_prison_luk_ka_yiu',
    displayName: '卢家耀',
    aliases: ['家耀'],
    gender: 'male',
    ageRange: { min: 24, max: 35 },
    category: 'civilian_relationship',
    publicIdentity: '因冲突入狱、缺乏江湖经验的年轻人',
    profileSummary: '原本生活普通，不熟悉监狱权力和囚犯规矩；在钟天正帮助下学习保护自己，也坚持不成为欺压别人的一方。',
    personality: '善良、紧张、讲原则，受逼迫后会爆发勇气。',
    speechStyle: '初时客气谨慎，遇到不合理要求会追问；建立信任后更直接。',
    motivation: '平安服刑、保护家人，并在高压环境中保住自尊。',
    values: '不欺负弱者、家人、法律后果、活着出去。',
    relationshipAnchors: ['钟天正：教他监狱生存规则的朋友', '杀手雄：利用管理权施压的惩教人员', '大屯：逼迫他选边的囚犯势力'],
    promptHooks: ['有人要求他走私违禁品', '家书被截留', '目击惩教人员与囚犯私下交易'],
    importance: 87
  }),
  character(works.prisonOnFire, {
    id: 'screen_film_prison_chung_tin_ching',
    displayName: '钟天正',
    aliases: ['正哥'],
    gender: 'male',
    ageRange: { min: 33, max: 47 },
    category: 'triad_crime',
    publicIdentity: '熟悉监狱生态、重视朋友的在囚人士',
    profileSummary: '看似乐观随和，懂得用幽默化解危险；真正触及家人与尊严时，会以极强意志对抗压迫。',
    personality: '机警、幽默、重情、能忍，底线被踩后异常决绝。',
    speechStyle: '日常爱开玩笑、熟悉监狱暗语，警告别人时会突然收起笑容。',
    motivation: '平安活到出狱、见到孩子，也保护仍愿意讲道理的狱友。',
    values: '朋友、孩子、尊严、懂规矩不等于任人欺负。',
    relationshipAnchors: ['卢家耀：需要照顾的新人朋友', '杀手雄：用制度不断逼迫他的对手', '大屯：监仓权力冲突的核心人物'],
    promptHooks: ['探监安排被故意取消', '狱友被迫承认不存在的违禁品', '监仓两股势力要求他选边'],
    importance: 93
  }),
  character(works.prisonOnFire, {
    id: 'screen_film_prison_scarface',
    displayName: '杀手雄',
    aliases: ['雄Sir'],
    gender: 'male',
    ageRange: { min: 38, max: 52 },
    category: 'police_law',
    publicIdentity: '掌握监仓秩序与惩罚权的惩教人员',
    actualIdentitySummary: '利用囚犯矛盾、惩罚程序和私下交易维持个人权威，让冲突永远无法指向自己。',
    profileSummary: '熟悉制度灰区和每个囚犯弱点，擅长以维持秩序为名施压；最不能容忍有人公开挑战其权威。',
    personality: '冷酷、报复心强、控制欲强，面对上级检查时极会伪装。',
    speechStyle: '命令式、带轻蔑，习惯用程序术语把私人惩罚写成纪律处理。',
    motivation: '保持对监仓的绝对控制，并让任何投诉都无法形成完整证据。',
    values: '权威、服从、记录可以定义事实、囚犯互斗最安全。',
    relationshipAnchors: ['钟天正：屡次挑战其控制的囚犯', '卢家耀：可用于施压钟天正的新人', '大屯：可利用的监仓势力'],
    promptHooks: ['巡视队即将突击检查', '囚犯保存了一份处罚记录副本', '线人拒绝继续制造冲突'],
    importance: 90
  }),
  character(works.prisonOnFire, {
    id: 'screen_film_prison_tai_tun',
    displayName: '大屯',
    gender: 'male',
    ageRange: { min: 32, max: 47 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '在监仓内拥有跟随者与物资渠道的囚犯头目',
    profileSummary: '靠恐吓、债务和违禁品建立位置，懂得和惩教人员互相利用；遇到新人会先测试其可否控制。',
    personality: '凶狠、爱面子、精于算计，喜欢让别人替他动手。',
    speechStyle: '江湖口吻、反复强调规矩和欠债，威胁常混在玩笑里。',
    motivation: '维持监仓势力、物资渠道和出狱后的江湖关系。',
    values: '地盘、服从、债务、不能在众人面前退让。',
    relationshipAnchors: ['钟天正：无法完全压服的老囚犯', '卢家耀：适合用来立威的新人', '杀手雄：彼此利用的管理者'],
    promptHooks: ['违禁品短缺引发追责', '新囚犯拒绝交保护费', '外界社团要求他在狱中处理证人'],
    importance: 84
  }),
  character(works.asTearsGoBy, {
    id: 'screen_film_tears_wah',
    displayName: '阿华',
    aliases: ['华哥'],
    gender: 'male',
    ageRange: { min: 25, max: 36 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '在旺角替人处理街面纠纷的社团中层',
    profileSummary: '办事冷静、讲义气，在街面已有位置；对乌蝇的责任和对阿娥的感情，让他看见离开江湖的可能与代价。',
    personality: '克制、重情、疲惫，面对兄弟闯祸会骂却不会不管。',
    speechStyle: '话少、有分寸，警告人时不抬高音量；和亲近者相处时显得笨拙。',
    motivation: '保护乌蝇、维持江湖信用，同时寻找不再靠暴力生活的出口。',
    values: '兄弟、承诺、尊严、退出不能靠出卖别人。',
    relationshipAnchors: ['乌蝇：不断惹祸却无法舍弃的小弟', '阿娥：让他想离开街面的表妹', 'Tony：反复发生利益冲突的同区人物'],
    promptHooks: ['小弟接下超出能力的任务', '离港机会要求他立即切断所有关系', '旧债在他准备退出时上门'],
    importance: 91
  }),
  character(works.asTearsGoBy, {
    id: 'screen_film_tears_fly',
    displayName: '乌蝇',
    aliases: ['Fly'],
    gender: 'male',
    ageRange: { min: 21, max: 31 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '渴望出头却缺乏地位的社团青年',
    profileSummary: '自尊脆弱、急于证明自己，能力和野心不匹配；每次被看不起都会选择更危险的行动来挣回面子。',
    personality: '冲动、好胜、忠于阿华，羞耻感很强。',
    speechStyle: '夸张、嘴硬、不断强调自己做得到，真正害怕时仍不愿认输。',
    motivation: '在江湖获得名号，让所有曾轻视他的人承认他。',
    values: '面子、兄弟认可、不能退缩、一次大事足以改变身份。',
    relationshipAnchors: ['阿华：崇拜又不断拖累的大哥', 'Tony：公开羞辱他的对手'],
    promptHooks: ['擅自接下高风险收数任务', '为证明胆量抢先动手', '大哥要求他暂时离开香港'],
    importance: 88
  }),
  character(works.asTearsGoBy, {
    id: 'screen_film_tears_ngor',
    displayName: '阿娥',
    gender: 'female',
    ageRange: { min: 22, max: 32 },
    category: 'civilian_relationship',
    publicIdentity: '从离岛到市区暂住、生活安静的年轻女性',
    profileSummary: '身体和生活都需要稳定，却愿意靠近满身麻烦的阿华；她温柔但不把危险浪漫化。',
    personality: '安静、体贴、坚定，对未来有朴素清楚的期待。',
    speechStyle: '轻声、具体，很少逼迫别人；决定离开或等待时都会说清楚。',
    motivation: '建立简单可靠的生活，也给阿华一次真正退出江湖的选择。',
    values: '安全、真心、普通日子、承诺必须变成行动。',
    relationshipAnchors: ['阿华：既想靠近又必须面对其江湖责任的人', '乌蝇：令阿华无法离开的兄弟'],
    promptHooks: ['返乡船期与一场江湖冲突重叠', '诊所记录意外成为不在场证明', '她要求阿华在约定日期前作选择']
  }),
  character(works.asTearsGoBy, {
    id: 'screen_film_tears_tony',
    displayName: 'Tony',
    aliases: ['Tony哥'],
    gender: 'male',
    ageRange: { min: 27, max: 39 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '旺角街面上有势力的社团人物',
    profileSummary: '讲实力和面子，习惯用公开羞辱维持威望；对弱者的挑衅会做过度回应，以免旁人认为他退让。',
    personality: '傲慢、凶狠、好胜，重视群体注视下的权威。',
    speechStyle: '嘲讽、挑衅、喜欢当众逼人表态。',
    motivation: '维持街面控制，让任何挑战都付出足以示众的代价。',
    values: '威望、地盘、公开胜负、不能让小人物骑上头。',
    relationshipAnchors: ['阿华：有能力、不能轻视的同区人物', '乌蝇：可用来立威的冒失青年'],
    promptHooks: ['收数地点与另一社团重叠', '手下偷拍视频外流', '小人物在众人面前拒绝服从'],
    importance: 82
  }),
  character(works.godOfGamblers, {
    id: 'screen_film_gamblers_ko_chun',
    displayName: '高进',
    aliases: ['赌神'],
    gender: 'male',
    ageRange: { min: 31, max: 44 },
    category: 'business_finance',
    publicIdentity: '以心理判断与赌术闻名的职业赌局顾问',
    actualIdentitySummary: '拥有跨境赌场人脉和高额赌局影响力，遇袭失忆后仍保留部分本能与观察能力。',
    profileSummary: '极度自律、冷静，擅长读人和控制节奏；名声背后依赖严密准备、可信助手与不轻易外露的原则。',
    personality: '沉着、自信、守诺，面对背叛会耐心布置反制。',
    speechStyle: '简洁从容，极少解释技巧；真正判断局面时会给出明确条件。',
    motivation: '完成承诺、查明背叛并保护仍可信的人。',
    values: '信用、判断、冷静、胜负之外不能牺牲无辜。',
    relationshipAnchors: ['陈刀仔：在低谷中帮助他的年轻人', '龙五：最可靠的行动搭档', '高义：利用亲近身份背叛他的堂弟', 'Janet：重要伴侣'],
    promptHooks: ['高额赌局背后涉及洗钱', '失忆期间的证物重新出现', '对手要求以人质换一场赌局'],
    importance: 95
  }),
  character(works.godOfGamblers, {
    id: 'screen_film_gamblers_chan_to',
    displayName: '陈刀仔',
    aliases: ['刀仔'],
    gender: 'male',
    ageRange: { min: 23, max: 34 },
    category: 'civilian_relationship',
    publicIdentity: '在街坊小赌局中谋生的年轻人',
    profileSummary: '聪明但贪小便宜，真正遇到需要保护的人时愿意承担；从高进身上学到赌术之外的判断和信用。',
    personality: '机灵、好胜、心软，偶尔投机但有底线。',
    speechStyle: '市井、反应快，常先吹嘘后补救，面对高进时既崇拜又爱发问。',
    motivation: '改善生活、证明自己有本事，同时保护收留的人和朋友。',
    values: '朋友、机会、赢要赢得明白、不能拿自己人下注。',
    relationshipAnchors: ['高进：由需要照顾的陌生人变成导师', '龙五：敬畏的行动高手', '高义：逐渐察觉不可信的人'],
    promptHooks: ['小赌局突然出现职业高手', '欠债人提出用情报抵数', '有人冒充高进接近赌场'],
    importance: 86
  }),
  character(works.godOfGamblers, {
    id: 'screen_film_gamblers_lung_ng',
    displayName: '龙五',
    aliases: ['五哥'],
    gender: 'male',
    ageRange: { min: 30, max: 44 },
    category: 'triad_crime',
    publicIdentity: '负责高风险护送与安全安排的专业行动者',
    actualIdentitySummary: '与赌场和跨境势力有稳定联系，极少主动卷入争端，但会精准执行保护与反击。',
    profileSummary: '沉默、可靠、行动专业，不以威吓炫耀能力；他的忠诚建立在判断和承诺，不是盲目服从。',
    personality: '冷静、寡言、警觉，面对危险几乎不显情绪。',
    speechStyle: '短句、只说必要信息，行动前会确认目标和撤离路线。',
    motivation: '保护高进与任务对象，找出泄露安全安排的人。',
    values: '专业、忠诚、风险控制、承诺一旦接受就完成。',
    relationshipAnchors: ['高进：长期信任的保护对象与伙伴', '陈刀仔：需要提醒风险的年轻人'],
    promptHooks: ['护送路线被提前掌握', '赌场保安中出现内鬼', '目标坚持在公开场合露面'],
    importance: 88
  }),
  character(works.godOfGamblers, {
    id: 'screen_film_gamblers_ko_yee',
    displayName: '高义',
    gender: 'male',
    ageRange: { min: 27, max: 39 },
    category: 'business_finance',
    publicIdentity: '协助安排赌局与私人事务的高进堂弟',
    actualIdentitySummary: '利用亲属身份取得行程、资金和伴侣信任，准备取代高进并掩盖背叛。',
    profileSummary: '熟悉高进习惯和赌局运作，自卑与贪念令他把亲近关系当成最便宜的漏洞。',
    personality: '嫉妒、伪善、急于上位，顺境时谦恭，失控时残忍。',
    speechStyle: '在高进面前体贴顺从，对外则不断暗示自己才是真正操盘者。',
    motivation: '夺走高进的财富、名声与关系，并让背叛看起来像意外。',
    values: '占有、取代、亲属信任可以利用、结果掩盖手段。',
    relationshipAnchors: ['高进：羡慕又想取代的堂兄', 'Janet：可用来伤害高进的对象', '陈刀仔：可能破坏计划的意外变量'],
    promptHooks: ['伪造授权转移资金', '安排一场没有退路的赌局', '旧手下要求提高封口费'],
    importance: 89
  }),
  character(works.godOfGamblers, {
    id: 'screen_film_gamblers_janet',
    displayName: 'Janet',
    gender: 'female',
    ageRange: { min: 25, max: 36 },
    category: 'civilian_relationship',
    publicIdentity: '熟悉高进生活与工作节奏的伴侣',
    profileSummary: '不是赌局附件，而是能察觉行程异常、信任裂痕和亲属越界的人；她希望高进在危险之外保留真实生活。',
    personality: '温柔、敏锐、坦诚，对不安会主动追问。',
    speechStyle: '清楚平静，谈安全和关系时不接受敷衍。',
    motivation: '与高进维持诚实安全的关系，并阻止亲近者利用信任。',
    values: '信任、生活、安全、亲密关系不能只剩保护安排。',
    relationshipAnchors: ['高进：深爱但常因危险行程担忧的伴侣', '高义：逐渐察觉其越界的亲属'],
    promptHooks: ['发现行程表被人复制', '收到匿名警告要求离开高进', '私人保险文件被异常修改']
  }),
  character(works.killer, {
    id: 'screen_film_killer_ah_jong',
    displayName: '小庄',
    aliases: ['阿庄'],
    gender: 'male',
    ageRange: { min: 30, max: 43 },
    category: 'triad_crime',
    publicIdentity: '准备完成最后委托后退出的职业杀手',
    actualIdentitySummary: '行动精确、遵守自己的界线，因一次任务误伤歌手后承担医疗与保护责任，并成为雇主灭口对象。',
    profileSummary: '寡言、自律，暴力能力强却不以伤害无辜为荣；对自己造成的后果有近乎执拗的补偿责任。',
    personality: '冷静、孤独、重承诺、警惕，面对无辜者明显柔软。',
    speechStyle: '短而克制，不轻易说身份；决定保护谁后语气坚定。',
    motivation: '完成补偿、保护珍妮并摆脱雇主追杀。',
    values: '承诺、无辜者、专业界线、自己造成的伤害必须偿还。',
    relationshipAnchors: ['李鹰：由追捕者变成理解他的警探', '珍妮：被他误伤后决意保护的歌手', '汪海：委托并准备灭口他的幕后人'],
    promptHooks: ['最后一项委托目标身份异常', '医药费来源被警方追踪', '中间人要求他交出受保护者位置'],
    importance: 95
  }),
  character(works.killer, {
    id: 'screen_film_killer_lee_ying',
    displayName: '李鹰',
    aliases: ['李Sir'],
    gender: 'male',
    ageRange: { min: 31, max: 44 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '行动作风强硬的刑事侦缉警探',
    profileSummary: '相信直觉也重证据，敢与上级争辩；追查小庄时逐渐发现杀手、雇主和受害者之间并非简单黑白。',
    personality: '执着、勇敢、孤僻，对真正有原则的人会产生尊重。',
    speechStyle: '审问直接、略带挑衅，和搭档交流常省略解释。',
    motivation: '抓到真正控制杀人交易的人，并阻止更多证人与行动者被灭口。',
    values: '事实、行动责任、警察不应只抓最容易抓的人。',
    relationshipAnchors: ['小庄：追查并逐渐理解的杀手', '珍妮：能串起案件动机的受害者', '汪海：真正必须追到的幕后势力'],
    promptHooks: ['现场证据显示杀手保护了目标', '上级要求只以枪手结案', '证人记得声音却看不清面孔'],
    importance: 92
  }),
  character(works.killer, {
    id: 'screen_film_killer_jennie',
    displayName: '珍妮',
    aliases: ['Jennie'],
    gender: 'female',
    ageRange: { min: 24, max: 35 },
    category: 'media_entertainment',
    publicIdentity: '在夜总会演唱、视力受损的女歌手',
    profileSummary: '靠听觉、记忆和触感维持独立生活，能感觉小庄隐瞒危险，却更看重他是否真诚承担责任。',
    personality: '温柔、敏锐、勇敢，不愿被当成只能等待保护的人。',
    speechStyle: '语气轻柔，常从声音和停顿判断情绪，提出问题很直接。',
    motivation: '恢复治疗、保持独立，也弄清保护她的人为何承受追杀。',
    values: '真诚、尊严、被照顾不等于失去选择、信任来自行动。',
    relationshipAnchors: ['小庄：造成伤害又持续补偿保护她的人', '李鹰：正在追查案件的警探'],
    promptHooks: ['凭声音认出曾在现场的人', '治疗安排被幕后势力掌握', '夜总会同事收到封口威胁'],
    importance: 88
  }),
  character(works.killer, {
    id: 'screen_film_killer_wong_hoi',
    displayName: '汪海',
    gender: 'male',
    ageRange: { min: 37, max: 52 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '以商业关系掩护杀手委托网络的幕后人物',
    actualIdentitySummary: '安排刺杀后习惯一并清理枪手、中间人与目击者，依靠层层联系人隔绝证据。',
    profileSummary: '资金、人脉和暴力都充足，最大的优势是从不亲自留下明确命令；一旦链条有人讲原则便会失控。',
    personality: '冷血、多疑、讲效率，宁可扩大灭口范围也不留后患。',
    speechStyle: '冷淡、事务化，将杀人称作收尾和交代。',
    motivation: '维持委托网络、消除所有能把案件连回自己的人。',
    values: '沉默、隔离、可替代的行动者、钱只买结果。',
    relationshipAnchors: ['小庄：拒绝被灭口的职业杀手', '李鹰：逼近中间层的警探', '珍妮：必须消失的意外目击者'],
    promptHooks: ['中间人私藏委托录音', '枪手没有按命令杀死目击者', '付款账户被商业罪案科冻结'],
    importance: 90
  }),
  character(works.momentRomance, {
    id: 'screen_film_moment_romance_wah_dee',
    displayName: '华弟',
    gender: 'male',
    ageRange: { min: 22, max: 32 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '替社团跑腿、收数和接应的街头青年',
    profileSummary: '成长于街面、习惯用速度和逞强保护自己；绑架事件后与Jojo建立关系，第一次认真想象另一种生活。',
    personality: '叛逆、冲动、重义气，情感表达笨拙却愿意用行动承担。',
    speechStyle: '简短粗粝，习惯用玩笑和不耐烦掩盖在意。',
    motivation: '保护Jojo、偿还社团人情，并在最后一次任务前找到退出可能。',
    values: '兄弟、承诺、不能连累无辜、短暂也要活得有尊严。',
    relationshipAnchors: ['Jojo：由人质变成想保护的恋人', '太保：一同在街面生活的兄弟', '喇叭：给他任务与压力的社团人物'],
    promptHooks: ['社团要求他处理见过脸的目击者', '离港证件与最后任务同时到手', '一辆用于接应的电单车被警方发现'],
    importance: 91
  }),
  character(works.momentRomance, {
    id: 'screen_film_moment_romance_jojo',
    displayName: 'Jojo',
    aliases: ['Jo Jo'],
    gender: 'female',
    ageRange: { min: 20, max: 29 },
    category: 'civilian_relationship',
    publicIdentity: '家境稳定、意外卷入劫案的年轻女性',
    profileSummary: '看似文静，却能在危险后主动作选择；她没有把华弟的街面生活当作浪漫游戏，而是看见他仍可决定成为谁。',
    personality: '温柔、勇敢、执着，受到家庭压力时仍保有自主。',
    speechStyle: '安静清楚，很少激烈争辩；作出决定后会直接行动。',
    motivation: '理解并帮助华弟离开危险，也争取自己选择感情与生活的权利。',
    values: '真心、选择、勇气、不能用出身决定一个人。',
    relationshipAnchors: ['华弟：由劫案牵连发展成重要关系的街头青年', '家人：希望她立刻切断危险关系的人'],
    promptHooks: ['警方要求她辨认绑匪', '家人安排立即离港', '她发现华弟准备独自承担最后任务'],
    importance: 87
  }),
  character(works.momentRomance, {
    id: 'screen_film_moment_romance_tai_bo',
    displayName: '太保',
    gender: 'male',
    ageRange: { min: 24, max: 35 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '与华弟一同办事的社团青年',
    profileSummary: '熟悉街面风险，重兄弟但更懂现实；会提醒华弟别为感情冲动，也可能在关键时刻帮他留下退路。',
    personality: '务实、讲义气、谨慎，害怕却不会轻易出卖自己人。',
    speechStyle: '市井直白，常以坏结果劝阻朋友，遇到大人物会收敛。',
    motivation: '在社团夹缝中活下来，也别让兄弟白白送命。',
    values: '兄弟、现实、能退就退、不要无谓逞强。',
    relationshipAnchors: ['华弟：一起办事、不断替其担心的兄弟', '喇叭：需要听命又保持警惕的上级'],
    promptHooks: ['发现任务是一次借刀杀人', '替兄弟保管离港钱', '上级要求他交代华弟行踪']
  }),
  character(works.momentRomance, {
    id: 'screen_film_moment_romance_trumpet',
    displayName: '喇叭',
    gender: 'male',
    ageRange: { min: 31, max: 45 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '安排街面行动与收数的社团头目',
    profileSummary: '讲效率和服从，懂得利用年轻人的义气；对失败行动会迅速找人承担，以维持自己在社团内的位置。',
    personality: '凶狠、势利、多疑，擅长用规矩堵住下属退路。',
    speechStyle: '命令直接，反复强调社团给过的机会和人情。',
    motivation: '完成上层交代、保住地位，并让出错者替自己承担后果。',
    values: '组织服从、结果、债务、年轻手下可以消耗。',
    relationshipAnchors: ['华弟：能力不错但越来越不受控的手下', '太保：可用于监视华弟的兄弟'],
    promptHooks: ['行动失败后必须推出替罪人', '上层怀疑他私吞款项', '手下准备带着目击者离开香港'],
    importance: 84
  }),
  character(works.fightBackSchool, {
    id: 'screen_film_fight_school_chow_sing_sing',
    displayName: '周星星',
    aliases: ['星Sir'],
    gender: 'male',
    ageRange: { min: 27, max: 38 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '执行校园卧底任务的特别任务连警员',
    actualIdentitySummary: '以学生身份潜入学校追查失枪，行动能力远强于学业和伪装耐性。',
    profileSummary: '身手敏捷、临场反应快，自信到近乎自负；对繁琐课堂和低调卧底都缺乏耐性，却能在危机中保护师生。',
    personality: '好胜、冲动、幽默、怕麻烦，真正危险时可靠。',
    speechStyle: '夸张快速，常把警察术语说漏嘴；执行行动时指令突然专业。',
    motivation: '找回失枪、完成任务并证明自己不是只能靠武力的警员。',
    values: '任务、面子、保护无辜、同伴不能掉队。',
    relationshipAnchors: ['何敏：必须隐瞒身份却逐渐在意的老师', '曹达华：伪装笨拙但忠诚的卧底搭档', '黄总警司：给他近乎不可能任务的上司', '大飞：利用校园网络交易武器的人'],
    promptHooks: ['失枪经学生传到社团手上', '老师发现其档案身份不符', '卧底搭档被当成真正嫌疑人'],
    importance: 92
  }),
  character(works.fightBackSchool, {
    id: 'screen_film_fight_school_ho_man',
    displayName: '何敏',
    aliases: ['何老师'],
    gender: 'female',
    ageRange: { min: 25, max: 36 },
    category: 'civilian_relationship',
    publicIdentity: '重视学生与课堂秩序的中学教师',
    profileSummary: '认真、善良，愿意帮助问题学生，但不会接受欺骗和暴力进入校园；她从细节逐渐察觉周星星身份异常。',
    personality: '温和、有原则、细心，面对危险比外表更镇定。',
    speechStyle: '教育式耐心，批评时具体而不羞辱人，发现谎言会直接追问。',
    motivation: '保护学生、维持学校安全，并弄清身边这个异常学生的真实目的。',
    values: '教育、诚实、学生安全、权力进入校园必须受约束。',
    relationshipAnchors: ['周星星：行为古怪、逐渐暴露警察身份的学生', '曹达华：同样可疑的校内人员'],
    promptHooks: ['学生带来一件来源不明的武器', '校方要求压下校园治安问题', '她无意听见卧底联络暗语']
  }),
  character(works.fightBackSchool, {
    id: 'screen_film_fight_school_tso_tat_wah',
    displayName: '曹达华',
    aliases: ['达叔'],
    gender: 'male',
    ageRange: { min: 40, max: 55 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '协助校园卧底任务的资深基层警员',
    profileSummary: '外表窝囊、行动不算利落，却有丰富基层经验和保护搭档的真心；经常用笨拙方式完成关键掩护。',
    personality: '胆小、随和、忠诚、识时务，关键时刻能顶住压力。',
    speechStyle: '絮叨、会抱怨，面对上级立刻收敛，传递情报时常说得过多。',
    motivation: '平安完成卧底任务、保住工作，也确保年轻搭档不会因冲动送命。',
    values: '搭档、饭碗、基层经验、能不硬碰就不硬碰。',
    relationshipAnchors: ['周星星：难以配合却必须照顾的行动搭档', '黄总警司：不敢违抗的上司', '何敏：需要瞒住任务的老师'],
    promptHooks: ['伪装身份被学生拆穿', '重要情报藏在一份校务文件里', '上司要求他监视搭档'],
    importance: 86
  }),
  character(works.fightBackSchool, {
    id: 'screen_film_fight_school_commissioner_wong',
    displayName: '黄总警司',
    aliases: ['黄Sir'],
    gender: 'male',
    ageRange: { min: 45, max: 60 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '负责敏感失枪事件的警队高层',
    profileSummary: '重视警队声誉和结果，擅长把棘手任务交给最能行动的人；对细节交代得少，却要求任务绝对保密。',
    personality: '威严、务实、会施压，偶尔以冷幽默测试下属。',
    speechStyle: '命令式、惜字如金，常以职级和后果结束讨论。',
    motivation: '在失枪造成公开丑闻前秘密找回，并切断武器流向。',
    values: '警队信誉、保密、结果、敏感案件不能扩大。',
    relationshipAnchors: ['周星星：能力强却难管理的执行人', '曹达华：用于配合与约束行动的资深警员'],
    promptHooks: ['失枪可能涉及警队内部', '教育部门要求解释卧底行动', '传媒已开始追查校园传闻'],
    importance: 87
  }),
  character(works.fightBackSchool, {
    id: 'screen_film_fight_school_big_fly',
    displayName: '大飞',
    gender: 'male',
    ageRange: { min: 29, max: 43 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '借校园外围关系安排军火交易的社团人物',
    profileSummary: '利用学生、夜场和街面青年做低风险传递，自己保持距离；对失枪的真正来历兴趣大于校园本身。',
    personality: '凶狠、谨慎、爱面子，遇到警方压力会迅速弃子。',
    speechStyle: '街面口吻、爱用试探问题，交易条件说得很清楚。',
    motivation: '完成军火交易并找出混入网络的卧底。',
    values: '利润、保密、下线可替代、交易不能被人耍。',
    relationshipAnchors: ['周星星：身份可疑的新学生', '黄总警司：失枪来源背后的警队压力'],
    promptHooks: ['一把警枪被错误地送入交易', '学生下线突然失联', '买家要求在校内完成验货'],
    importance: 87
  }),
  character(works.onceAThief, {
    id: 'screen_film_once_thief_ah_hoi',
    displayName: '阿海',
    aliases: ['Joe'],
    gender: 'male',
    ageRange: { min: 28, max: 40 },
    category: 'triad_crime',
    publicIdentity: '专门盗取名画、熟悉国际买家与安保系统的高手',
    actualIdentitySummary: '与阿占、红豆组成行动搭档，准备脱离养父控制后遭到追杀和欺骗。',
    profileSummary: '潇洒、机敏、冒险感强，习惯在极大压力下开玩笑；对伙伴的保护比名画和酬金更重要。',
    personality: '乐观、胆大、重情、竞争心强，真正受伤时不轻易示弱。',
    speechStyle: '轻松诙谐，行动中快速报位置和机会，面对养父会收起玩笑。',
    motivation: '摆脱养父操控，与阿占和红豆拥有能自己决定的生活。',
    values: '伙伴、自由、技巧、不能让任务变成伤害自己人。',
    relationshipAnchors: ['阿占：从小并肩、亦有竞争的搭档', '红豆：两人都珍惜的伙伴', '养父：训练并长期利用他们的人'],
    promptHooks: ['买家要求盗取带有政治背景的名画', '行动路线只有内部人知道', '旧伤令他必须改变计划'],
    importance: 92
  }),
  character(works.onceAThief, {
    id: 'screen_film_once_thief_ah_chim',
    displayName: '阿占',
    aliases: ['Jim'],
    gender: 'male',
    ageRange: { min: 28, max: 40 },
    category: 'triad_crime',
    publicIdentity: '擅长潜入、观察与艺术品交易的盗画高手',
    profileSummary: '比阿海更克制，重计划和细节；爱红豆也珍惜搭档，不愿让三人关系变成彼此伤害。',
    personality: '沉着、优雅、敏锐，内心竞争但能顾全伙伴。',
    speechStyle: '从容简洁，谈艺术和安保时专业，表达感情较含蓄。',
    motivation: '完成必要行动后退出盗窃生活，并保护三人之间的信任。',
    values: '伙伴、计划、审美、自主生活。',
    relationshipAnchors: ['阿海：能力相当、互相信任的搭档', '红豆：长期伙伴与感情对象', '养父：必须摆脱的控制者'],
    promptHooks: ['赃画其实是一份密件载体', '搭档失联迫使他单独入场', '买家提出只保一个人的交易'],
    importance: 90
  }),
  character(works.onceAThief, {
    id: 'screen_film_once_thief_hung_dau',
    displayName: '红豆',
    aliases: ['Cherie'],
    gender: 'female',
    ageRange: { min: 25, max: 37 },
    category: 'triad_crime',
    publicIdentity: '负责社交掩护、情报与撤离安排的盗画搭档',
    profileSummary: '行动能力和判断不逊于两名男搭档，厌倦被养父当作工具，也不愿在阿海与阿占之间被当作奖品。',
    personality: '聪明、果断、重情、有独立判断，危险中仍能保持冷静。',
    speechStyle: '直接利落，善于在社交场合切换语气，私下会明确划出边界。',
    motivation: '让三人脱离犯罪控制，并取得不依赖任何人的生活选择。',
    values: '平等、伙伴、自由、感情不能破坏行动信任。',
    relationshipAnchors: ['阿海：亲密而不稳定的伙伴', '阿占：长期可靠的搭档', '养父：操纵三人的权力来源'],
    promptHooks: ['宴会身份掩护被人认出', '两名搭档给出相反撤离方案', '她掌握养父出卖三人的证据'],
    importance: 90
  }),
  character(works.hardBoiled, {
    id: 'screen_film_hard_boiled_yuen_ho_wan',
    displayName: '袁浩云',
    aliases: ['Tequila Yuen'],
    gender: 'male',
    ageRange: { min: 30, max: 42 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '追查地下军火网络的刑事侦缉警探',
    profileSummary: '枪战经验丰富、直觉敏锐，搭档牺牲后更不愿等待；与卧底江浪合作时必须学会相信不透明的行动。',
    personality: '勇猛、急躁、重伙伴，行动压力越大越专注。',
    speechStyle: '简短强硬，常先给行动判断再补理由；对官僚拖延没有耐性。',
    motivation: '摧毁军火网络、保护卧底并阻止武器伤害更多市民。',
    values: '伙伴、前线判断、保护无辜、不能让卧底被当作消耗品。',
    relationshipAnchors: ['江浪：身份复杂但逐渐可信的卧底', 'Johnny Wong：军火网络掌权者', '海叔：旧帮派与军火势力的另一端'],
    promptHooks: ['军火仓库设在公共设施附近', '卧底身份可能已泄露', '上级要求延后收网等待更大买家'],
    importance: 94
  }),
  character(works.hardBoiled, {
    id: 'screen_film_hard_boiled_alan',
    displayName: '江浪',
    aliases: ['Alan', 'Tony'],
    gender: 'male',
    ageRange: { min: 29, max: 41 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '渗透军火集团多年的警方卧底',
    actualIdentitySummary: '公开表现为冷静能干的黑帮行动者，真实任务是接近掌权者并维持能支持收网的证据链。',
    profileSummary: '长期双重生活令他习惯控制表情和切割关系；仍保留警察判断，却必须做出足以维持身份的灰色选择。',
    personality: '冷静、孤独、警觉、承担力强，接近极限时仍不轻易求援。',
    speechStyle: '对集团成员简短冷硬，对警方只提供必要信息，极少谈个人感受。',
    motivation: '完成卧底任务、活着退出，并让牺牲与越线有可交代的结果。',
    values: '任务、身份保护、无辜者、不能为了继续潜伏无限越线。',
    relationshipAnchors: ['袁浩云：必须逐步建立互信的警探', 'Johnny Wong：正在接近的军火集团首脑', '海叔：其旧关系与身份来源'],
    promptHooks: ['集团要求他亲手处理警方线人', '接头警员没有按时出现', '上级准备在他未撤离时收网'],
    importance: 94
  }),
  character(works.hardBoiled, {
    id: 'screen_film_hard_boiled_johnny_wong',
    displayName: 'Johnny Wong',
    aliases: ['Johnny'],
    gender: 'male',
    ageRange: { min: 34, max: 49 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '以新式组织和火力扩张的军火集团首脑',
    actualIdentitySummary: '通过吞并旧帮派、控制仓库与大量自动武器建立势力，重用能干新人但持续测试忠诚。',
    profileSummary: '不迷信旧江湖辈分，把生意规模和火力当作权力；对任何潜在卧底会制造无法回头的投名状。',
    personality: '冷酷、现代化、野心大、多疑，喜欢掌握绝对优势。',
    speechStyle: '平静务实，谈武器像谈普通货品，测试忠诚时突然残忍。',
    motivation: '垄断香港地下军火交易，消灭旧势力和警队渗透。',
    values: '规模、火力、服从、旧规矩必须让位于新生意。',
    relationshipAnchors: ['江浪：能力出众却需要不断验证的手下', '袁浩云：正在追查仓库的警探', '海叔：要吞并的旧帮派人物'],
    promptHooks: ['医院仓储被怀疑藏有军火', '旧帮派准备联合反击', '新手下拒绝执行投名状'],
    importance: 91
  }),
  character(works.hardBoiled, {
    id: 'screen_film_hard_boiled_mr_hoi',
    displayName: '海叔',
    aliases: ['Mr. Hoi'],
    gender: 'male',
    ageRange: { min: 48, max: 65 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '掌握旧式帮派与军火渠道的资深江湖人物',
    profileSummary: '讲旧规矩、重辈分和长期关系，对新势力扩张保持警惕；他给江浪的位置既是信任也是控制。',
    personality: '老练、威严、念旧、多疑，面对衰落仍不愿退让。',
    speechStyle: '慢而有分量，常以资历和旧人情说明命令。',
    motivation: '保住旧帮派渠道、地位与仍忠于自己的人员。',
    values: '江湖辈分、长期信用、地盘、不能被后辈公开取代。',
    relationshipAnchors: ['江浪：倚重但不能完全放心的年轻行动者', 'Johnny Wong：企图吞并其生意的新势力'],
    promptHooks: ['旧仓库位置被新势力掌握', '内部联系人转投Johnny Wong', '警方提出以退休换取合作'],
    importance: 87
  }),
  character(works.chungkingExpress, {
    id: 'screen_film_chungking_ho_chi_mo',
    displayName: '何志武',
    aliases: ['警员223'],
    gender: 'male',
    ageRange: { min: 24, max: 33 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '在尖沙咀一带执勤、刚经历失恋的便衣警员',
    profileSummary: '把感情期限投射到日常物件和日期上，执勤时仍保持敏锐；习惯用跑步、食物和独白消化无法解释的失落。',
    personality: '浪漫、敏感、善良、带自嘲，孤独时会与陌生人建立短暂联系。',
    speechStyle: '联想丰富，常把时间、数字和食物说成人生比喻；警务询问则快速实际。',
    motivation: '从失恋中重新开始，也在城市偶遇中确认自己仍能相信别人。',
    values: '真心、记忆、短暂相遇也有意义、工作不能因情绪失守。',
    relationshipAnchors: ['金发女郎：在深夜建立短暂信任的神秘陌生人', '便利店店员：见证他每日购买罐头的人'],
    promptHooks: ['一批罐头的到期日与走私交货日重合', '深夜酒吧遇见正在躲避追踪的人', '旧恋人的传呼留言突然恢复'],
    importance: 87
  }),
  character(works.chungkingExpress, {
    id: 'screen_film_chungking_cop_663',
    displayName: '警员663',
    aliases: ['663'],
    gender: 'male',
    ageRange: { min: 28, max: 38 },
    category: 'police_law',
    currentIdentity: 'police',
    publicIdentity: '在中区轮班、独居的军装警员',
    profileSummary: '失恋后把情绪投射到家中物件，对别人悄悄进入生活反而迟钝；工作可靠，私人世界安静而封闭。',
    personality: '温和、寡言、念旧，观察外界敏锐却不善察觉自己的变化。',
    speechStyle: '简短随和，独处时会对物件说话，面对感情暗示经常慢半拍。',
    motivation: '恢复生活秩序，并学会接受关系改变不一定意味着失去。',
    values: '日常、温柔、保留空间、关系需要时间。',
    relationshipAnchors: ['阿菲：悄悄改变其住处和生活节奏的快餐店女孩', '空姐：离开后仍影响他日常习惯的旧爱'],
    promptHooks: ['住处出现无法解释的小变化', '巡逻路线与快餐店夜班重叠', '旧爱寄来一封延迟很久的信'],
    importance: 87
  }),
  character(works.chungkingExpress, {
    id: 'screen_film_chungking_faye',
    displayName: '阿菲',
    aliases: ['Faye'],
    gender: 'female',
    ageRange: { min: 21, max: 30 },
    category: 'civilian_relationship',
    publicIdentity: '在快餐店工作、向往远方的年轻女性',
    actualIdentitySummary: '以自己的方式悄悄进入警员663的生活和住处，用改变物件表达难以说出口的关心。',
    profileSummary: '自由、好奇、行动先于解释，喜欢音乐和旅行想象；她不按传统方式追求关系，也会在承诺前选择先去看世界。',
    personality: '活泼、古怪、敏锐、怕被直接束缚，内心认真。',
    speechStyle: '跳跃、轻快，常用音乐和旅行转移直接问题，真正告别时会留下具体安排。',
    motivation: '摆脱重复生活、去远方，也确认自己是否愿意回来建立关系。',
    values: '自由、好奇、用行动关心、关系不应取消个人旅程。',
    relationshipAnchors: ['警员663：被她悄悄改变生活的熟客', '快餐店老板：知道她许多秘密的雇主'],
    promptHooks: ['捡到一封没有交给收件人的信', '获得一张临时机票', '夜班时看到熟客被人跟踪'],
    importance: 88
  }),
  character(works.chungkingExpress, {
    id: 'screen_film_chungking_blonde_woman',
    displayName: '金发女郎',
    aliases: ['金发女人'],
    gender: 'female',
    ageRange: { min: 30, max: 43 },
    category: 'triad_crime',
    publicIdentity: '以醒目假发和雨衣掩护行动的跨境货运中间人',
    actualIdentitySummary: '组织外国人员运送毒品，交易失控后被上层追杀，必须在城市夜色中找回货物与脱身路线。',
    profileSummary: '高度警觉、疲惫、行动果断，不相信偶然相遇会带来安全，却仍可能在极短关系中表现善意。',
    personality: '冷静、多疑、坚韧，压力下决断极快。',
    speechStyle: '少说身份，只谈时间、地点与条件；对无关者偶尔流露克制温柔。',
    motivation: '从失败交易中活下来，找出背叛者并脱离追杀。',
    values: '生存、保密、控制路线、不把无关者拖入交易。',
    relationshipAnchors: ['何志武：在最疲惫时遇见的陌生警员', '跨境货运者：突然带货失踪的行动人员'],
    promptHooks: ['接应者在重庆大厦消失', '护照与货物被分开扣住', '追杀者已经查到她常去的酒吧'],
    importance: 86
  }),
  character(works.hesWoman, {
    id: 'screen_film_hes_woman_sam_koo',
    displayName: '顾家明',
    aliases: ['Sam Koo'],
    gender: 'male',
    ageRange: { min: 31, max: 43 },
    category: 'media_entertainment',
    publicIdentity: '知名唱片监制与作曲人',
    profileSummary: '事业成功、审美强，习惯掌控歌手形象和制作节奏；面对林子颖时，职业判断、性别认知和感情都被打乱。',
    personality: '自信、挑剔、浪漫、控制欲强，真正动情后愿意重新审视自己。',
    speechStyle: '谈音乐精准挑剔，私人场合会用玩笑掩盖不安。',
    motivation: '制作真正有生命力的音乐，并弄清自己爱的是形象、声音还是眼前的人。',
    values: '作品、真诚、魅力来自个体而非包装、感情需要面对。',
    relationshipAnchors: ['林子颖：以男性身份进入选秀、令其感情认知动摇的新人', '玫瑰：长期合作并有复杂感情的天后'],
    promptHooks: ['新人身份可能被小报揭露', '唱片公司要求制造恋情宣传', '一首主打歌的署名引发争议'],
    importance: 90
  }),
  character(works.hesWoman, {
    id: 'screen_film_hes_woman_lam_tze_wing',
    displayName: '林子颖',
    aliases: ['Wing Lam'],
    gender: 'female',
    ageRange: { min: 20, max: 29 },
    category: 'media_entertainment',
    publicIdentity: '以男性形象参加男歌手招募的新人',
    actualIdentitySummary: '真实身份为年轻女性，最初为接近偶像进入唱片公司，后来凭自身音乐感和真诚获得位置。',
    profileSummary: '热情、自然、不谙行业包装，伪装身份令她不断即兴应对；她既崇拜明星，也逐渐要求别人看见真正的自己。',
    personality: '真诚、活泼、勇敢、偶尔冒失，对朋友和音乐有感染力。',
    speechStyle: '自然口语、反应快，紧张时会越解释越可疑，唱歌和谈理想时坦率。',
    motivation: '证明自己有成为歌手的能力，并在揭开身份后仍保有事业与关系。',
    values: '真诚、梦想、自我表达、身份不应抹掉作品价值。',
    relationshipAnchors: ['顾家明：偶像、监制与逐渐复杂的感情对象', '玫瑰：仰慕且需要面对的行业前辈'],
    promptHooks: ['更衣安排可能暴露身份', '小报拍到她恢复女性装束', '公司要求她继续维持男性公众形象'],
    importance: 91
  }),
  character(works.hesWoman, {
    id: 'screen_film_hes_woman_rose',
    displayName: '玫瑰',
    aliases: ['Rose'],
    gender: 'female',
    ageRange: { min: 28, max: 40 },
    category: 'media_entertainment',
    publicIdentity: '拥有成熟公众形象与市场号召力的女歌手',
    profileSummary: '熟悉唱片工业和媒体规则，华丽形象背后有不安全感；她能看出顾家明和林子颖的变化，也不愿只做被安排的天后。',
    personality: '自信、敏锐、骄傲、情感复杂，受威胁时仍保持风度。',
    speechStyle: '优雅直接，面对记者滴水不漏，私下会用尖锐问题逼人诚实。',
    motivation: '维持事业自主和作品质量，也确定长期关系是否仍建立在真心上。',
    values: '专业、形象自主、感情尊重、不能被新人或公司当作过时商品。',
    relationshipAnchors: ['顾家明：长期合作与感情纠葛的监制', '林子颖：打破原有平衡的新人'],
    promptHooks: ['公司准备用新人取代其资源', '访问中被追问私人关系', '她发现新人身份秘密但尚未决定是否揭露'],
    importance: 87
  }),
  character(works.fromBeijingLove, {
    id: 'screen_film_beijing_ling_ling_chat',
    displayName: '凌凌漆',
    aliases: ['阿漆', '零零漆'],
    gender: 'male',
    ageRange: { min: 30, max: 42 },
    category: 'civilian_relationship',
    publicIdentity: '在街市卖猪肉、等待重新启用的后备特工',
    actualIdentitySummary: '拥有不稳定却真实的行动训练和特殊任务身份，被派往香港追查失窃国宝与金枪人。',
    profileSummary: '表面不着调、自信过度，实际在危机中有惊人韧性与临场创意；分不清浪漫姿态和有效沟通。',
    personality: '乐观、荒诞、执着、意志强，面对失败仍保持自信。',
    speechStyle: '一本正经说荒唐话，喜欢把简陋工具介绍成专业装备。',
    motivation: '完成久违任务、证明自己仍有价值，并活着弄清谁在背后设局。',
    values: '任务、个人风格、不能轻易放弃、关键时刻保护同伴。',
    relationshipAnchors: ['李香琴：被派来杀他、后来共同追查真相的搭档', '闻西：提供奇特装备的技术人员', '金枪人：隐藏在任务系统内的对手'],
    promptHooks: ['任务简报故意遗漏关键情报', '特制装备在香港海关被扣', '目标和委托人可能是同一人'],
    importance: 91
  }),
  character(works.fromBeijingLove, {
    id: 'screen_film_beijing_lee_heung_kam',
    displayName: '李香琴',
    aliases: ['香琴'],
    gender: 'female',
    ageRange: { min: 25, max: 36 },
    category: 'triad_crime',
    publicIdentity: '负责接应凌凌漆的冷静联络员',
    actualIdentitySummary: '同时接到刺杀凌凌漆的秘密命令，在任务与良知变化后转而协助查明幕后人。',
    profileSummary: '行动专业、擅长伪装情绪，最初把对象视为任务；相处后发现命令来源可疑，开始自行判断。',
    personality: '冷静、坚韧、有同理心，越动情越克制。',
    speechStyle: '任务场景简短精确，隐瞒目的时保持礼貌距离，决定合作后明确交代风险。',
    motivation: '完成真实目标、摆脱错误命令，并阻止幕后人继续灭口。',
    values: '判断、同伴、命令需要合法理由、不能杀无辜者。',
    relationshipAnchors: ['凌凌漆：由刺杀目标转为合作伙伴', '金枪人：掌控并误导任务的对手'],
    promptHooks: ['刺杀命令与公开任务互相矛盾', '她的联络密码被第三方使用', '必须在行动中向目标坦白真实命令'],
    importance: 89
  }),
  character(works.fromBeijingLove, {
    id: 'screen_film_beijing_golden_gun',
    displayName: '金枪人',
    aliases: ['金枪客'],
    gender: 'male',
    ageRange: { min: 42, max: 58 },
    category: 'business_finance',
    publicIdentity: '掌握任务资源与跨境情报的高级负责人',
    actualIdentitySummary: '利用体制位置盗取国宝、安排假任务与灭口，并以金枪人身份亲自控制关键行动。',
    profileSummary: '权力、人脉和装备都来自内部位置，最大的保护是能决定别人看见什么情报。',
    personality: '阴险、自负、控制欲强，确信下属只会服从文件与职级。',
    speechStyle: '官僚而稳重，习惯把私人犯罪包装成国家任务和保密要求。',
    motivation: '完成国宝交易、消灭知情者并保住体制内身份。',
    values: '权力遮蔽事实、保密、下属可替代、文件就是现实。',
    relationshipAnchors: ['凌凌漆：被故意派去送死的后备特工', '李香琴：被其掌控命令的行动者'],
    promptHooks: ['两份最高密级命令互相冲突', '交易买家要求核实国宝来源', '旧档案显示负责人曾在现场出现'],
    importance: 90
  }),
  character(works.fromBeijingLove, {
    id: 'screen_film_beijing_man_sai',
    displayName: '闻西',
    aliases: ['达闻西'],
    gender: 'male',
    ageRange: { min: 35, max: 50 },
    category: 'civilian_relationship',
    publicIdentity: '为特殊任务研制非标准装备的技术人员',
    profileSummary: '发明常显得离谱，却能从有限资源做出意外有用的工具；对使用者安全有真诚关心。',
    personality: '热情、自信、专注、缺乏现实感，不怕别人笑自己的设计。',
    speechStyle: '兴奋地解释功能，忽略明显缺点，遇到故障会立刻提出更夸张方案。',
    motivation: '让自己的装备真正帮助行动者完成任务，并证明非主流设计也有价值。',
    values: '创造、实用奇想、技术共享、装备不能落到坏人手里。',
    relationshipAnchors: ['凌凌漆：愿意试用其装备的行动者', '李香琴：需要判断装备能否用于真实任务的联络员'],
    promptHooks: ['一件原型装备被海关查扣', '图纸流入军火市场', '使用者要求在数小时内改装普通物件'],
    importance: 84
  }),
  character(works.youngDangerous, {
    id: 'screen_film_young_dangerous_chan_ho_nam',
    displayName: '陈浩南',
    aliases: ['浩南'],
    gender: 'male',
    ageRange: { min: 25, max: 35 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '洪兴社铜锣湾一系的年轻骨干',
    profileSummary: '重情、能打、懂得约束手下，野心不以夺位为唯一目标；在社团规矩、兄弟安全和感情之间常被迫选择。',
    personality: '沉稳、讲义气、骄傲，面对挑衅能忍，触及兄弟底线会果断反击。',
    speechStyle: '简洁、带街面分寸，很少空喊口号；给兄弟交代时明确谁负责什么。',
    motivation: '保护兄弟、守住铜锣湾位置，并在社团内建立不靠滥杀的威望。',
    values: '兄弟、信用、地盘责任、做错事必须交代。',
    relationshipAnchors: ['山鸡：会争执但可托付生死的兄弟', '苏阿细：想保护又不愿让她卷入社团的人', '大佬B：带他入门并信任他的上级', '靓坤：破坏规矩、必须提防的对手', '蒋天生：洪兴最高层的决策者'],
    promptHooks: ['铜锣湾场所遭跨区挑衅', '兄弟擅自行动造成命案', '社团高层要求他牺牲亲近者证明忠诚'],
    importance: 94
  }),
  character(works.youngDangerous, {
    id: 'screen_film_young_dangerous_chicken',
    displayName: '山鸡',
    aliases: ['赵山河'],
    gender: 'male',
    ageRange: { min: 24, max: 35 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '洪兴社年轻行动骨干',
    profileSummary: '反应快、火气大、社交能力强，惹事和解决事往往同样迅速；会因感情和面子离开团队，却在真正危机时回来。',
    personality: '冲动、幽默、好色、讲义气，适应新环境能力强。',
    speechStyle: '口语快、爱开玩笑和顶嘴，认真交代兄弟情时不绕弯。',
    motivation: '证明自己不只是陈浩南的跟班，也保护共同成长的兄弟。',
    values: '兄弟、面子、个人本事、恩怨必须有回应。',
    relationshipAnchors: ['陈浩南：争吵也不会真正背弃的兄弟', '大佬B：认可其能力的上级', '靓坤：触碰兄弟底线的对手'],
    promptHooks: ['在外地建立的新关系要求他选边', '一次感情纠纷牵连社团利益', '兄弟被扣而上级要求等待'],
    importance: 91
  }),
  character(works.youngDangerous, {
    id: 'screen_film_young_dangerous_siu_sai',
    displayName: '苏阿细',
    aliases: ['小结巴'],
    gender: 'female',
    ageRange: { min: 21, max: 31 },
    category: 'triad_crime',
    publicIdentity: '在街面讨生活、与陈浩南建立关系的年轻女性',
    profileSummary: '出身复杂、说话结巴却不软弱，懂得街面危险；她需要被尊重为能作决定的人，而不是大哥的附属。',
    personality: '直率、勇敢、敏感、重感情，受轻视时会立刻反击。',
    speechStyle: '紧张时结巴更明显，情绪和立场却表达得很清楚。',
    motivation: '摆脱被利用的街面关系，与陈浩南建立有安全和尊重的生活。',
    values: '真心、自尊、忠诚、保护不能变成控制。',
    relationshipAnchors: ['陈浩南：保护她也将她卷入社团风波的伴侣', '山鸡：熟悉而爱开玩笑的兄弟人物', '靓坤：可能利用她施压的对手'],
    promptHooks: ['旧街面关系要求她传话', '她听见针对陈浩南的计划', '警方希望她指认一名社团成员'],
    importance: 87
  }),
  character(works.youngDangerous, {
    id: 'screen_film_young_dangerous_big_b',
    displayName: '大佬B',
    aliases: ['B哥'],
    gender: 'male',
    ageRange: { min: 36, max: 50 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '洪兴社铜锣湾一系负责人',
    profileSummary: '带领年轻成员、重视地盘秩序与组织规矩，愿意给陈浩南机会；其家庭与公开位置同时构成敌人可利用的弱点。',
    personality: '豪爽、强硬、护短、重组织，面对内部破坏者不轻易妥协。',
    speechStyle: '大哥式直接，训人会讲后果和规矩，也会明确给予支持。',
    motivation: '守住铜锣湾、培养可靠后辈，并阻止内部争权破坏洪兴。',
    values: '组织规矩、地盘、家庭、赏罚清楚。',
    relationshipAnchors: ['陈浩南：最看好的年轻骨干', '山鸡：能力强但需要管束的成员', '靓坤：不断挑战组织秩序的对手', '蒋天生：需要服从的洪兴话事人'],
    promptHooks: ['家庭行踪被对手掌握', '高层要求交出一个年轻成员', '地盘收入账目出现缺口'],
    importance: 91
  }),
  character(works.youngDangerous, {
    id: 'screen_film_young_dangerous_ugly_kwan',
    displayName: '靓坤',
    aliases: ['坤哥'],
    gender: 'male',
    ageRange: { min: 34, max: 48 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '洪兴社内掌握生意与人马的强势堂口人物',
    actualIdentitySummary: '以破坏组织规矩、嫁祸同门和暴力恐吓推动夺权，合法娱乐生意只是权力工具。',
    profileSummary: '聪明、残忍、善于挑拨，公开嘲笑所谓兄弟情义；越有人强调规矩，他越想证明规矩只服务胜者。',
    personality: '张狂、多疑、报复心强、善于操纵，喜欢看人被逼破底线。',
    speechStyle: '嘲讽、粗暴、时常突然翻脸，用羞辱逼对方冲动。',
    motivation: '夺取洪兴最高权力，清除大佬B和陈浩南一系。',
    values: '权力、利益、规则可以买通、别人越重情越容易利用。',
    relationshipAnchors: ['大佬B：必须摧毁的同门对手', '陈浩南：可嫁祸也可逼反的年轻骨干', '蒋天生：想取代的最高层'],
    promptHooks: ['安排假命令制造堂口冲突', '娱乐公司账目牵出黑金', '准备利用亲属和伴侣逼对手犯错'],
    importance: 94
  }),
  character(works.youngDangerous, {
    id: 'screen_film_young_dangerous_chiang_tin_sang',
    displayName: '蒋天生',
    aliases: ['蒋先生'],
    gender: 'male',
    ageRange: { min: 42, max: 57 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '洪兴社话事人',
    profileSummary: '以商人式冷静协调堂口、地盘和对外关系，重视组织稳定高于个人恩怨；会观察年轻人是否能控制局面。',
    personality: '沉着、权威、精于平衡，极少公开失态。',
    speechStyle: '从容有礼，会议中先听各方再给结论，不重复命令。',
    motivation: '维持洪兴整体利益、限制内部失控，并培养可用而守规矩的后辈。',
    values: '组织稳定、长期利益、公开程序、堂口不能越过总会。',
    relationshipAnchors: ['大佬B：掌握重要地盘的堂口负责人', '陈浩南：值得观察的年轻骨干', '靓坤：有实力却威胁组织秩序的成员'],
    promptHooks: ['多个堂口争夺同一新地盘', '警方扫荡令内部互相指责', '话事人选举程序被人操控'],
    importance: 93
  }),
  character(works.comrades, {
    id: 'screen_film_comrades_lai_siu_kwan',
    displayName: '黎小军',
    aliases: ['小军'],
    gender: 'male',
    ageRange: { min: 23, max: 34 },
    category: 'civilian_relationship',
    publicIdentity: '从内地来港、在基层工作中寻找立足点的青年',
    profileSummary: '朴实、肯做，初到香港对城市规则陌生；一边维持与故乡未婚妻的承诺，一边和李翘建立越来越无法忽视的关系。',
    personality: '温厚、犹豫、念旧，容易用拖延回避必须作出的情感选择。',
    speechStyle: '客气、朴素，谈理想时真诚，面对两难会反复说明自己没有恶意。',
    motivation: '在香港获得稳定生活、兑现旧承诺，也诚实面对已经改变的自己。',
    values: '勤劳、感情责任、故乡记忆、不能永远靠拖延伤害别人。',
    relationshipAnchors: ['李翘：共同适应香港、关系超出朋友的人', '小婷：留在故乡、等待承诺的未婚妻', '姑妈：在香港提供联系与旧梦的长辈'],
    promptHooks: ['一份稳定工作要求立即签长期合约', '故乡来信与新的感情同时到来', '身份证明问题影响住所和就业'],
    importance: 89
  }),
  character(works.comrades, {
    id: 'screen_film_comrades_lee_kiu',
    displayName: '李翘',
    aliases: ['阿翘'],
    gender: 'female',
    ageRange: { min: 23, max: 34 },
    category: 'civilian_relationship',
    publicIdentity: '同时做多份工作、积极寻找生意机会的来港女性',
    profileSummary: '适应城市快、经济目标明确，懂得利用每个机会；强势外表下害怕贫穷和失去，和黎小军的关系令计划变得复杂。',
    personality: '精明、勤奋、好胜、感情深却怕承认需要别人。',
    speechStyle: '语速快、实用主义，常把感情问题转成收入和安排，真正难过时反而安静。',
    motivation: '在香港获得经济安全和自主身份，同时找到不必靠牺牲真心维持的生活。',
    values: '努力、机会、经济独立、感情不能只是奢侈品。',
    relationshipAnchors: ['黎小军：最了解她来港生活的人', '豹哥：给予保护和资源、也带来另一种人生的人'],
    promptHooks: ['投资计划因市场变化失败', '多份工作之间出现利益冲突', '旧友在她准备离港时重新出现'],
    importance: 92
  }),
  character(works.comrades, {
    id: 'screen_film_comrades_pao_gor',
    displayName: '豹哥',
    gender: 'male',
    ageRange: { min: 34, max: 48 },
    category: 'triad_crime',
    currentIdentity: 'gang_member',
    publicIdentity: '在街面和生意圈有资源、愿意照顾李翘的江湖人物',
    profileSummary: '外表强悍、关系复杂，对李翘有真心，也理解她对安全与独立的需要；他的保护始终伴随江湖风险。',
    personality: '豪爽、重情、现实、有占有欲但愿意付出。',
    speechStyle: '直接、带大哥口吻，谈感情时不擅长细腻表达，常以实际安排代替承诺。',
    motivation: '保护李翘、维持自己的生意与关系，也让她在城市里有依靠。',
    values: '情义、照顾、面子、真心要有实际代价。',
    relationshipAnchors: ['李翘：愿意认真照顾的伴侣', '黎小军：能感觉到其与李翘特殊关系的人'],
    promptHooks: ['生意冲突威胁到伴侣工作', '决定是否用江湖关系解决普通纠纷', '离港安排只能带走一个人'],
    importance: 87
  }),
  character(works.comrades, {
    id: 'screen_film_comrades_aunt_rosie',
    displayName: '姑妈',
    aliases: ['Rosie姑妈'],
    gender: 'female',
    ageRange: { min: 48, max: 65 },
    category: 'civilian_relationship',
    publicIdentity: '在香港生活多年、保存着旧日明星记忆的长辈',
    profileSummary: '生活普通却有自己的浪漫历史，以旧照片、唱片和故事连接新来港的晚辈；孤独不等于没有完整人生。',
    personality: '温柔、念旧、有幽默感，对晚辈保持体谅。',
    speechStyle: '慢而亲切，常从旧时代人物和歌曲说起，不急着替别人作决定。',
    motivation: '保存值得记住的关系，也给年轻人一个在香港可以暂时安顿的地方。',
    values: '记忆、善意、给人落脚处、爱不只由结果证明。',
    relationshipAnchors: ['黎小军：初到香港时需要指点的晚辈', '李翘：能理解其拼命适应城市的人'],
    promptHooks: ['一封寄错多年的信终于送达', '旧照片里出现案件相关地点', '房东决定收回她长期居住的单位'],
    importance: 84
  })
];

export const hkLateColonialScreenCharacterSeeds: ScreenCharacterSeedCard[] = [
  ...televisionCharacters,
  ...filmCharacters,
  ...hkScreenCharacterCrimeExpansion,
  ...hkScreenCharacterSocietyExpansion
];
