import type { CityOrganizationAnchor } from './cityPowerTypes';

export const hkLateColonialCivilianOrganizations: CityOrganizationAnchor[] = [
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_hk_supreme_court',
    displayName: '香港最高法院',
    englishName: 'Supreme Court of Hong Kong',
    disguisedNames: ['最高法院', '最高法院大楼', '高院'],
    organizationType: 'legal',
    activeYears: { from: 1844, to: 1997 },
    publicKnowledge: '香港最高级别法院，重大刑事、民事和上诉案件会把律师、警队、媒体与公众注意力集中到金钟。',
    promptSafeProfile: '最高法院只在重大案件、上诉或轰动争议中成为直接场景，不代表每宗街面案件都会进入最高层级审讯。',
    headquartersPlaceIds: ['place_supreme_court_building'],
    territoryPlaceIds: ['place_supreme_court_building'],
    relatedOrganizationIds: ['org_legal_department', 'org_hk_district_court'],
    sectorTags: ['legal', 'court', 'appeal', 'major_case'],
    influence: 88,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_hk_district_court',
    displayName: '区域法院',
    englishName: 'District Court',
    disguisedNames: ['地院', '区域法院系统', '地区法院'],
    organizationType: 'legal',
    activeYears: { from: 1953, to: 1997 },
    publicKnowledge: '处理较严重刑事案件和一定范围民事争议的法院，是普通市民、律师与警队较可能接触的审讯层级。',
    promptSafeProfile: '区域法院承接已经形成正式程序的案件，但具体提堂、保释和审讯进度仍以案件结构化事实为准。',
    headquartersPlaceIds: ['place_supreme_court_building'],
    territoryPlaceIds: ['place_central_magistracy'],
    relatedOrganizationIds: ['org_legal_department', 'org_hk_supreme_court'],
    sectorTags: ['legal', 'court', 'trial', 'civil_dispute'],
    influence: 78,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_hk_four_stock_exchanges',
    displayName: '香港证券市场（四会时期）',
    englishName: 'Hong Kong Securities Market (Four Exchanges Era)',
    disguisedNames: ['四会', '四间交易所', '香港证券交易所', '远东交易所', '金银证券交易所', '九龙证券交易所'],
    organizationType: 'finance',
    activeYears: { from: 1984, to: 1985 },
    publicKnowledge: '1986年统一交易前，香港股票买卖由香港、远东、金银与九龙四所并存，市场消息在不同交易场与经纪网络间流动。',
    promptSafeProfile: '四会时期代表分散的证券交易网络，只在股票、融资、地产、财经新闻和市场风声相关场景中进入叙事。',
    headquartersPlaceIds: ['place_exchange_square'],
    territoryPlaceIds: ['place_exchange_square', 'place_hsbc_main_building'],
    relatedOrganizationIds: ['org_hsbc', 'org_hang_seng_bank', 'org_cheung_kong_group'],
    sectorTags: ['finance', 'market', 'stocks', 'four_exchanges'],
    influence: 84,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_atv',
    displayName: '亚洲电视',
    englishName: 'Asia Television Limited',
    disguisedNames: ['亚视', 'ATV', '丽的转名后的电视台'],
    organizationType: 'media',
    activeYears: { from: 1982, to: 1997 },
    publicKnowledge: '香港主要免费电视台之一，新闻、剧集、艺员与广告业务让它持续进入市民日常生活。',
    promptSafeProfile: '亚视连接新闻部、制作人员、艺员和广告客户，适合作为传媒竞争、娱乐消息与公众舆论的直接机构。',
    headquartersPlaceIds: ['place_atv_broadcast_drive'],
    territoryPlaceIds: ['place_atv_broadcast_drive', 'place_broadcast_drive'],
    relatedOrganizationIds: ['org_tvb', 'org_commercial_radio', 'org_capital_artists'],
    sectorTags: ['television', 'media', 'news', 'entertainment'],
    influence: 84,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_commercial_radio',
    displayName: '香港商业电台',
    englishName: 'Hong Kong Commercial Broadcasting Company Limited',
    disguisedNames: ['商业电台', '商台', 'CRHK'],
    organizationType: 'media',
    activeYears: { from: 1959, to: 1997 },
    publicKnowledge: '商业广播机构，新闻、时事、音乐节目和唱片宣传让声音迅速进入全港听众。',
    promptSafeProfile: '商业电台连接主持、记者、唱片公司和广告客户，可放大新闻线索、娱乐风声与公众情绪。',
    headquartersPlaceIds: ['place_commercial_radio_broadcast_drive'],
    territoryPlaceIds: ['place_commercial_radio_broadcast_drive', 'place_broadcast_drive'],
    relatedOrganizationIds: ['org_rthk', 'org_tvb', 'org_atv', 'org_polygram_hk'],
    sectorTags: ['radio', 'media', 'music', 'news'],
    influence: 80,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_cinema_city',
    displayName: '新艺城影业',
    englishName: 'Cinema City Company Limited',
    disguisedNames: ['新艺城', 'Cinema City', '新艺城电影'],
    organizationType: 'entertainment',
    activeYears: { from: 1980, to: 1991 },
    publicKnowledge: '1980年代重要商业电影公司，制作、发行、明星与投资关系在影坛竞争中十分活跃。',
    promptSafeProfile: '新艺城适合进入电影制作、明星档期、票房竞争与幕后投资剧情，但不自动与社团或犯罪事实绑定。',
    headquartersPlaceIds: ['place_golden_harvest_studio'],
    territoryPlaceIds: ['place_golden_harvest_studio', 'place_broadcast_drive'],
    relatedOrganizationIds: ['org_golden_princess', 'org_golden_harvest', 'org_shaw_brothers'],
    sectorTags: ['film', 'production', 'distribution', 'entertainment'],
    influence: 82,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_db_films',
    displayName: '德宝电影公司',
    englishName: 'D & B Films Company Limited',
    disguisedNames: ['德宝', 'D&B Films', '德宝影业'],
    organizationType: 'entertainment',
    activeYears: { from: 1984, to: 1992 },
    publicKnowledge: '1980年代中后期活跃的电影制作公司，连接演员、导演、幕后班底与院线发行。',
    promptSafeProfile: '德宝提供电影制作、合约、融资与片场人际入口，成立前不得提前出现。',
    headquartersPlaceIds: ['place_golden_harvest_studio'],
    territoryPlaceIds: ['place_broadcast_drive', 'place_golden_harvest_studio'],
    relatedOrganizationIds: ['org_golden_princess', 'org_golden_harvest'],
    sectorTags: ['film', 'production', 'entertainment'],
    influence: 74,
    defaultVisibility: 'public',
    sourceConfidence: 'medium'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_wins_entertainment',
    displayName: '永盛电影公司',
    englishName: "Win's Movie Production & I/E Co. Ltd.",
    disguisedNames: ['永盛', '永盛影业', "Win's"],
    organizationType: 'entertainment',
    activeYears: { from: 1987, to: 1997 },
    publicKnowledge: '1980年代末开始活跃的电影制作和发行公司，资金、明星、发行与江湖传闻常在外围交错。',
    promptSafeProfile: '永盛只能在成立后出现；真实犯罪或社团关系不得由机构名称自动推定，必须由剧情事实支持。',
    headquartersPlaceIds: ['place_broadcast_drive'],
    territoryPlaceIds: ['place_broadcast_drive', 'place_golden_harvest_studio'],
    relatedOrganizationIds: ['org_golden_princess', 'org_cinema_city'],
    sectorTags: ['film', 'production', 'distribution', 'entertainment'],
    influence: 78,
    defaultVisibility: 'public',
    sourceConfidence: 'medium'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_golden_princess',
    displayName: '金公主娱乐',
    englishName: 'Golden Princess Entertainment',
    disguisedNames: ['金公主', '金公主院线', 'Golden Princess'],
    organizationType: 'entertainment',
    activeYears: { from: 1980, to: 1997 },
    publicKnowledge: '1980年代重要电影发行与院线网络，片源、档期、票房和投资关系影响多家电影公司。',
    promptSafeProfile: '金公主适合承载发行、院线竞争、票房与电影投资事件，不把院线商业纠纷自动写成犯罪。',
    headquartersPlaceIds: ['place_harbour_city'],
    territoryPlaceIds: ['place_harbour_city', 'place_causeway_bay_shopping_streets'],
    relatedOrganizationIds: ['org_cinema_city', 'org_db_films', 'org_wins_entertainment'],
    sectorTags: ['cinema', 'distribution', 'film', 'box_office'],
    influence: 80,
    defaultVisibility: 'public',
    sourceConfidence: 'medium'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_polygram_hk',
    displayName: '宝丽金唱片',
    englishName: 'PolyGram Records Hong Kong',
    disguisedNames: ['宝丽金', 'PolyGram', '宝记'],
    organizationType: 'entertainment',
    activeYears: { from: 1970, to: 1997 },
    publicKnowledge: '香港主要唱片公司之一，歌手合约、录音、宣传、版权和海外发行构成完整行业网络。',
    promptSafeProfile: '宝丽金可进入歌手签约、录音、宣传、销量和版权争议，相关现实人物言行仍由当局剧情事实决定。',
    headquartersPlaceIds: ['place_broadcast_drive'],
    territoryPlaceIds: ['place_broadcast_drive', 'place_commercial_radio_broadcast_drive'],
    relatedOrganizationIds: ['org_commercial_radio', 'org_capital_artists', 'org_emi_hk'],
    sectorTags: ['music', 'record_label', 'copyright', 'entertainment'],
    influence: 82,
    defaultVisibility: 'public',
    sourceConfidence: 'medium'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_capital_artists',
    displayName: '华星唱片',
    englishName: 'Capital Artists Limited',
    disguisedNames: ['华星', 'Capital Artists', '华星娱乐'],
    organizationType: 'entertainment',
    activeYears: { from: 1971, to: 1997 },
    publicKnowledge: '与电视娱乐网络关系密切的唱片公司，连接歌手、节目、宣传和艺员发展。',
    promptSafeProfile: '华星适合投影音乐节目、艺员合约与唱片宣传，不自动把电视台与唱片公司的关系扩大成全知内幕。',
    headquartersPlaceIds: ['place_tv_city_clear_water_bay'],
    territoryPlaceIds: ['place_tv_city_clear_water_bay', 'place_broadcast_drive'],
    relatedOrganizationIds: ['org_tvb', 'org_atv', 'org_polygram_hk'],
    sectorTags: ['music', 'record_label', 'television', 'entertainment'],
    influence: 78,
    defaultVisibility: 'public',
    sourceConfidence: 'medium'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_emi_hk',
    displayName: 'EMI 香港',
    englishName: 'EMI (Hong Kong) Limited',
    disguisedNames: ['EMI', '百代唱片香港', 'EMI唱片'],
    organizationType: 'entertainment',
    activeYears: { from: 1960, to: 1997 },
    publicKnowledge: '国际唱片集团在香港的业务网络，连接本地歌手、录音制作、版权与海外发行。',
    promptSafeProfile: 'EMI香港提供跨地发行、唱片合约和国际市场入口，具体签约与艺人关系不得凭空断言。',
    headquartersPlaceIds: ['place_broadcast_drive'],
    territoryPlaceIds: ['place_broadcast_drive', 'place_commercial_radio_broadcast_drive'],
    relatedOrganizationIds: ['org_polygram_hk', 'org_commercial_radio'],
    sectorTags: ['music', 'record_label', 'international', 'copyright'],
    influence: 76,
    defaultVisibility: 'public',
    sourceConfidence: 'medium'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_royal_hk_jockey_club',
    displayName: '英皇御准香港赛马会',
    englishName: 'The Royal Hong Kong Jockey Club',
    disguisedNames: ['马会', '皇家香港赛马会', '跑马地马会'],
    organizationType: 'entertainment',
    activeYears: { from: 1959, to: 1997 },
    publicKnowledge: '香港赛马与合法博彩的核心机构，也通过会员、慈善和大型公众活动连接商界与社会名流。',
    promptSafeProfile: '马会可进入赛马、投注、会员社交、公众娱乐和慈善名望剧情，不代表所有马圈人物都参与非法活动。',
    headquartersPlaceIds: ['place_happy_valley_racecourse'],
    territoryPlaceIds: ['place_happy_valley_racecourse'],
    relatedOrganizationIds: ['org_hsbc', 'org_government_house'],
    sectorTags: ['horse_racing', 'betting', 'entertainment', 'charity'],
    influence: 88,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_mtrc',
    displayName: '地下铁路公司',
    englishName: 'Mass Transit Railway Corporation',
    disguisedNames: ['地铁公司', '地下铁', 'MTRC'],
    organizationType: 'transport',
    activeYears: { from: 1975, to: 1997 },
    publicKnowledge: '负责兴建和营运地下铁路的公营机构，车站、通勤、工程与物业把它带入大量市民生活。',
    promptSafeProfile: '地铁公司适合进入通勤、车站事件、失窃、工程和运输就业剧情，具体线路以当年已经开通的地点事实为准。',
    headquartersPlaceIds: ['place_mtr_admiralty_station'],
    territoryPlaceIds: ['place_mtr_central_station', 'place_mtr_admiralty_station', 'place_mtr_kowloon_tong_station', 'place_mtr_tsuen_wan_station'],
    relatedOrganizationIds: ['org_kcrc', 'org_kmb', 'org_star_ferry'],
    sectorTags: ['transport', 'rail', 'commute', 'infrastructure'],
    influence: 88,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_kcrc',
    displayName: '九广铁路公司',
    englishName: 'Kowloon-Canton Railway Corporation',
    disguisedNames: ['九铁公司', '九广铁路', 'KCRC'],
    organizationType: 'transport',
    activeYears: { from: 1982, to: 1997 },
    publicKnowledge: '经营九广铁路的公营公司，连接九龙、新界和边境客货运输。',
    promptSafeProfile: '九铁可进入通勤、货运、罗湖边境和铁路岗位剧情，线路扩张必须服从当年时间窗口。',
    headquartersPlaceIds: ['place_hung_hom_station'],
    territoryPlaceIds: ['place_hung_hom_station', 'place_lo_wu_station'],
    relatedOrganizationIds: ['org_mtrc', 'org_kmb'],
    sectorTags: ['transport', 'rail', 'border', 'freight'],
    influence: 84,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_kmb',
    displayName: '九龙巴士',
    englishName: 'The Kowloon Motor Bus Company (1933) Limited',
    disguisedNames: ['九巴', '九龙巴士公司', 'KMB'],
    organizationType: 'transport',
    activeYears: { from: 1933, to: 1997 },
    publicKnowledge: '九龙和新界主要专营巴士公司，司机、车厂、路线与乘客纠纷都与市民日常相连。',
    promptSafeProfile: '九巴可进入通勤、交通意外、失物、司机与车厂岗位剧情，不需要模拟完整路线表。',
    headquartersPlaceIds: ['place_mtr_kowloon_tong_station'],
    territoryPlaceIds: ['place_fa_yuen_street', 'place_mtr_tsuen_wan_station', 'place_hung_hom_station'],
    relatedOrganizationIds: ['org_mtrc', 'org_kcrc', 'org_star_ferry'],
    sectorTags: ['transport', 'bus', 'commute', 'road'],
    influence: 80,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_star_ferry',
    displayName: '天星小轮',
    englishName: 'The Star Ferry Company, Limited',
    disguisedNames: ['天星轮', '小轮公司', 'Star Ferry'],
    organizationType: 'transport',
    activeYears: { from: 1898, to: 1997 },
    publicKnowledge: '往来维港两岸的标志性渡轮公司，码头、船员和通勤乘客形成稳定公共接触面。',
    promptSafeProfile: '天星小轮适合进入码头、维港通勤、失物、目击与船员岗位剧情，不需要模拟全部航班。',
    headquartersPlaceIds: ['place_central_star_ferry_pier'],
    territoryPlaceIds: ['place_central_star_ferry_pier', 'place_tsim_sha_tsui_star_ferry_pier'],
    relatedOrganizationIds: ['org_mtrc', 'org_kmb'],
    sectorTags: ['transport', 'ferry', 'harbour', 'commute'],
    influence: 76,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_queen_elizabeth_hospital',
    displayName: '伊利沙伯医院',
    englishName: 'Queen Elizabeth Hospital',
    disguisedNames: ['伊院', 'QEH', '伊利沙伯'],
    organizationType: 'public_service',
    activeYears: { from: 1963, to: 1997 },
    publicKnowledge: '九龙大型公立医院，急症、伤者、医护人员和警方查询使它成为高频公共场所。',
    promptSafeProfile: '伊利沙伯医院可承接治疗、伤者、医护职业和案件证人剧情，医疗结论必须以结构化事实或当回合明确生成结果为准。',
    headquartersPlaceIds: ['place_queen_elizabeth_hospital'],
    territoryPlaceIds: ['place_queen_elizabeth_hospital'],
    relatedOrganizationIds: ['org_kwong_wah_hospital', 'org_hk_police'],
    sectorTags: ['hospital', 'medical', 'public_service', 'emergency'],
    influence: 84,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_kwong_wah_hospital',
    displayName: '广华医院',
    englishName: 'Kwong Wah Hospital',
    disguisedNames: ['广华', '广华医院急症室'],
    organizationType: 'public_service',
    activeYears: { from: 1911, to: 1997 },
    publicKnowledge: '油麻地与旺角一带的重要医院，医护、病人、家属和街区案件常在此交汇。',
    promptSafeProfile: '广华医院可承接九龙旧区的医疗、伤者与医护职业剧情，不自动公开病人私隐或未确认诊断。',
    headquartersPlaceIds: ['place_kwong_wah_hospital'],
    territoryPlaceIds: ['place_kwong_wah_hospital'],
    relatedOrganizationIds: ['org_queen_elizabeth_hospital', 'org_hk_police'],
    sectorTags: ['hospital', 'medical', 'public_service', 'community'],
    influence: 80,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_wing_on_department_store',
    displayName: '永安百货',
    englishName: 'Wing On Department Stores',
    disguisedNames: ['永安公司', '永安百货公司', 'Wing On'],
    organizationType: 'business',
    activeYears: { from: 1907, to: 1997 },
    publicKnowledge: '老牌百货企业，职员、顾客、现金、货品和供应商让它成为稳定的消费与就业场所。',
    promptSafeProfile: '永安百货可进入零售工作、失窃、顾客纠纷、人事与供应链剧情，不需要建立完整楼层经营系统。',
    headquartersPlaceIds: ['place_causeway_bay_shopping_streets'],
    territoryPlaceIds: ['place_causeway_bay_shopping_streets', 'place_harbour_city'],
    relatedOrganizationIds: ['org_sincere_department_store', 'org_dairy_farm'],
    sectorTags: ['retail', 'department_store', 'employment', 'consumer'],
    influence: 74,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_sincere_department_store',
    displayName: '先施百货',
    englishName: 'The Sincere Company, Limited',
    disguisedNames: ['先施公司', '先施百货公司', 'Sincere'],
    organizationType: 'business',
    activeYears: { from: 1900, to: 1997 },
    publicKnowledge: '香港老牌百货公司，零售岗位、顾客、供货商与商场现金流形成直接市民接触面。',
    promptSafeProfile: '先施百货可进入零售工作、消费、人事、失窃与商业纠纷，不因为老字号地位自动拥有隐藏政治影响。',
    headquartersPlaceIds: ['place_causeway_bay_shopping_streets'],
    territoryPlaceIds: ['place_causeway_bay_shopping_streets', 'place_fa_yuen_street'],
    relatedOrganizationIds: ['org_wing_on_department_store', 'org_dairy_farm'],
    sectorTags: ['retail', 'department_store', 'employment', 'consumer'],
    influence: 72,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_dairy_farm',
    displayName: '牛奶公司',
    englishName: 'The Dairy Farm Company, Limited',
    disguisedNames: ['牛奶公司集团', 'Dairy Farm', '食品零售集团'],
    organizationType: 'business',
    activeYears: { from: 1886, to: 1997 },
    publicKnowledge: '食品、零售与供应链企业，门店、货仓、供应商和日常消费让它贴近市民生活。',
    promptSafeProfile: '牛奶公司可进入食品零售、门店就业、仓储和供货纠纷，不需要模拟集团全部品牌和财务。',
    headquartersPlaceIds: ['place_admiralty_commercial_district'],
    territoryPlaceIds: ['place_causeway_bay_shopping_streets', 'place_harbour_city'],
    relatedOrganizationIds: ['org_wing_on_department_store', 'org_sincere_department_store', 'org_maxims'],
    sectorTags: ['retail', 'food', 'supply_chain', 'employment'],
    influence: 76,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_maxims',
    displayName: '美心集团',
    englishName: "Maxim's Caterers Limited",
    disguisedNames: ['美心', '美心餐饮', "Maxim's"],
    organizationType: 'business',
    activeYears: { from: 1956, to: 1997 },
    publicKnowledge: '本地餐饮集团，酒楼、餐厅、宴会、员工与供应商形成广泛的市民和商界接触面。',
    promptSafeProfile: '美心可进入餐饮就业、宴会、顾客、人事和供货剧情，不扩建餐厅经营模拟。',
    headquartersPlaceIds: ['place_admiralty_commercial_district'],
    territoryPlaceIds: ['place_harbour_city', 'place_causeway_bay_shopping_streets'],
    relatedOrganizationIds: ['org_dairy_farm', 'org_royal_hk_jockey_club'],
    sectorTags: ['catering', 'restaurant', 'banquet', 'employment'],
    influence: 76,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_queen_mary_hospital',
    displayName: '玛丽医院',
    englishName: 'Queen Mary Hospital',
    disguisedNames: ['玛丽医院', '玛丽', 'QMH'],
    organizationType: 'public_service',
    activeYears: { from: 1937, to: 1997 },
    publicKnowledge: '港岛主要公立及教学医院，连接大学医学院、急症服务、专科治疗、病人家属与警方查询。',
    promptSafeProfile: '玛丽医院可承接医护职业、敏感病例、家属压力和案件伤者剧情；病历、诊断和内部权限必须服从当前结构化事实。',
    headquartersPlaceIds: ['place_queen_mary_hospital'],
    territoryPlaceIds: ['place_queen_mary_hospital'],
    relatedOrganizationIds: ['org_hku', 'org_queen_elizabeth_hospital'],
    sectorTags: ['hospital', 'medical', 'teaching_hospital', 'public_service'],
    influence: 86,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_prince_of_wales_hospital',
    displayName: '威尔斯亲王医院',
    englishName: 'Prince of Wales Hospital',
    disguisedNames: ['威院', '威尔斯医院', 'PWH'],
    organizationType: 'public_service',
    activeYears: { from: 1984, to: 1997 },
    publicKnowledge: '服务沙田与新界东的大型教学医院，急症、病房、大学医疗教学与新市镇人口压力在此交汇。',
    promptSafeProfile: '威尔斯亲王医院只可在1984年后出现；适合承接新界东医护职业、急症和家庭照护压力。',
    headquartersPlaceIds: ['place_prince_of_wales_hospital'],
    territoryPlaceIds: ['place_prince_of_wales_hospital'],
    relatedOrganizationIds: ['org_cuhk', 'org_queen_elizabeth_hospital'],
    sectorTags: ['hospital', 'medical', 'teaching_hospital', 'new_territories'],
    influence: 82,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_hong_kong_sanatorium',
    displayName: '养和医院',
    englishName: 'Hong Kong Sanatorium & Hospital',
    disguisedNames: ['养和', '跑马地养和', 'HKSH'],
    organizationType: 'public_service',
    activeYears: { from: 1922, to: 1997 },
    publicKnowledge: '港岛历史悠久的私营医院，医疗专业、付费服务、病人私隐与社会名流关系构成独特职业环境。',
    promptSafeProfile: '养和医院可进入私营医疗、病人服务和敏感私隐剧情，但不得自动公开名人病历或把付费医疗写成无限资源。',
    headquartersPlaceIds: ['place_hong_kong_sanatorium'],
    territoryPlaceIds: ['place_hong_kong_sanatorium'],
    relatedOrganizationIds: ['org_queen_mary_hospital'],
    sectorTags: ['hospital', 'medical', 'private_healthcare'],
    influence: 78,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_tung_wah_group',
    displayName: '东华三院',
    englishName: 'Tung Wah Group of Hospitals',
    disguisedNames: ['东华', '东华医院网络', 'TWGHs'],
    organizationType: 'public_service',
    activeYears: { from: 1870, to: 1997 },
    publicKnowledge: '历史悠久的慈善与社会服务机构，涵盖医疗、教育、安老、家庭与社区服务。',
    promptSafeProfile: '东华三院可连接医院、学校、社会服务和社区关系；具体资源、个案和服务安排仍须由当前事实建立。',
    headquartersPlaceIds: ['place_tung_wah_hospital'],
    territoryPlaceIds: ['place_tung_wah_hospital', 'place_kwong_wah_hospital'],
    relatedOrganizationIds: ['org_kwong_wah_hospital', 'org_po_leung_kuk', 'org_caritas_hk'],
    sectorTags: ['charity', 'medical', 'education', 'social_service'],
    influence: 84,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_hku',
    displayName: '香港大学',
    englishName: 'The University of Hong Kong',
    disguisedNames: ['港大', '香港大学本部', 'HKU'],
    organizationType: 'public_service',
    activeYears: { from: 1911, to: 1997 },
    publicKnowledge: '香港历史最悠久的大学，教学、研究、学生事务、医疗与专业网络连接政府、医院和社会。',
    promptSafeProfile: '香港大学适合进入教育、研究、行政、学生与专业职业剧情，不自动赋予玩家学术权威或政府权限。',
    headquartersPlaceIds: ['place_university_of_hong_kong'],
    territoryPlaceIds: ['place_university_of_hong_kong'],
    relatedOrganizationIds: ['org_queen_mary_hospital', 'org_cuhk'],
    sectorTags: ['education', 'university', 'research', 'medical_training'],
    influence: 86,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_cuhk',
    displayName: '香港中文大学',
    englishName: 'The Chinese University of Hong Kong',
    disguisedNames: ['中大', '沙田中文大学', 'CUHK'],
    organizationType: 'public_service',
    activeYears: { from: 1963, to: 1997 },
    publicKnowledge: '位于沙田的综合大学，由书院传统发展而来，连接教学、研究、新市镇与医疗专业网络。',
    promptSafeProfile: '香港中文大学可进入教学、行政、学生、研究及新界社会关系剧情；院系和人物权限必须由当前事实支持。',
    headquartersPlaceIds: ['place_chinese_university_of_hong_kong'],
    territoryPlaceIds: ['place_chinese_university_of_hong_kong'],
    relatedOrganizationIds: ['org_prince_of_wales_hospital', 'org_hku'],
    sectorTags: ['education', 'university', 'research', 'new_territories'],
    influence: 84,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_clp',
    displayName: '中华电力',
    englishName: 'China Light & Power Company',
    disguisedNames: ['中电', '中华电力公司', 'CLP'],
    organizationType: 'business',
    activeYears: { from: 1901, to: 1997 },
    publicKnowledge: '九龙及新界主要电力企业，供电、工程、维修、客户服务和大型设施影响大量市民生活。',
    promptSafeProfile: '中华电力可进入公用事业岗位、维修、停电和客户服务剧情，不需要模拟完整电网或发电调度。',
    headquartersPlaceIds: ['place_kwun_tong_industrial_area'],
    territoryPlaceIds: ['place_kwun_tong_industrial_area', 'place_tsuen_wan_industrial_area'],
    relatedOrganizationIds: ['org_hk_electric', 'org_towngas'],
    sectorTags: ['utility', 'electricity', 'engineering', 'customer_service'],
    influence: 88,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_hk_electric',
    displayName: '香港电灯',
    englishName: 'The Hongkong Electric Company',
    disguisedNames: ['港灯', '香港电灯公司', 'HK Electric'],
    organizationType: 'business',
    activeYears: { from: 1889, to: 1997 },
    publicKnowledge: '港岛主要电力企业，工程、维修、客户服务和城市发展与港岛居民日常紧密相连。',
    promptSafeProfile: '香港电灯可进入港岛公用事业岗位、维修和停电压力；具体故障与责任必须由剧情事实建立。',
    headquartersPlaceIds: ['place_admiralty_commercial_district'],
    territoryPlaceIds: ['place_admiralty_commercial_district', 'place_causeway_bay_shopping_streets'],
    relatedOrganizationIds: ['org_clp', 'org_towngas'],
    sectorTags: ['utility', 'electricity', 'engineering', 'hong_kong_island'],
    influence: 84,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_towngas',
    displayName: '香港中华煤气',
    englishName: 'The Hong Kong and China Gas Company',
    disguisedNames: ['煤气公司', '中华煤气', 'Towngas'],
    organizationType: 'business',
    activeYears: { from: 1862, to: 1997 },
    publicKnowledge: '提供城市煤气及相关客户服务的公用事业企业，安装、维修、账务与安全检查直接进入住宅和商户。',
    promptSafeProfile: '煤气公司可进入维修、客户服务、安全检查和工程职业剧情，不把一般报修自动升级为灾害。',
    headquartersPlaceIds: ['place_admiralty_commercial_district'],
    territoryPlaceIds: ['place_causeway_bay_shopping_streets', 'place_fa_yuen_street'],
    relatedOrganizationIds: ['org_clp', 'org_hk_electric'],
    sectorTags: ['utility', 'gas', 'maintenance', 'customer_service'],
    influence: 82,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_hk_tramways',
    displayName: '香港电车',
    englishName: 'Hongkong Tramways',
    disguisedNames: ['电车公司', '叮叮', 'Hongkong Tramways'],
    organizationType: 'transport',
    activeYears: { from: 1904, to: 1997 },
    publicKnowledge: '贯穿港岛北岸的路面电车营运机构，车务、维修、乘客与街面交通形成稳定职业接触面。',
    promptSafeProfile: '香港电车可进入车务、维修、乘客和交通事故剧情，不需要模拟完整班次与路线表。',
    headquartersPlaceIds: ['place_causeway_bay_shopping_streets'],
    territoryPlaceIds: ['place_causeway_bay_shopping_streets', 'place_wan_chai_star_ferry_pier'],
    relatedOrganizationIds: ['org_mtrc', 'org_star_ferry'],
    sectorTags: ['transport', 'tram', 'maintenance', 'commute'],
    influence: 76,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_cathay_pacific',
    displayName: '国泰航空',
    englishName: 'Cathay Pacific Airways',
    disguisedNames: ['国泰', '国泰航空公司', 'Cathay Pacific'],
    organizationType: 'transport',
    activeYears: { from: 1946, to: 1997 },
    publicKnowledge: '以启德机场为核心的香港航空企业，机舱、地勤、票务、货运与旅客服务连接本地和国际网络。',
    promptSafeProfile: '国泰航空可进入航空职业、旅客、货运和班次压力剧情；安全、航班和跨境资料必须服从当年事实。',
    headquartersPlaceIds: ['place_kai_tak_airport'],
    territoryPlaceIds: ['place_kai_tak_airport'],
    relatedOrganizationIds: ['org_mtrc', 'org_hk_tramways'],
    sectorTags: ['transport', 'aviation', 'tourism', 'cargo'],
    influence: 86,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_po_leung_kuk',
    displayName: '保良局',
    englishName: 'Po Leung Kuk',
    disguisedNames: ['保良局总局', '保良局服务网络', 'PLK'],
    organizationType: 'public_service',
    activeYears: { from: 1878, to: 1997 },
    publicKnowledge: '历史悠久的慈善及社会服务机构，服务涉及儿童、家庭、教育、安老和社区支援。',
    promptSafeProfile: '保良局可进入社会工作、儿童与家庭服务、学校和社区职业剧情；敏感个案不得凭机构身份自动公开。',
    headquartersPlaceIds: ['place_causeway_bay_shopping_streets'],
    territoryPlaceIds: ['place_causeway_bay_shopping_streets', 'place_fa_yuen_street'],
    relatedOrganizationIds: ['org_tung_wah_group', 'org_caritas_hk'],
    sectorTags: ['charity', 'social_service', 'child_welfare', 'education'],
    influence: 80,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_caritas_hk',
    displayName: '香港明爱',
    englishName: 'Caritas - Hong Kong',
    disguisedNames: ['明爱', '明爱社会服务', 'Caritas Hong Kong'],
    organizationType: 'public_service',
    activeYears: { from: 1953, to: 1997 },
    publicKnowledge: '提供家庭、青年、社区、教育、康复和社会服务的慈善机构，联系基层家庭与专业服务人员。',
    promptSafeProfile: '香港明爱可进入社会工作、社区服务和家庭支援剧情；个案资料、资源和转介必须由当前事实建立。',
    headquartersPlaceIds: ['place_hong_kong_city_hall'],
    territoryPlaceIds: ['place_hong_kong_city_hall', 'place_sham_shui_po_street_markets'],
    relatedOrganizationIds: ['org_po_leung_kuk', 'org_tung_wah_group'],
    sectorTags: ['charity', 'social_service', 'family_service', 'community'],
    influence: 78,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_hk_housing_society',
    displayName: '香港房屋协会',
    englishName: 'Hong Kong Housing Society',
    disguisedNames: ['房协', '香港房协', 'Housing Society'],
    organizationType: 'public_service',
    activeYears: { from: 1948, to: 1997 },
    publicKnowledge: '参与住宅发展、租务与屋邨管理的公共性质机构，职员、住户、维修承办商和社区关系直接交织。',
    promptSafeProfile: '房协可进入物业管理、租务、住户和维修职业剧情，不等同房屋署，也不自动拥有警方或法院权力。',
    headquartersPlaceIds: ['place_causeway_bay_shopping_streets'],
    territoryPlaceIds: ['place_causeway_bay_shopping_streets', 'place_sham_shui_po_street_markets'],
    relatedOrganizationIds: ['org_cheung_kong_group', 'org_government_house'],
    sectorTags: ['housing', 'property_management', 'public_service', 'community'],
    influence: 80,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  }
];
