import { cityPowerRuntimeActorId } from './cityPowerIdentityIds';
import type { CityPowerFigureAnchor } from './cityPowerTypes';

type FigureDraft = Omit<CityPowerFigureAnchor, 'type' | 'canonicalSeedId' | 'runtimeActorId'>;

function anchor(canonicalSeedId: string, draft: FigureDraft): CityPowerFigureAnchor {
  return {
    type: 'CityPowerFigureAnchor',
    canonicalSeedId,
    runtimeActorId: cityPowerRuntimeActorId(canonicalSeedId),
    ...draft
  };
}

const triadFigureVisibility = {
  police: 'restricted',
  civilian: 'rumor',
  gang_member: 'rumor'
} as const;

export const hkLateColonialPowerFigures: CityPowerFigureAnchor[] = [
  anchor('power_police_commissioner_li_man_bun', {
    displayName: '李君夏',
    englishName: 'Li Kwan-ha',
    recognitionAliases: ['李处长', '一哥李Sir', '李Sir'],
    protectedRealNames: [],
    category: 'police_command',
    activeYears: { from: 1985, to: 1989 },
    publicRole: '皇家香港警队高层指挥人物',
    affiliationOrganizationIds: ['org_hk_police', 'org_police_hq'],
    relatedOrganizationIds: ['org_icac', 'org_legal_department'],
    usualPlaceIds: ['place_wan_chai_police_headquarters'],
    accessRoutes: ['警队简报', '重大案件记者会', '内部通告'],
    promptSafeProfile: '警队最高层级的公开指挥人物，常以纪律、舆论和政治压力影响基层案件处理。',
    promptSafeHooks: ['记者会前内部口径变化', '重大案件指挥压力', '廉署关注警队纪律'],
    identityHooks: {
      police: '警察身份可从内部通告、上级转述或重大案件会议听见李君夏。',
      civilian: '市民身份多从报纸、电视记者会和街坊议论中听见李君夏。',
      gang_member: '社团身份多把李君夏视作近期扫荡风向的象征。'
    },
    contactPolicy: 'restricted_contact',
    defaultVisibility: 'public',
    sourceConfidence: 'medium',
    copyRisk: 'medium',
    importance: 96
  }),
  anchor('power_police_deputy_ho_wing_sir', {
    displayName: '何荣源',
    englishName: 'John Ho Wing-sir',
    recognitionAliases: ['何副处', '何Sir', '行动处何荣源'],
    protectedRealNames: [],
    category: 'police_command',
    activeYears: { from: 1984, to: 1990 },
    publicRole: '警队行动与地区调配高层',
    affiliationOrganizationIds: ['org_hk_police', 'org_police_hq'],
    relatedOrganizationIds: ['org_icac'],
    usualPlaceIds: ['place_wan_chai_police_headquarters', 'place_central_police_station'],
    accessRoutes: ['行动命令摘要', '分区指挥会议', '夜间突击部署'],
    promptSafeProfile: '他负责把总部意志变成街面行动，既懂警队规矩，也懂媒体镜头前的分寸。',
    promptSafeHooks: ['临时抽调防暴队', '分区主管被召回总部', '行动口径突然收紧'],
    identityHooks: {
      police: '警察身份会从排更表和行动命令上见到何荣源的签批影子。',
      civilian: '市民身份只会在大案新闻里听到何荣源代表警队解释行动。',
      gang_member: '社团身份把何荣源的名字当作近期街面查牌会变密的预兆。'
    },
    contactPolicy: 'restricted_contact',
    defaultVisibility: 'public',
    sourceConfidence: 'medium',
    copyRisk: 'medium',
    importance: 90
  }),
  anchor('power_cid_senior_lau_kai', {
    displayName: '刘启总督察',
    englishName: 'Chief Inspector Kai Lau',
    recognitionAliases: ['刘Sir', '重案刘启', 'CID刘总'],
    protectedRealNames: ['Lau Kai Source', '刘启源型'],
    category: 'police_command',
    activeYears: { from: 1982, to: 1991 },
    publicRole: '刑事情报与重案侦缉高阶警官',
    affiliationOrganizationIds: ['org_hk_police', 'org_police_hq'],
    relatedOrganizationIds: ['org_icac', 'org_wo_shing_wo'],
    usualPlaceIds: ['place_wan_chai_police_headquarters', 'place_mong_kok_police_station'],
    accessRoutes: ['CID线人转述', '重案组案头会议', '扣查室外的低声交代'],
    promptSafeProfile: '刘启总督察熟悉线人、口供和街面消息的灰区，能让一条传闻变成搜查方向。',
    promptSafeHooks: ['线人突然要求换地点', '重案组档案被调阅', '证人保护条件变得苛刻'],
    identityHooks: {
      police: '警察身份可从CID同僚口中听到刘启总督察对线索可信度的判断。',
      civilian: '市民身份可能只在被问话时知道刘启总督察代表重案组。',
      gang_member: '社团身份会把刘启总督察看作熟悉街面暗语的危险警官。'
    },
    contactPolicy: 'restricted_contact',
    defaultVisibility: 'identity_gated',
    visibilityByIdentity: { police: 'restricted', civilian: 'rumor', gang_member: 'rumor' },
    sourceConfidence: 'low',
    copyRisk: 'low',
    importance: 86
  }),
  anchor('power_icac_commissioner_banham_ha', {
    displayName: '班士利',
    englishName: 'Geoffrey Barnes',
    recognitionAliases: ['班专员', '廉政专员', 'Barnes'],
    protectedRealNames: [],
    category: 'icac_command',
    activeYears: { from: 1984, to: 1988 },
    publicRole: '廉政公署最高层反贪指挥人物',
    affiliationOrganizationIds: ['org_icac'],
    relatedOrganizationIds: ['org_hk_police', 'org_legal_department'],
    usualPlaceIds: ['place_icac_headquarters'],
    accessRoutes: ['廉署公开声明', '反贪记者会', '检控前会议'],
    promptSafeProfile: '班士利代表反贪机构的公开威慑，任何涉及公职人员的钱路都会被重新审视。',
    promptSafeHooks: ['廉署突然重启旧案', '匿名举报箱被清空', '警队高层避谈某次饭局'],
    identityHooks: {
      police: '警察身份会从纪律提醒和廉署查询中感到班士利带来的压力。',
      civilian: '市民身份在新闻里把班士利视为反贪象征。',
      gang_member: '社团身份会担心班士利让旧保护伞失效。'
    },
    contactPolicy: 'restricted_contact',
    defaultVisibility: 'public',
    sourceConfidence: 'medium',
    copyRisk: 'medium',
    importance: 94
  }),
  anchor('power_icac_ops_wong_chung', {
    displayName: '郭文纬',
    englishName: 'Tony Kwok Man-wai',
    recognitionAliases: ['郭处长', '郭Sir', '廉署郭文纬'],
    protectedRealNames: [],
    category: 'icac_command',
    activeYears: { from: 1983, to: 1992 },
    publicRole: '廉署行动部门高级调查指挥',
    affiliationOrganizationIds: ['org_icac'],
    relatedOrganizationIds: ['org_hk_police', 'org_legal_department'],
    usualPlaceIds: ['place_icac_headquarters', 'place_central_magistracy'],
    accessRoutes: ['行动组传票', '秘密约见室', '检控证据会议'],
    promptSafeProfile: '郭文纬处理最容易爆炸的反贪线索，擅长在证人口供和资金流之间施压。',
    promptSafeHooks: ['证人改在廉署大楼会面', '银行记录被要求封存', '警员同僚开始避谈旧账'],
    identityHooks: {
      police: '警察身份可能从同僚被约谈的消息中听见郭文纬。',
      civilian: '市民身份多通过举报回执或新闻简讯认识郭文纬。',
      gang_member: '社团身份会把郭文纬视为调查保护伞的危险人物。'
    },
    contactPolicy: 'restricted_contact',
    defaultVisibility: 'identity_gated',
    visibilityByIdentity: { police: 'restricted', civilian: 'rumor', gang_member: 'rumor' },
    sourceConfidence: 'low',
    copyRisk: 'low',
    importance: 88
  }),
  anchor('power_governor_wai_yik_sun', {
    displayName: '卫奕信',
    englishName: 'David Wilson',
    recognitionAliases: ['卫督', '卫奕信爵士', '总督卫奕信'],
    protectedRealNames: [],
    category: 'government_official',
    activeYears: { from: 1987, to: 1992 },
    publicRole: '殖民地后期香港最高行政代表',
    affiliationOrganizationIds: ['org_government_house'],
    relatedOrganizationIds: ['org_hk_police', 'org_legal_department', 'org_hsbc'],
    usualPlaceIds: ['place_government_house', 'place_murray_building'],
    accessRoutes: ['政府新闻处公告', '行政会议风声', '总督府接待名单'],
    promptSafeProfile: '卫奕信是公开政治秩序的最高象征，政策语气会影响警队、商界和报馆的判断。',
    promptSafeHooks: ['总督府突然安排闭门会', '政策简报修改用词', '警队高层提前统一口径'],
    identityHooks: {
      police: '警察身份会从总部命令和政府口径中感到卫奕信的间接影响。',
      civilian: '市民身份主要在新闻、演说和街坊政治议论里听见卫奕信。',
      gang_member: '社团身份只会关心卫奕信的政策风向会不会带来扫荡。'
    },
    contactPolicy: 'background_only',
    defaultVisibility: 'public',
    sourceConfidence: 'medium',
    copyRisk: 'medium',
    importance: 95
  }),
  anchor('power_chief_secretary_fok_tak_ming', {
    displayName: '霍德',
    englishName: 'David Ford',
    recognitionAliases: ['霍德爵士', '布政司霍德'],
    protectedRealNames: [],
    category: 'government_official',
    activeYears: { from: 1986, to: 1993 },
    publicRole: '政府行政体系核心协调者',
    affiliationOrganizationIds: ['org_government_house'],
    relatedOrganizationIds: ['org_police_hq', 'org_legal_department', 'org_rthk'],
    usualPlaceIds: ['place_murray_building', 'place_government_house'],
    accessRoutes: ['政府内部简报', '跨部门协调会', '政策局饭局传闻'],
    promptSafeProfile: '霍德掌握部门之间的协调节奏，能让一件街头小事变成政策风险。',
    promptSafeHooks: ['跨部门会议突然加会', '广播口径提前统一', '警队被要求提交额外说明'],
    identityHooks: {
      police: '警察身份可能从跨部门备忘录里看到霍德的要求。',
      civilian: '市民身份会从新闻和电台讨论中听到霍德代表政府解释政策。',
      gang_member: '社团身份会把霍德的关注视作生意环境收紧。'
    },
    contactPolicy: 'background_only',
    defaultVisibility: 'public',
    sourceConfidence: 'low',
    copyRisk: 'low',
    importance: 88
  }),
  anchor('power_attorney_general_ma_siu_kei', {
    displayName: '唐明治',
    englishName: 'Michael Thomas',
    recognitionAliases: ['唐律政', '律政司唐明治'],
    protectedRealNames: [],
    category: 'legal_official',
    activeYears: { from: 1983, to: 1988 },
    publicRole: '检控与政府法律意见最高层人物',
    affiliationOrganizationIds: ['org_legal_department'],
    relatedOrganizationIds: ['org_icac', 'org_hk_police', 'org_government_house'],
    usualPlaceIds: ['place_supreme_court_building', 'place_central_magistracy'],
    accessRoutes: ['检控会议', '律政署来函', '法院走廊传闻'],
    promptSafeProfile: '唐明治决定证据怎样进入法庭，也能让政治敏感案件在法律字眼里转向。',
    promptSafeHooks: ['检控意见突然延迟', '证供格式被退回', '法庭外记者追问口径'],
    identityHooks: {
      police: '警察身份会从检控意见和补充证供要求中接触唐明治的影响。',
      civilian: '市民身份只会在重大案件新闻中听见唐明治。',
      gang_member: '社团身份会关注唐明治是否批准重案起诉。'
    },
    contactPolicy: 'background_only',
    defaultVisibility: 'public',
    sourceConfidence: 'low',
    copyRisk: 'low',
    importance: 87
  }),
  anchor('power_new_yi_on_heung_sir', {
    displayName: '向华炎',
    englishName: 'Heung Wah-yim',
    recognitionAliases: ['向先生', '新义安向氏人物'],
    protectedRealNames: [],
    category: 'triad_leader',
    activeYears: { from: 1975, to: 1992 },
    publicRole: '坊间传闻中的新义安高层人物',
    affiliationOrganizationIds: ['org_sun_yee_on'],
    relatedOrganizationIds: ['org_golden_harvest', 'org_hk_police', 'org_wo_shing_wo'],
    usualPlaceIds: ['place_portland_street', 'place_golden_harvest_studio'],
    accessRoutes: ['夜场经理转述', '片场茶水间传闻', '叔父辈饭局'],
    promptSafeProfile: '向华炎从不需要公开露面，传闻里他能让片场纠纷、夜场保护和街面人情同时安静下来。',
    promptSafeHooks: ['剧组突然改用指定保安', '夜场经理主动赔笑', '线人不肯在电话里提名字'],
    identityHooks: {
      police: '警察身份只能从情报摘要和线人口供里拼出向华炎的轮廓。',
      civilian: '市民身份多半只听过向华炎是不能乱讲的江湖名号。',
      gang_member: '社团身份知道向华炎的称呼代表新义安一条高层线。'
    },
    contactPolicy: 'rumor_only',
    defaultVisibility: 'identity_gated',
    visibilityByIdentity: triadFigureVisibility,
    sourceConfidence: 'medium',
    copyRisk: 'high',
    importance: 92
  }),
  anchor('power_wo_shing_wo_uncle_kiu', {
    displayName: '桥叔',
    englishName: 'Uncle Kiu',
    recognitionAliases: ['和字头桥叔', '庙街桥叔', '旧规矩桥爷'],
    protectedRealNames: ['Uncle Kiu Source', '桥叔源型'],
    category: 'triad_leader',
    activeYears: { from: 1978, to: 1991 },
    publicRole: '坊间传闻中的和胜和叔父辈人物',
    affiliationOrganizationIds: ['org_wo_shing_wo'],
    relatedOrganizationIds: ['org_sun_yee_on', 'org_14k', 'org_hk_police'],
    usualPlaceIds: ['place_temple_street_night_market', 'place_yau_ma_tei_fruit_market'],
    accessRoutes: ['庙街茶档暗语', '夜市摊主传话', '旧社团拜帖'],
    promptSafeProfile: '桥叔代表老派街面规矩，话不多，但一句话足以让摊档、马房和看场人换态度。',
    promptSafeHooks: ['摊主突然集体收声', '夜市纠纷被老人调停', '线人要求避开庙街见面'],
    identityHooks: {
      police: '警察身份会在老线人和扫黄档案里见到桥叔的称呼。',
      civilian: '市民身份只会把桥叔当成夜市里有面子的老人。',
      gang_member: '社团身份知道桥叔的话代表和胜和叔父辈意见。'
    },
    contactPolicy: 'rumor_only',
    defaultVisibility: 'rumor',
    visibilityByIdentity: triadFigureVisibility,
    sourceConfidence: 'low',
    copyRisk: 'low',
    importance: 88
  }),
  anchor('power_14k_dragon_chow', {
    displayName: '周龙哥',
    englishName: 'Dragon Chow',
    recognitionAliases: ['十四号龙哥', '尖沙咀周龙', '码头龙哥'],
    protectedRealNames: ['Dragon Chow Source', '周龙源型'],
    category: 'triad_leader',
    activeYears: { from: 1979, to: 1993 },
    publicRole: '坊间传闻中的十四K跨区人物',
    affiliationOrganizationIds: ['org_14k'],
    relatedOrganizationIds: ['org_sun_yee_on', 'org_wo_shing_wo', 'org_hk_police'],
    usualPlaceIds: ['place_chungking_mansions', 'place_macau_ferry_terminal'],
    accessRoutes: ['码头蛇头传闻', '重庆大厦线人', '跨境赌档口信'],
    promptSafeProfile: '周龙哥的名字常和跨境走动、旅馆线索和码头风声一起出现，真实势力边界故意模糊。',
    promptSafeHooks: ['码头查牌前有人走漏风声', '旅馆老板突然改口', '赌档账簿被提前搬走'],
    identityHooks: {
      police: '警察身份会从跨境情报和旅馆检查记录里追到周龙哥的传闻。',
      civilian: '市民身份只会在码头和旅馆八卦里听到周龙哥。',
      gang_member: '社团身份知道周龙哥代表十四K一条跨区线。'
    },
    contactPolicy: 'rumor_only',
    defaultVisibility: 'rumor',
    visibilityByIdentity: triadFigureVisibility,
    sourceConfidence: 'low',
    copyRisk: 'low',
    importance: 87
  }),
  anchor('power_tvb_sir_siu', {
    displayName: '邵逸夫',
    englishName: 'Run Run Shaw',
    recognitionAliases: ['六叔', '邵老板', '无线大班'],
    protectedRealNames: [],
    category: 'media_boss',
    activeYears: { from: 1967, to: 1997 },
    publicRole: '电视广播和娱乐资本高层人物',
    affiliationOrganizationIds: ['org_tvb', 'org_shaw_brothers'],
    relatedOrganizationIds: ['org_golden_harvest', 'org_rthk', 'org_ming_pao'],
    usualPlaceIds: ['place_tv_city_clear_water_bay', 'place_shaw_brothers_studio'],
    accessRoutes: ['电视城高层会议', '慈善晚宴名单', '艺员合约转述'],
    promptSafeProfile: '邵逸夫掌握电视台档期、艺员合约和娱乐资本面子，能把一个人捧成明星，也能让他消失在节目表。',
    promptSafeHooks: ['艺员档期突然清空', '新闻部收到高层提醒', '慈善晚宴座位被重新安排'],
    identityHooks: {
      police: '警察身份会在电视城安保和新闻采访协调中听见邵逸夫。',
      civilian: '市民身份把邵逸夫视作电视城和娱乐圈的大老板。',
      gang_member: '社团身份会关注邵逸夫身边的片场保安和合约纠纷。'
    },
    contactPolicy: 'background_only',
    defaultVisibility: 'public',
    sourceConfidence: 'medium',
    copyRisk: 'medium',
    importance: 91
  }),
  anchor('power_ming_pao_cha_sir', {
    displayName: '查良镛',
    englishName: 'Louis Cha',
    recognitionAliases: ['金庸', '查先生', '查社长', '明报查先生'],
    protectedRealNames: [],
    category: 'media_boss',
    activeYears: { from: 1959, to: 1993 },
    publicRole: '报馆创办人与舆论场重要人物',
    affiliationOrganizationIds: ['org_ming_pao'],
    relatedOrganizationIds: ['org_sing_tao', 'org_rthk', 'org_legal_department'],
    usualPlaceIds: ['place_rthk_broadcasting_house', 'place_central_magistracy'],
    accessRoutes: ['编辑部茶水间', '社评截稿前会议', '文化圈饭局'],
    promptSafeProfile: '查良镛让报馆同时拥有新闻判断和文人声望，一篇评论足以让官商警都重新估算舆论。',
    promptSafeHooks: ['社评迟迟不落标题', '记者坚持追问旧案', '文化圈饭局流出一句评语'],
    identityHooks: {
      police: '警察身份会关注查良镛旗下报馆如何报道纪律和重大案件。',
      civilian: '市民身份会把查良镛与有分量的报纸评论联系起来。',
      gang_member: '社团身份会担心查良镛的报馆把街面传闻写成公共议题。'
    },
    contactPolicy: 'background_only',
    defaultVisibility: 'public',
    sourceConfidence: 'medium',
    copyRisk: 'medium',
    importance: 86
  }),
  anchor('power_sing_tao_wu_lady', {
    displayName: '胡仙',
    englishName: 'Sally Aw',
    recognitionAliases: ['星岛胡女士', '报业女班主'],
    protectedRealNames: [],
    category: 'media_boss',
    activeYears: { from: 1970, to: 1997 },
    publicRole: '报业集团与商界社交圈高层人物',
    affiliationOrganizationIds: ['org_sing_tao'],
    relatedOrganizationIds: ['org_ming_pao', 'org_hsbc', 'org_government_house'],
    usualPlaceIds: ['place_broadcast_drive', 'place_hsbc_main_building'],
    accessRoutes: ['报业集团办公室', '商会晚宴', '英文报线人'],
    promptSafeProfile: '胡仙熟悉新闻版面、商业关系和上层社交礼节，能让一条财经消息换一种姿态出现。',
    promptSafeHooks: ['英文版头条忽然换位', '商界晚宴座位暗藏信号', '记者被提醒不要碰某家公司'],
    identityHooks: {
      police: '警察身份会在高层舆情简报中看到胡仙报业集团的反应。',
      civilian: '市民身份会把胡仙和星岛报业的商业新闻联系起来。',
      gang_member: '社团身份多从商界消息和报纸风向判断胡仙的影响。'
    },
    contactPolicy: 'background_only',
    defaultVisibility: 'public',
    sourceConfidence: 'medium',
    copyRisk: 'medium',
    importance: 82
  }),
  anchor('power_cheung_kong_lee_ka_sing', {
    displayName: '李嘉诚',
    englishName: 'Li Ka-shing',
    recognitionAliases: ['长实李生', '李先生', '地产李先生'],
    protectedRealNames: [],
    category: 'business_tycoon',
    activeYears: { from: 1971, to: 1997 },
    publicRole: '地产与资本市场重要商界人物',
    affiliationOrganizationIds: ['org_cheung_kong_group'],
    relatedOrganizationIds: ['org_hsbc', 'org_hk_stock_exchange', 'org_government_house'],
    usualPlaceIds: ['place_hsbc_main_building', 'place_exchange_square'],
    accessRoutes: ['中环董事会传闻', '银行家饭局', '上市公告前风声'],
    promptSafeProfile: '李嘉诚的影响来自资本、地皮和长期信誉，许多城市变化先在他的会议室里成形。',
    promptSafeHooks: ['银行贷款条件突然松动', '地盘收购风声提前走漏', '财经记者同时追同一只股票'],
    identityHooks: {
      police: '警察身份会在保护贵宾和处理地产纠纷时接触李嘉诚的外围人员。',
      civilian: '市民身份会在财经新闻和楼市传闻里听见李嘉诚。',
      gang_member: '社团身份会把李嘉诚相关地盘视作不能乱碰的高风险地方。'
    },
    contactPolicy: 'background_only',
    defaultVisibility: 'public',
    sourceConfidence: 'medium',
    copyRisk: 'medium',
    importance: 93
  }),
  anchor('power_sun_hung_kai_kwok_family', {
    displayName: '郭得胜',
    englishName: 'Kwok Tak-seng',
    recognitionAliases: ['新地郭生', '地产郭氏'],
    protectedRealNames: [],
    category: 'business_tycoon',
    activeYears: { from: 1972, to: 1997 },
    publicRole: '地产家族资本与大型项目代表',
    affiliationOrganizationIds: ['org_sun_hung_kai_group'],
    relatedOrganizationIds: ['org_hsbc', 'org_hk_stock_exchange', 'org_cheung_kong_group'],
    usualPlaceIds: ['place_exchange_square', 'place_harbour_city'],
    accessRoutes: ['地产项目会议', '承建商饭局', '上市公司公告'],
    promptSafeProfile: '郭得胜把家族资本、地盘规划和银行关系捆在一起，许多街区改造都绕不开他们。',
    promptSafeHooks: ['承建商突然换人', '地盘保安加强', '财经版提早收到项目消息'],
    identityHooks: {
      police: '警察身份会在大型地盘纠纷和保安安排里遇见郭得胜的外围。',
      civilian: '市民身份多从新楼盘、商场和财经新闻里认识郭得胜。',
      gang_member: '社团身份会把郭得胜相关工程看作有高层关注的生意。'
    },
    contactPolicy: 'background_only',
    defaultVisibility: 'public',
    sourceConfidence: 'medium',
    copyRisk: 'medium',
    importance: 89
  }),
  anchor('power_golden_harvest_chow_boss', {
    displayName: '邹文怀',
    englishName: 'Raymond Chow',
    recognitionAliases: ['嘉禾邹生', '邹老板', '片场邹老板'],
    protectedRealNames: [],
    category: 'entertainment_backstage',
    activeYears: { from: 1970, to: 1997 },
    publicRole: '电影公司制作与发行高层人物',
    affiliationOrganizationIds: ['org_golden_harvest'],
    relatedOrganizationIds: ['org_tvb', 'org_shaw_brothers', 'org_sun_yee_on'],
    usualPlaceIds: ['place_golden_harvest_studio', 'place_lai_chi_kok_industrial_area'],
    accessRoutes: ['片场制片室', '院线排片饭局', '武师班头转述'],
    promptSafeProfile: '邹文怀懂发行、明星档期和片场人情，能把一场纠纷变成合约问题，也能把合约问题变成江湖问题。',
    promptSafeHooks: ['片场临时停工', '武师班头要求加钱', '院线排片突然调整'],
    identityHooks: {
      police: '警察身份会在片场骚扰、敲诈或明星保护案中听见邹文怀。',
      civilian: '市民身份会把邹文怀和卖座港片联系起来。',
      gang_member: '社团身份会关注邹文怀片场背后的保护和投资人关系。'
    },
    contactPolicy: 'contactable_seed',
    defaultVisibility: 'public',
    sourceConfidence: 'medium',
    copyRisk: 'medium',
    importance: 85
  }),
  anchor('power_action_star_agent_choi_ming', {
    displayName: '蔡子明',
    englishName: 'Choi Chi-ming',
    recognitionAliases: ['蔡经理', '蔡生', '功夫明星经纪人'],
    protectedRealNames: [],
    category: 'entertainment_backstage',
    activeYears: { from: 1984, to: 1992 },
    publicRole: '动作明星经纪与片场协调人物',
    affiliationOrganizationIds: ['org_golden_harvest'],
    relatedOrganizationIds: ['org_tvb', 'org_shaw_brothers', 'org_sun_yee_on'],
    usualPlaceIds: ['place_golden_harvest_studio', 'place_tv_city_clear_water_bay'],
    accessRoutes: ['艺人休息室', '保险合同夹层', '武行饭局'],
    promptSafeProfile: '蔡子明游走在明星、武师、保险和片场保安之间，手里常有没人愿意公开承认的麻烦。',
    promptSafeHooks: ['动作明星临时失约', '保险经纪要求重签', '武行兄弟在片场外等人'],
    identityHooks: {
      police: '警察身份可通过片场投诉、伤人案和保安记录接触蔡子明。',
      civilian: '市民身份可能只知道蔡子明替动作明星挡记者。',
      gang_member: '社团身份会把蔡子明视为进入片场和明星线的人情入口。'
    },
    contactPolicy: 'contactable_seed',
    defaultVisibility: 'identity_gated',
    visibilityByIdentity: { police: 'restricted', civilian: 'rumor', gang_member: 'rumor' },
    sourceConfidence: 'low',
    copyRisk: 'low',
    importance: 80
  })
];
