import type { CityOrganizationAnchor } from './cityPowerTypes';
import { hkLateColonialCivilianOrganizations } from './hkLateColonialCivilianOrganizations';
import { hkLateColonialTriadOrganizations } from './hkLateColonialTriadOrganizations';

export const hkLateColonialOrganizations: CityOrganizationAnchor[] = [
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_hk_police',
    displayName: '皇家香港警队',
    englishName: 'Royal Hong Kong Police',
    disguisedNames: ['警队', '皇家警队', '差馆系统'],
    organizationType: 'police',
    activeYears: { from: 1844, to: 1997 },
    publicKnowledge: '殖民地后期香港最主要的执法机关，掌管街面治安、刑事侦查和纪律指挥。',
    promptSafeProfile: '警队是城市秩序的公开支柱，基层巡逻、侦缉部门和总部命令共同影响每一宗案件。',
    headquartersPlaceIds: ['place_wan_chai_police_headquarters'],
    territoryPlaceIds: [
      'place_mong_kok_police_station',
      'place_yau_ma_tei_police_station',
      'place_central_police_station'
    ],
    relatedOrganizationIds: ['org_police_hq', 'org_icac', 'org_legal_department'],
    sectorTags: ['police', 'law_enforcement', 'discipline'],
    influence: 100,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_police_hq',
    displayName: '警察总部',
    englishName: 'Police Headquarters',
    disguisedNames: ['湾仔总部', '总部大楼', '警队指挥层'],
    organizationType: 'police',
    activeYears: { from: 1950, to: 1997 },
    publicKnowledge: '警队最高层的办公和指挥中心，重大案件、新闻发布和内部纪律都从这里扩散。',
    promptSafeProfile: '总部代表警队命令链，既能压下基层风声，也能把街面小案推成全城关注。',
    headquartersPlaceIds: ['place_wan_chai_police_headquarters'],
    territoryPlaceIds: ['place_wan_chai_police_headquarters'],
    relatedOrganizationIds: ['org_hk_police', 'org_icac', 'org_legal_department'],
    sectorTags: ['police', 'command', 'press'],
    influence: 96,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_icac',
    displayName: '廉政公署',
    englishName: 'ICAC',
    disguisedNames: ['廉署', '反贪部门', '北角廉署'],
    organizationType: 'icac',
    activeYears: { from: 1974, to: 1997 },
    publicKnowledge: '专责反贪调查和防贪教育的机构，警队、政府和商界都在其监察阴影下行事。',
    promptSafeProfile: '廉署让旧式人情和现金关系变得危险，任何举报都可能牵出高层压力。',
    headquartersPlaceIds: ['place_icac_headquarters'],
    territoryPlaceIds: ['place_icac_headquarters', 'place_central_magistracy'],
    relatedOrganizationIds: ['org_hk_police', 'org_police_hq', 'org_legal_department'],
    sectorTags: ['icac', 'anti_corruption', 'government'],
    influence: 95,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_government_house',
    displayName: '港督府',
    englishName: 'Government House',
    disguisedNames: ['山顶官邸', '总督府', '上亚厘毕道官邸'],
    organizationType: 'government',
    activeYears: { from: 1855, to: 1997 },
    publicKnowledge: '殖民地后期香港最高行政象征，政策、任命和政治风向都与这里相连。',
    promptSafeProfile: '港督府是公开权力的象征，很多命令不会直接落款，却会改变警队、商界和媒体的语气。',
    headquartersPlaceIds: ['place_government_house'],
    territoryPlaceIds: ['place_government_house', 'place_murray_building'],
    relatedOrganizationIds: ['org_police_hq', 'org_legal_department', 'org_hsbc'],
    sectorTags: ['government', 'politics', 'policy'],
    influence: 94,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_legal_department',
    displayName: '律政署',
    englishName: 'Legal Department',
    disguisedNames: ['律政系统', '检控部门', '法院线'],
    organizationType: 'legal',
    activeYears: { from: 1844, to: 1997 },
    publicKnowledge: '负责检控和法律意见的政府部门，决定许多案件能否真正进入法庭。',
    promptSafeProfile: '律政署把街面证供变成法庭语言，也会让证据不足的调查在门外停下。',
    headquartersPlaceIds: ['place_supreme_court_building'],
    territoryPlaceIds: ['place_central_magistracy', 'place_supreme_court_building'],
    relatedOrganizationIds: ['org_hk_police', 'org_icac', 'org_government_house'],
    sectorTags: ['legal', 'prosecution', 'court'],
    influence: 90,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_tvb',
    displayName: '电视广播城',
    englishName: 'TVB',
    disguisedNames: ['无线', '清水湾电视城', '电视台'],
    organizationType: 'media',
    activeYears: { from: 1967, to: 1997 },
    publicKnowledge: '电视新闻和娱乐节目的核心机构，能把案件、明星和政治风声送进每个客厅。',
    promptSafeProfile: '电视台把城市传闻剪成画面，也让幕后老板、记者和艺员经纪人形成另一条权力线。',
    headquartersPlaceIds: ['place_tv_city_clear_water_bay'],
    territoryPlaceIds: ['place_tv_city_clear_water_bay', 'place_broadcast_drive'],
    relatedOrganizationIds: ['org_rthk', 'org_golden_harvest', 'org_shaw_brothers'],
    sectorTags: ['television', 'media', 'entertainment'],
    influence: 88,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_golden_harvest',
    displayName: '嘉禾片场',
    englishName: 'Golden Harvest',
    disguisedNames: ['嘉禾影业', '荔枝角片场', '电影公司'],
    organizationType: 'entertainment',
    activeYears: { from: 1970, to: 1997 },
    publicKnowledge: '港产动作片和商业片的重要制作网络，片场、发行和明星档期牵动许多江湖传闻。',
    promptSafeProfile: '嘉禾片场连接导演、武师、经纪和发行商，台前笑脸背后常有片酬、保护费和人情债。',
    headquartersPlaceIds: ['place_golden_harvest_studio'],
    territoryPlaceIds: ['place_golden_harvest_studio', 'place_lai_chi_kok_industrial_area'],
    relatedOrganizationIds: ['org_tvb', 'org_shaw_brothers', 'org_sun_yee_on'],
    sectorTags: ['film', 'entertainment', 'backstage'],
    influence: 86,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_shaw_brothers',
    displayName: '邵氏片场',
    englishName: 'Shaw Brothers',
    disguisedNames: ['邵氏影城', '清水湾片场', '老牌电影厂'],
    organizationType: 'entertainment',
    activeYears: { from: 1958, to: 1997 },
    publicKnowledge: '老牌片厂和娱乐资本网络，院线、艺员训练和电视业务仍有深厚影响。',
    promptSafeProfile: '邵氏片场是旧时代娱乐秩序的象征，规矩、合约和人脉比新闻稿更能说明问题。',
    headquartersPlaceIds: ['place_shaw_brothers_studio'],
    territoryPlaceIds: ['place_shaw_brothers_studio', 'place_tv_city_clear_water_bay'],
    relatedOrganizationIds: ['org_tvb', 'org_golden_harvest'],
    sectorTags: ['film', 'entertainment', 'studio'],
    influence: 82,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_ming_pao',
    displayName: '明报馆',
    disguisedNames: ['明报', '文人报馆', '北角报房'],
    organizationType: 'media',
    activeYears: { from: 1959, to: 1997 },
    publicKnowledge: '以评论和都市新闻见长的报馆，常在政治、文化和案件舆论中保留独立声音。',
    promptSafeProfile: '明报馆的编辑部重视线索和文字分寸，一篇社评可能让权力人物改口。',
    headquartersPlaceIds: ['place_rthk_broadcasting_house'],
    territoryPlaceIds: ['place_central_magistracy', 'place_broadcast_drive'],
    relatedOrganizationIds: ['org_sing_tao', 'org_rthk', 'org_legal_department'],
    sectorTags: ['newspaper', 'media', 'commentary'],
    influence: 84,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_sing_tao',
    displayName: '星岛报业',
    disguisedNames: ['星岛', '报业集团', '英文中文报线'],
    organizationType: 'media',
    activeYears: { from: 1938, to: 1997 },
    publicKnowledge: '跨语种报业集团，商业新闻、社会新闻和上层社交圈消息互相流通。',
    promptSafeProfile: '星岛报业懂得在商界饭局和新闻版面之间取平衡，消息源常比稿件更重要。',
    headquartersPlaceIds: ['place_broadcast_drive'],
    territoryPlaceIds: ['place_broadcast_drive', 'place_central_magistracy'],
    relatedOrganizationIds: ['org_ming_pao', 'org_hsbc', 'org_government_house'],
    sectorTags: ['newspaper', 'media', 'business_press'],
    influence: 80,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_hsbc',
    displayName: '汇丰银行',
    englishName: 'HSBC',
    disguisedNames: ['汇丰', '中环大银行', '皇后大道银行'],
    organizationType: 'finance',
    activeYears: { from: 1865, to: 1997 },
    publicKnowledge: '殖民地后期香港金融核心之一，贷款、地产融资和大型商业关系都绕不开它。',
    promptSafeProfile: '汇丰银行像城市的资金阀门，许多看似江湖或娱乐圈的麻烦最后都指向账面。',
    headquartersPlaceIds: ['place_hsbc_main_building'],
    territoryPlaceIds: ['place_hsbc_main_building', 'place_exchange_square'],
    relatedOrganizationIds: ['org_hang_seng_bank', 'org_cheung_kong_group', 'org_sun_hung_kai_group'],
    sectorTags: ['finance', 'banking', 'capital'],
    influence: 92,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_hang_seng_bank',
    displayName: '恒生银行',
    englishName: 'Hang Seng Bank',
    disguisedNames: ['恒生', '中资银行线', '本地银行'],
    organizationType: 'finance',
    activeYears: { from: 1933, to: 1997 },
    publicKnowledge: '本地银行与指数品牌连接零售金融、商户贷款和中环市场情绪。',
    promptSafeProfile: '恒生银行更贴近本地商户和市场脉搏，账房里的小动作常比大新闻更早出现。',
    headquartersPlaceIds: ['place_hang_seng_bank_headquarters'],
    territoryPlaceIds: ['place_hang_seng_bank_headquarters', 'place_exchange_square'],
    relatedOrganizationIds: ['org_hsbc', 'org_hk_stock_exchange'],
    sectorTags: ['finance', 'banking', 'local_business'],
    influence: 84,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_cheung_kong_group',
    displayName: '长江实业',
    disguisedNames: ['长实', '地产财团', '中环地产线'],
    organizationType: 'property',
    activeYears: { from: 1971, to: 1997 },
    publicKnowledge: '大型地产和基建财团，地皮、商场和融资关系让它拥有稳定影响力。',
    promptSafeProfile: '长江实业的力量不靠喧哗，而是靠贷款、地契和董事会席位慢慢改变城市。',
    headquartersPlaceIds: ['place_hsbc_main_building'],
    territoryPlaceIds: ['place_the_landmark_central', 'place_harbour_city'],
    relatedOrganizationIds: ['org_hsbc', 'org_hk_stock_exchange', 'org_sun_hung_kai_group'],
    sectorTags: ['property', 'infrastructure', 'capital'],
    influence: 90,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_sun_hung_kai_group',
    displayName: '新鸿基地产',
    disguisedNames: ['新地', '地产家族', '九龙地产线'],
    organizationType: 'property',
    activeYears: { from: 1972, to: 1997 },
    publicKnowledge: '主要地产集团，住宅、商场和家族资本在九龙与新界扩张。',
    promptSafeProfile: '新鸿基地产代表家族式地产权力，项目批文、银行关系和地盘消息彼此相扣。',
    headquartersPlaceIds: ['place_exchange_square'],
    territoryPlaceIds: ['place_harbour_city', 'place_tsuen_wan_industrial_area'],
    relatedOrganizationIds: ['org_hsbc', 'org_cheung_kong_group', 'org_hk_stock_exchange'],
    sectorTags: ['property', 'family_business', 'development'],
    influence: 88,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  ...hkLateColonialCivilianOrganizations,
  ...hkLateColonialTriadOrganizations,
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_hk_stock_exchange',
    displayName: '香港联合交易所',
    englishName: 'The Stock Exchange of Hong Kong Limited',
    disguisedNames: ['交易所', '中环股票场', '上市大厅'],
    organizationType: 'finance',
    activeYears: { from: 1986, to: 1997 },
    publicKnowledge: '统一后的证券交易平台，上市消息、停牌风声和融资计划会迅速影响商界。',
    promptSafeProfile: '交易所把商界野心变成数字，也让内幕消息和市场谣言有了追逐目标。',
    headquartersPlaceIds: ['place_exchange_square'],
    territoryPlaceIds: ['place_exchange_square', 'place_hsbc_main_building'],
    relatedOrganizationIds: ['org_hsbc', 'org_hang_seng_bank', 'org_cheung_kong_group'],
    sectorTags: ['finance', 'market', 'listing'],
    influence: 86,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  },
  {
    type: 'CityOrganizationAnchor',
    organizationId: 'org_rthk',
    displayName: '香港电台',
    englishName: 'RTHK',
    disguisedNames: ['电台', '广播处', '公营广播'],
    organizationType: 'public_service',
    activeYears: { from: 1928, to: 1997 },
    publicKnowledge: '公营广播机构，新闻、公共事务和广播节目让政府声音与市民意见同时出现。',
    promptSafeProfile: '香港电台不像商业电视台那样追逐明星，却常在公共议题上留下可查的声音记录。',
    headquartersPlaceIds: ['place_rthk_broadcasting_house'],
    territoryPlaceIds: ['place_broadcast_drive', 'place_rthk_broadcasting_house'],
    relatedOrganizationIds: ['org_tvb', 'org_ming_pao', 'org_government_house'],
    sectorTags: ['broadcasting', 'public_service', 'media'],
    influence: 78,
    defaultVisibility: 'public',
    sourceConfidence: 'high'
  }
];
