import type { EraSeedFigureCard } from './eraSeedFigureTypes';
import { hkLateColonialEntertainmentFigureExpansion } from './hkLateColonialEntertainmentFigureExpansion';

type SeedInput = Omit<
  EraSeedFigureCard,
  'type' | 'identityHooks' | 'copyRisk' | 'sourceConfidence' | 'importance'
> &
  Partial<Pick<EraSeedFigureCard, 'copyRisk' | 'sourceConfidence' | 'importance'>>;

const publicFigureNamesBySeedId: Record<string, string[]> = {
  fig_lian_jit_action_star: ['李连杰', 'Jet Li'],
  fig_dragon_big_brother_action_comic: ['成龙', 'Jackie Chan'],
  fig_fat_gor_brooding_lead: ['周润发', 'Chow Yun-fat', 'Chow Yun Fat'],
  fig_sing_chi_comedy_runner: ['周星驰', 'Stephen Chow'],
  fig_gor_gor_glass_singer_actor: ['张国荣', 'Leslie Cheung'],
  fig_mui_sister_stage_queen: ['梅艳芳', 'Anita Mui'],
  fig_wah_diligent_idol: ['刘德华', 'Andy Lau'],
  fig_maggie_screen_chameleon: ['张曼玉', 'Maggie Cheung'],
  fig_red_chung_glamour_star: ['钟楚红', 'Cherie Chung'],
  fig_blue_lam_cloud_swordswoman: ['林青霞', 'Brigitte Lin'],
  fig_sally_yip_power_vocal: ['叶倩文', 'Sally Yeh'],
  fig_jacky_crooner_rising: ['张学友', 'Jacky Cheung'],
  fig_alan_arena_king: ['谭咏麟', 'Alan Tam'],
  fig_leon_tv_idol: ['黎明', 'Leon Lai'],
  fig_aaron_dance_rookie: ['郭富城', 'Aaron Kwok'],
  fig_sandy_city_voice: ['林忆莲', 'Sandy Lam'],
  fig_priscilla_campus_voice: ['陈慧娴', 'Priscilla Chan'],
  fig_danny_melancholy_singer: ['陈百强', 'Danny Chan'],
  fig_sam_hui_canto_pop_founder: ['许冠杰', 'Sam Hui'],
  fig_george_lam_moustache_voice: ['林子祥', 'George Lam'],
  fig_dodo_cheng_sharp_tv_sister: ['郑裕玲', 'Carol Cheng'],
  fig_liza_wang_civic_tv_diva: ['汪明荃', 'Liza Wang'],
  fig_lydia_sum_happy_host: ['沈殿霞', 'Lydia Shum'],
  fig_eric_tsang_host_producer: ['曾志伟', 'Eric Tsang'],
  fig_tony_leung_quiet_tv_lead: ['梁朝伟', 'Tony Leung'],
  fig_sean_lau_plainclothes_actor: ['刘青云', 'Sean Lau'],
  fig_francis_edge_actor: ['吴镇宇', 'Francis Ng'],
  fig_simon_yam_model_actor: ['任达华', 'Simon Yam'],
  fig_carina_lau_tv_film_bridge: ['刘嘉玲', 'Carina Lau'],
  fig_rosamund_kwan_beauty_icon: ['关之琳', 'Rosamund Kwan'],
  fig_michelle_yeo_action_queen: ['杨紫琼', 'Michelle Yeoh'],
  fig_moon_lee_fighting_girl: ['李赛凤', 'Moon Lee'],
  fig_action_policewoman_star: ['杨丽菁', 'Cynthia Khan'],
  fig_sammo_hung_action_big_brother: ['洪金宝', 'Sammo Hung'],
  fig_yuen_biao_agile_stunt_star: ['元彪', 'Yuen Biao'],
  fig_lam_ching_ying_taoist_star: ['林正英', 'Lam Ching-ying'],
  fig_wu_ma_ghost_actor_director: ['午马', 'Wu Ma'],
  fig_michael_hui_satire_comic: ['许冠文', 'Michael Hui'],
  fig_ricky_hui_deadpan_comic: ['许冠英', 'Ricky Hui'],
  fig_ng_man_tat_golden_support: ['吴孟达', 'Ng Man-tat'],
  fig_tsui_hark_new_wave_director: ['徐克', 'Tsui Hark'],
  fig_john_woo_bullet_brotherhood: ['吴宇森', 'John Woo'],
  fig_ringo_lam_city_fire_director: ['林岭东', 'Ringo Lam'],
  fig_ann_hui_social_director: ['许鞍华', 'Ann Hui'],
  fig_stanley_kwan_melodrama_director: ['关锦鹏', 'Stanley Kwan'],
  fig_wong_kar_way_slow_neon_director: ['王家卫', 'Wong Kar-wai', 'Wong Kar Wai'],
  fig_wong_jing_fast_director: ['王晶', 'Wong Jing'],
  fig_ching_siu_tung_wirework_director: ['程小东', 'Ching Siu-tung'],
  fig_yuen_woo_ping_action_master: ['袁和平', 'Yuen Woo-ping'],
  fig_corey_yuen_action_director: ['元奎', 'Corey Yuen'],
  fig_lau_kar_leung_martial_master: ['刘家良', 'Lau Kar-leung'],
  fig_ti_lung_old_school_hero: ['狄龙', 'Ti Lung'],
  fig_david_chiang_classic_swordsman: ['姜大卫', 'David Chiang'],
  fig_gordon_liu_monk_fighter: ['刘家辉', 'Gordon Liu'],
  fig_mabel_cheung_migration_director: ['张婉婷', 'Mabel Cheung'],
  fig_alex_law_writer_director: ['罗启锐', 'Alex Law'],
  fig_tam_kar_ming_modernist: ['谭家明', 'Patrick Tam'],
  fig_beyond_rooftop_band: ['Beyond乐队', 'Beyond'],
  fig_cha_sir_wuxia_publisher: ['金庸', '查良镛', 'Jin Yong', 'Louis Cha'],
  fig_gu_lung_wine_swordsman: ['古龙', 'Gu Long'],
  fig_ni_kuang_sci_fi_writer: ['倪匡', 'Ni Kuang'],
  fig_leung_yu_sang_sword_serialist: ['梁羽生', 'Liang Yusheng'],
  fig_yi_shu_city_novelist: ['亦舒', 'Yi Shu'],
  fig_james_wong_lyric_trickster: ['黄霑', 'James Wong'],
  fig_choy_lam_food_film_critic: ['蔡澜', 'Chua Lam'],
  fig_lam_yin_nee_columnist: ['林燕妮', 'Eunice Lam'],
  fig_film_critic_roka_archive: ['罗卡', 'Law Kar'],
  fig_choi_manager_shadow: ['蔡子明', 'Choi Chi-ming'],
  fig_six_uncle_tv_tycoon: ['邵逸夫', 'Run Run Shaw'],
  fig_golden_harvest_big_boss: ['邹文怀', 'Raymond Chow'],
  fig_cinema_chain_lady_boss: ['方逸华', 'Mona Fong']
};

function publicFigureIdentity(seedId: string): {
  displayName: string;
  englishName?: string;
  alternateNames: string[];
} | undefined {
  const names = publicFigureNamesBySeedId[seedId];
  if (!names?.length) return undefined;

  const chineseNames = names.filter((name) => /\p{Script=Han}/u.test(name));
  const englishNames = names.filter((name) => !/\p{Script=Han}/u.test(name));
  const displayName = chineseNames[0] ?? names[0]!;
  const englishName = englishNames[0];

  return {
    displayName,
    ...(englishName ? { englishName } : {}),
    alternateNames: names.filter((name) => name !== displayName && name !== englishName)
  };
}

function canonicalRecognitionAliases(input: SeedInput, identity: ReturnType<typeof publicFigureIdentity>): string[] {
  const canonicalNames = new Set([identity?.displayName, identity?.englishName].filter(Boolean));
  return Array.from(new Set([...input.recognitionAliases, ...(identity?.alternateNames ?? [])])).filter(
    (alias) => !canonicalNames.has(alias)
  );
}

function identityHooks(displayName: string, role: string): EraSeedFigureCard['identityHooks'] {
  return {
    police: `可通过报案、片场纠纷、合约争议、记者线索或保护安排接触${displayName}；不要默认本人在场。`,
    civilian: `可通过工作、邻里、报馆、片场、粉丝、夜场或亲友关系听到${displayName}的消息。`,
    gang_member: `可通过投资、保护费、债务、片场秩序、夜场人脉或经纪合约牵连${displayName}。`
  };
}

function seed(input: SeedInput): EraSeedFigureCard {
  const publicIdentity = publicFigureIdentity(input.id);
  const displayName = publicIdentity?.displayName ?? input.displayName;
  return {
    type: 'EraSeedFigureCard',
    identityHooks: identityHooks(displayName, input.publicRole),
    copyRisk: input.copyRisk ?? 'medium',
    sourceConfidence: input.sourceConfidence ?? 'medium',
    importance: input.importance ?? 70,
    ...input,
    displayName,
    ...(publicIdentity?.englishName ? { englishName: publicIdentity.englishName } : {}),
    recognitionAliases: canonicalRecognitionAliases(input, publicIdentity),
    canonicalSeedId: input.canonicalSeedId ?? input.id,
    protectedRealNames: []
  };
}

const hkLateColonialCoreEraSeedFigures: EraSeedFigureCard[] = [
  seed({
    id: 'fig_lian_jit_action_star',
    displayName: '李连杰',
    category: 'entertainment',
    sectors: ['film', 'action', 'martial_arts'],
    activeYears: { from: 1982, to: 1998 },
    recognitionAliases: ['北派功夫明星', '武术冠军出身的银幕新星'],
    publicRole: '北派武术出身的年轻动作明星',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest', 'place_kln_tang_tvb_city'],
    accessRoutes: ['经纪人安排', '动作片片场', '武指班底', '电影公司合约纠纷'],
    promptSafeProfile:
      '年轻功夫明星，动作干净凌厉，背后有经纪人、武指班底和片商压力；他本人不一定懂江湖，但围着他的合约、片酬和人身安全足以牵出大案。',
    promptSafeHooks: ['功夫明星被迫接片', '经纪人受威胁', '片场保镖临时换人'],
    eraTags: ['功夫片', '经纪人', '合约', '片场'],
    contactPolicy: 'contactable_seed',
    importance: 95,
    sourceConfidence: 'high'
  }),
  seed({
    id: 'fig_dragon_big_brother_action_comic',
    displayName: '成龙',
    category: 'entertainment',
    sectors: ['film', 'action', 'stunt'],
    activeYears: { from: 1978, to: 1998 },
    recognitionAliases: ['龙哥', '成家班大佬', '拼命喜剧动作明星'],
    publicRole: '以亲身特技和喜剧动作闻名的巨星',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['成家班武师', '保险公司事故调查', '戏院宣传活动', '片场工伤'],
    promptSafeProfile:
      '极受欢迎的动作喜剧巨星，片场像一个小江湖，武师、保险、投资人和记者都围着他转；真正可用的是他的班底和行业影响，不要把他写成随便可见的普通 NPC。',
    promptSafeHooks: ['危险特技受伤', '班底替人出头', '宣传活动遇袭'],
    eraTags: ['动作喜剧', '武师班', '工伤', '巨星'],
    contactPolicy: 'contactable_seed',
    importance: 96,
    sourceConfidence: 'high'
  }),
  seed({
    id: 'fig_fat_gor_brooding_lead',
    displayName: '周润发',
    category: 'entertainment',
    sectors: ['film', 'tv', 'star'],
    activeYears: { from: 1976, to: 1998 },
    recognitionAliases: ['发哥', '长风衣影帝', '义气银幕大佬', 'Chow Yun Fat'],
    publicRole: '从电视走向电影的顶级男星',
    usualPlaceIds: ['place_kln_tang_tvb_city', 'place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['电视台旧同事', '电影宣传', '片场探班', '记者蹲守'],
    promptSafeProfile:
      '银幕上有江湖义气气质的男星，公众形象成熟可靠；围绕他的传闻常与片约、兄弟气、夜场应酬和记者追访有关。',
    promptSafeHooks: ['旧同事求助', '宣传夜被人跟踪', '江湖气质被现实误读'],
    eraTags: ['电影男星', '电视台', '记者', '义气'],
    contactPolicy: 'contactable_seed',
    importance: 94
  }),
  seed({
    id: 'fig_sing_chi_comedy_runner',
    displayName: '周星驰',
    category: 'entertainment',
    sectors: ['film', 'tv', 'comedy'],
    activeYears: { from: 1983, to: 1998 },
    recognitionAliases: ['星仔', '周星', '训练班出身喜剧仔', '无厘头新人'],
    publicRole: '从儿童节目和小角色冒头的喜剧演员',
    usualPlaceIds: ['place_kln_tang_tvb_city', 'place_kln_tang_broadcast_drive'],
    accessRoutes: ['电视城跑通告', '小剧组临时演员', '更衣室闲谈', '编剧朋友'],
    promptSafeProfile:
      '尚未完全爆红的喜剧演员，脑子快、嘴快，常在边角位置听到大人物不愿让人听见的话；适合作为线索入口，不适合开局固定绑定。',
    promptSafeHooks: ['临时演员听到秘密', '喜剧桥段误撞真案', '片场小人物被低估'],
    eraTags: ['喜剧', '电视城', '临时演员'],
    contactPolicy: 'contactable_seed',
    importance: 87
  }),
  seed({
    id: 'fig_gor_gor_glass_singer_actor',
    displayName: '张国荣',
    category: 'entertainment',
    sectors: ['music', 'film', 'star'],
    activeYears: { from: 1977, to: 1998 },
    recognitionAliases: ['哥哥', '荣哥', '玻璃声线男星', '舞台与银幕两栖明星'],
    publicRole: '歌影视两栖的顶级明星',
    usualPlaceIds: ['place_kln_tang_broadcast_drive', 'place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['演唱会后台', '唱片公司', '电影宣传', '夜场熟人'],
    promptSafeProfile:
      '拥有强烈舞台魅力和敏感气质的男星，身边有歌迷、记者、经理人和旧日朋友；他的出现应像城市传闻或高门槛接触。',
    promptSafeHooks: ['后台收到威胁信', '歌迷递来线索', '旧友用明星关系挡事'],
    eraTags: ['歌手', '电影', '后台', '记者'],
    contactPolicy: 'contactable_seed',
    importance: 94
  }),
  seed({
    id: 'fig_mui_sister_stage_queen',
    displayName: '梅艳芳',
    category: 'entertainment',
    sectors: ['music', 'film', 'nightlife'],
    activeYears: { from: 1982, to: 1998 },
    recognitionAliases: ['梅姐', '舞台女王', '百变歌姬'],
    publicRole: '舞台表现极强的女歌星和演员',
    usualPlaceIds: ['place_kln_tang_broadcast_drive', 'place_mong_kok_portland_street'],
    accessRoutes: ['演唱会后台', '夜场旧识', '慈善晚会', '唱片公司'],
    promptSafeProfile:
      '从舞台和夜场生态中走出的女王级人物，仗义、敏锐、见过底层；她能成为娱乐圈与街头之间的高价值桥梁。',
    promptSafeHooks: ['后台替人出头', '慈善晚会暗账', '夜场旧识求救'],
    eraTags: ['歌坛', '舞台', '夜场', '义气'],
    contactPolicy: 'contactable_seed',
    importance: 94
  }),
  seed({
    id: 'fig_wah_diligent_idol',
    displayName: '刘德华',
    category: 'entertainment',
    sectors: ['film', 'music', 'tv'],
    activeYears: { from: 1981, to: 1998 },
    recognitionAliases: ['华仔', '勤力偶像', '训练班靓仔'],
    publicRole: '勤奋高产的偶像演员和歌手',
    usualPlaceIds: ['place_kln_tang_tvb_city', 'place_kln_tang_broadcast_drive'],
    accessRoutes: ['电视台旧同学', '唱片宣传', '影迷会', '片场通告'],
    promptSafeProfile:
      '形象正面、工作极密的偶像明星，身边总有影迷、经理人、宣传和同门；适合牵出粉丝、合约、旧同学和宣传事故。',
    promptSafeHooks: ['影迷会出现异常', '宣传车被跟踪', '训练班旧友涉案'],
    eraTags: ['偶像', '电视城', '影迷', '唱片'],
    contactPolicy: 'contactable_seed',
    importance: 92
  }),
  seed({
    id: 'fig_maggie_screen_chameleon',
    displayName: '张曼玉',
    category: 'entertainment',
    sectors: ['film', 'tv', 'fashion'],
    activeYears: { from: 1983, to: 1998 },
    recognitionAliases: ['曼玉姐', '银幕变色龙', '选美出身女星'],
    publicRole: '从选美和电视进入电影圈的女演员',
    usualPlaceIds: ['place_kln_tang_tvb_city', 'place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['造型间', '电视城通告', '电影宣传', '杂志拍摄'],
    promptSafeProfile:
      '公众熟悉的女演员，外界常低估她的观察力；可作为时装、杂志、片场与女性处境的入口。',
    promptSafeHooks: ['造型师发现血迹', '杂志访问听到假供词', '女星被合约困住'],
    eraTags: ['女演员', '选美', '杂志', '片场'],
    contactPolicy: 'contactable_seed',
    importance: 94
  }),
  seed({
    id: 'fig_red_chung_glamour_star',
    displayName: '钟楚红',
    category: 'entertainment',
    sectors: ['film', 'star'],
    activeYears: { from: 1979, to: 1998 },
    recognitionAliases: ['红姑', '红裙女神', '都市电影女星'],
    publicRole: '极具都市魅力的电影女星',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['电影公司', '广告拍摄', '记者会', '时装活动'],
    promptSafeProfile:
      '光彩照人的都市女星，常出入广告、片场和慈善场合；她身边的司机、摄影助理、化妆师可能比本人更容易接触。',
    promptSafeHooks: ['广告拍摄被勒索', '司机失踪', '记者会收到奇怪花篮'],
    eraTags: ['电影女星', '广告', '记者会'],
    contactPolicy: 'contactable_seed',
    importance: 96
  }),
  seed({
    id: 'fig_blue_lam_cloud_swordswoman',
    displayName: '林青霞',
    category: 'entertainment',
    sectors: ['film', 'martial_arts', 'star'],
    activeYears: { from: 1973, to: 1998 },
    recognitionAliases: ['青霞姐', '雌雄难辨的银幕侠影', '云上女侠'],
    publicRole: '华语影坛标志性女星',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['大型电影项目', '武侠片造型间', '跨地宣传', '杂志访问'],
    promptSafeProfile:
      '银幕气质极强的女星，常被安排在大制作和武侠类型中；她是文化符号，直接接触应稀有，更多通过片方、造型师、记者和粉丝体现。',
    promptSafeHooks: ['武侠造型照外泄', '跨地宣传被人盯梢', '片方争夺档期'],
    eraTags: ['武侠片', '女星', '造型', '宣传'],
    contactPolicy: 'contactable_seed',
    importance: 95
  }),
  seed({
    id: 'fig_sally_yip_power_vocal',
    displayName: '叶倩文',
    category: 'entertainment',
    sectors: ['music', 'film'],
    activeYears: { from: 1980, to: 1998 },
    recognitionAliases: ['莎莉姐', '高亢女声', '电影主题曲女歌手'],
    publicRole: '以强烈声线和电影歌曲闻名的歌手',
    usualPlaceIds: ['place_kln_tang_broadcast_drive'],
    accessRoutes: ['录音室', '电台访问', '电影主题曲宣传', '唱片公司'],
    promptSafeProfile:
      '歌声极有辨识度的女歌手，常连接电影主题曲、唱片公司和电台宣传；适合牵出电台点歌、录音室深夜事故。',
    promptSafeHooks: ['录音室停电后多了一段声音', '电台点歌传信', '唱片母带被调包'],
    eraTags: ['歌手', '录音室', '电台'],
    contactPolicy: 'contactable_seed',
    importance: 78
  }),
  seed({
    id: 'fig_jacky_crooner_rising',
    displayName: '张学友',
    category: 'entertainment',
    sectors: ['music', 'film'],
    activeYears: { from: 1984, to: 1998 },
    recognitionAliases: ['学友仔', '新晋唱将', '靓声新人'],
    publicRole: '正在快速上升的男歌手',
    usualPlaceIds: ['place_kln_tang_broadcast_drive'],
    accessRoutes: ['歌唱比赛旧档案', '电台访问', '唱片公司', '校园演出'],
    promptSafeProfile:
      '唱功突出、仍在上升期的男歌手，适合连接比赛、唱片合约、校园演出和粉丝信件。',
    promptSafeHooks: ['粉丝信夹带线索', '比赛旧档案被偷', '校园演出有人失踪'],
    eraTags: ['歌手', '比赛', '粉丝', '唱片'],
    contactPolicy: 'contactable_seed',
    importance: 78
  }),
  seed({
    id: 'fig_alan_arena_king',
    displayName: '谭咏麟',
    category: 'entertainment',
    sectors: ['music', 'concert'],
    activeYears: { from: 1978, to: 1998 },
    recognitionAliases: ['阿伦', '谭校长', '歌坛校长', '红馆常客'],
    publicRole: '大型演唱会和流行歌坛核心人物',
    usualPlaceIds: ['place_kln_tang_broadcast_drive'],
    accessRoutes: ['演唱会后台', '歌迷会', '电台宣传', '唱片公司'],
    promptSafeProfile:
      '歌坛号召力极强的男歌手，演唱会后台人多复杂；适合出现黄牛票、后台失窃、歌迷会纠纷。',
    promptSafeHooks: ['黄牛票牵出社团', '后台通行证被复制', '歌迷会资金不明'],
    eraTags: ['歌坛', '演唱会', '黄牛'],
    contactPolicy: 'contactable_seed',
    importance: 82
  }),
  seed({
    id: 'fig_leon_tv_idol',
    displayName: '黎明',
    category: 'entertainment',
    sectors: ['tv', 'music', 'idol'],
    activeYears: { from: 1986, to: 1998 },
    recognitionAliases: ['阿明', '电台选秀靓仔', '新晋偶像'],
    publicRole: '电视和歌坛之间冒头的新人',
    usualPlaceIds: ['place_kln_tang_tvb_city', 'place_kln_tang_broadcast_drive'],
    accessRoutes: ['新秀比赛', '电视城', '唱片公司', '粉丝会'],
    promptSafeProfile:
      '仍在上升的新晋偶像，最适合用作新人被抢约、粉丝聚集、公司包装压力的种子。',
    promptSafeHooks: ['新秀比赛资料被动过', '粉丝堵门', '经纪公司抢人'],
    eraTags: ['偶像', '新秀', '电视城'],
    contactPolicy: 'contactable_seed',
    importance: 72
  }),
  seed({
    id: 'fig_aaron_dance_rookie',
    displayName: '郭富城',
    category: 'entertainment',
    sectors: ['dance', 'music', 'tv'],
    activeYears: { from: 1987, to: 1998 },
    recognitionAliases: ['城城仔', '跳舞新人', '伴舞班靓仔'],
    publicRole: '舞蹈和电视训练出身的新人',
    usualPlaceIds: ['place_kln_tang_tvb_city'],
    accessRoutes: ['舞蹈排练室', '电视城训练班', '广告试镜', '伴舞通告'],
    promptSafeProfile:
      '跳舞底子很强的新人，尚未完全成名；他更适合通过训练班、广告试镜和伴舞圈出现。',
    promptSafeHooks: ['排练室有人藏东西', '广告试镜名单被换', '伴舞听见后台争执'],
    eraTags: ['舞蹈', '新人', '电视城'],
    contactPolicy: 'contactable_seed',
    importance: 68
  }),
  seed({
    id: 'fig_sandy_city_voice',
    displayName: '林忆莲',
    category: 'entertainment',
    sectors: ['music', 'radio'],
    activeYears: { from: 1985, to: 1998 },
    recognitionAliases: ['都市女声', '电台出来的歌手', '夜色唱腔'],
    publicRole: '带都市感的女歌手',
    usualPlaceIds: ['place_kln_tang_broadcast_drive'],
    accessRoutes: ['电台节目', '录音室', '唱片公司', '夜间宣传'],
    promptSafeProfile:
      '声音有都市夜色质感的女歌手，适合接入电台、录音室、夜间节目和情感热线。',
    promptSafeHooks: ['深夜节目收到求救', '录音带里有背景声', '唱片公司压下新闻'],
    eraTags: ['都市音乐', '电台', '录音室'],
    contactPolicy: 'contactable_seed',
    importance: 72
  }),
  seed({
    id: 'fig_priscilla_campus_voice',
    displayName: '陈慧娴',
    category: 'entertainment',
    sectors: ['music', 'school'],
    activeYears: { from: 1983, to: 1998 },
    recognitionAliases: ['慧娴妹', '校园女声', '清亮歌姬', '学生歌迷偶像'],
    publicRole: '校园气质强烈的女歌手',
    usualPlaceIds: ['place_kln_tang_broadcast_drive'],
    accessRoutes: ['校园演出', '唱片店', '电台访问', '歌迷来信'],
    promptSafeProfile:
      '干净校园气质的女歌手，常被学生歌迷包围；适合牵出校园、唱片店、来信和演出安全。',
    promptSafeHooks: ['歌迷来信指向失踪学生', '校园演出被勒索', '唱片店老板认出可疑人'],
    eraTags: ['校园', '歌手', '歌迷'],
    contactPolicy: 'contactable_seed',
    importance: 70
  }),
  seed({
    id: 'fig_danny_melancholy_singer',
    displayName: '陈百强',
    category: 'entertainment',
    sectors: ['music', 'film'],
    activeYears: { from: 1979, to: 1998 },
    recognitionAliases: ['百强仔', '忧郁唱作人', '钢琴男声'],
    publicRole: '带忧郁气质的唱作歌手',
    usualPlaceIds: ['place_kln_tang_broadcast_drive'],
    accessRoutes: ['录音室', '电台节目', '私人聚会', '唱片公司'],
    promptSafeProfile:
      '气质内敛的唱作歌手，适合引出私人聚会、情绪危机、唱片合约和媒体追访。',
    promptSafeHooks: ['私人派对有人昏迷', '歌词手稿被偷', '记者过度追访'],
    eraTags: ['唱作', '私人聚会', '媒体'],
    contactPolicy: 'contactable_seed',
    importance: 74
  }),
  seed({
    id: 'fig_sam_hui_canto_pop_founder',
    displayName: '许冠杰',
    category: 'entertainment',
    sectors: ['music', 'film', 'comedy'],
    activeYears: { from: 1971, to: 1998 },
    recognitionAliases: ['市民歌王', '鬼马兄弟之一'],
    publicRole: '粤语流行歌和市民喜剧的重要人物',
    usualPlaceIds: ['place_kln_tang_broadcast_drive', 'place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['电视台旧档', '唱片公司', '喜剧片片场', '电台访问'],
    promptSafeProfile:
      '把市民口语带进流行歌和喜剧的人物，适合连接旧电视、唱片、茶餐厅民生和喜剧片时代。',
    promptSafeHooks: ['旧节目带出失踪艺人', '市民歌被改成暗号', '喜剧片道具被调包'],
    eraTags: ['粤语歌', '喜剧', '市民文化'],
    contactPolicy: 'contactable_seed',
    importance: 82
  }),
  seed({
    id: 'fig_george_lam_moustache_voice',
    displayName: '林子祥',
    category: 'entertainment',
    sectors: ['music', 'film'],
    activeYears: { from: 1976, to: 1998 },
    recognitionAliases: ['阿Lam', '胡子高音', '都市男声'],
    publicRole: '声音强烈的男歌手和演员',
    usualPlaceIds: ['place_kln_tang_broadcast_drive'],
    accessRoutes: ['录音室', '电台访问', '电影主题曲', '音乐人饭局'],
    promptSafeProfile:
      '有强烈嗓音和音乐人气质的男歌手，适合接入录音室、主题曲、音乐人饭局和版权争议。',
    promptSafeHooks: ['主题曲版权纠纷', '录音室外有人守候', '音乐人饭局提到旧案'],
    eraTags: ['歌手', '主题曲', '版权'],
    contactPolicy: 'contactable_seed',
    importance: 74
  }),
  seed({
    id: 'fig_dodo_cheng_sharp_tv_sister',
    displayName: '郑裕玲',
    category: 'entertainment',
    sectors: ['tv', 'hosting', 'film'],
    activeYears: { from: 1976, to: 1998 },
    recognitionAliases: ['嘟姐', '机敏女主持', '电视台大姐'],
    publicRole: '反应极快的电视主持和演员',
    usualPlaceIds: ['place_kln_tang_tvb_city'],
    accessRoutes: ['电视台走廊', '访问节目', '颁奖礼后台', '艺员饭堂'],
    promptSafeProfile:
      '在电视台人脉很广、反应很快的女主持，能听懂台面话背后的意思；适合作为媒体圈信息节点。',
    promptSafeHooks: ['访问前嘉宾失踪', '后台名单被换', '主持人听出供词破绽'],
    eraTags: ['主持', '电视台', '后台'],
    contactPolicy: 'contactable_seed',
    importance: 78
  }),
  seed({
    id: 'fig_liza_wang_civic_tv_diva',
    displayName: '汪明荃',
    category: 'entertainment',
    sectors: ['tv', 'music', 'public_affairs'],
    activeYears: { from: 1967, to: 1998 },
    recognitionAliases: ['汪姐', '阿姐', '电视台女台柱', '台庆大姐'],
    publicRole: '电视台台柱级女艺人',
    usualPlaceIds: ['place_kln_tang_tvb_city', 'place_kln_tang_broadcast_drive'],
    accessRoutes: ['台庆后台', '公益活动', '电视台高层走廊', '艺员训练班'],
    promptSafeProfile:
      '台柱级女艺人，连接电视台、公益、公众活动和高层礼节；适合出现在大型晚会、制度压力和艺人保护场景。',
    promptSafeHooks: ['公益晚会善款争议', '台庆后台有人闹事', '高层要求压下新闻'],
    eraTags: ['电视台', '公益', '台庆'],
    contactPolicy: 'contactable_seed',
    importance: 84
  }),
  seed({
    id: 'fig_lydia_sum_happy_host',
    displayName: '沈殿霞',
    category: 'entertainment',
    sectors: ['tv', 'hosting', 'comedy'],
    activeYears: { from: 1967, to: 1998 },
    recognitionAliases: ['肥姐', '开心果大姐', '圆眼镜主持', '综艺台柱'],
    publicRole: '综艺主持和喜剧气氛核心',
    usualPlaceIds: ['place_kln_tang_tvb_city'],
    accessRoutes: ['综艺后台', '艺员饭堂', '慈善节目', '电视台旧人脉'],
    promptSafeProfile:
      '表面热闹亲切、实际知道很多台前幕后人情的主持人；适合让严肃案子从综艺后台或慈善节目切入。',
    promptSafeHooks: ['综艺后台听见哭声', '慈善节目账目不对', '艺员饭堂有人求她带话'],
    eraTags: ['综艺', '慈善', '电视台'],
    contactPolicy: 'contactable_seed',
    importance: 80
  }),
  seed({
    id: 'fig_eric_tsang_host_producer',
    displayName: '曾志伟',
    category: 'entertainment',
    sectors: ['tv', 'film', 'producer'],
    activeYears: { from: 1974, to: 1998 },
    recognitionAliases: ['志伟哥', '矮仔监制', '综艺电影双栖人'],
    publicRole: '横跨演员、主持和制作的圈内人',
    usualPlaceIds: ['place_kln_tang_tvb_city', 'place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['监制办公室', '综艺后台', '电影饭局', '艺人足球队'],
    promptSafeProfile:
      '人脉横跨电视、电影、综艺和饭局，消息灵通但话不一定直说；适合做娱乐圈人情网络节点。',
    promptSafeHooks: ['饭局上有人递名单', '足球队更衣室谈到债务', '监制办公室压新闻'],
    eraTags: ['监制', '主持', '饭局', '人脉'],
    contactPolicy: 'contactable_seed',
    importance: 82
  }),
  seed({
    id: 'fig_tony_leung_quiet_tv_lead',
    displayName: '梁朝伟',
    category: 'entertainment',
    sectors: ['tv', 'film', 'actor'],
    activeYears: { from: 1982, to: 1998 },
    recognitionAliases: ['伟仔', '安静眼神男星', '训练班男主角'],
    publicRole: '从电视训练班走出的细腻男演员',
    usualPlaceIds: ['place_kln_tang_tvb_city'],
    accessRoutes: ['电视城', '电影试镜', '训练班旧友', '剧组休息室'],
    promptSafeProfile:
      '不多话但观察细的年轻男演员，适合成为目击者、旧同学或剧组边角信息来源。',
    promptSafeHooks: ['试镜时看见不该来的人', '训练班旧友涉案', '休息室一段沉默成线索'],
    eraTags: ['演员', '训练班', '电视城'],
    contactPolicy: 'contactable_seed',
    importance: 78
  }),
  seed({
    id: 'fig_sean_lau_plainclothes_actor',
    displayName: '刘青云',
    category: 'entertainment',
    sectors: ['tv', 'film', 'actor'],
    activeYears: { from: 1984, to: 1998 },
    recognitionAliases: ['青云仔', '扎实电视演员', '平民脸男主'],
    publicRole: '从电视圈扎实冒头的男演员',
    usualPlaceIds: ['place_kln_tang_tvb_city'],
    accessRoutes: ['电视剧组', '外景队', '训练班同学', '艺员饭堂'],
    promptSafeProfile:
      '平实可靠的演员，适合被放在外景队、街坊角色和真实案件擦边处；容易让玩家相信他不是光鲜明星。',
    promptSafeHooks: ['外景队拍到真案', '街坊认错演员和嫌疑人', '艺员饭堂谈到失踪临记'],
    eraTags: ['电视演员', '外景', '临记'],
    contactPolicy: 'contactable_seed',
    importance: 70
  }),
  seed({
    id: 'fig_francis_edge_actor',
    displayName: '吴镇宇',
    category: 'entertainment',
    sectors: ['tv', 'film', 'actor'],
    activeYears: { from: 1986, to: 1998 },
    recognitionAliases: ['镇宇仔', '边缘气质演员', '反派眼神新人'],
    publicRole: '带危险气质的年轻演员',
    usualPlaceIds: ['place_kln_tang_tvb_city'],
    accessRoutes: ['配角试镜', '电视城走廊', '夜间外景', '临时演员圈'],
    promptSafeProfile:
      '有边缘和反派气质的演员，适合被误认、被利用或在夜间外景里撞见真事。',
    promptSafeHooks: ['演反派被街坊误认', '夜间外景撞见交易', '试镜名单里有假名'],
    eraTags: ['配角', '反派气质', '外景'],
    contactPolicy: 'contactable_seed',
    importance: 68
  }),
  seed({
    id: 'fig_simon_yam_model_actor',
    displayName: '任达华',
    category: 'entertainment',
    sectors: ['film', 'fashion', 'actor'],
    activeYears: { from: 1979, to: 1998 },
    recognitionAliases: ['达华哥', '模特出身男星', '冷面绅士'],
    publicRole: '模特和演员之间的冷面男星',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['广告棚', '时装活动', '电影试镜', '夜场熟人'],
    promptSafeProfile:
      '外形冷峻、常出入广告棚和时装活动的男演员，适合连接商业广告、夜场、摄影棚和上流派对。',
    promptSafeHooks: ['广告棚遗失底片', '时装活动有人勒索', '派对宾客名单异常'],
    eraTags: ['演员', '广告', '时装'],
    contactPolicy: 'contactable_seed',
    importance: 72
  }),
  seed({
    id: 'fig_carina_lau_tv_film_bridge',
    displayName: '刘嘉玲',
    category: 'entertainment',
    sectors: ['tv', 'film', 'star'],
    activeYears: { from: 1983, to: 1998 },
    recognitionAliases: ['嘉玲姐', '电视电影两栖女星', '派对圈女星'],
    publicRole: '从电视圈进入电影和社交场的女演员',
    usualPlaceIds: ['place_kln_tang_tvb_city', 'place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['电视台旧同事', '电影饭局', '时装派对', '记者跟拍'],
    promptSafeProfile:
      '社交圈能见度高的女演员，适合牵出派对名单、记者跟拍、片约压力和女性艺人安全。',
    promptSafeHooks: ['派对后有人失联', '记者底片被抢', '女星收到恐吓电话'],
    eraTags: ['女演员', '派对', '记者'],
    contactPolicy: 'contactable_seed',
    importance: 92
  }),
  seed({
    id: 'fig_rosamund_kwan_beauty_icon',
    displayName: '关之琳',
    category: 'entertainment',
    sectors: ['film', 'fashion', 'star'],
    activeYears: { from: 1981, to: 1998 },
    recognitionAliases: ['之琳姐', '古典美人', '时装广告女星'],
    publicRole: '高曝光的电影和广告女星',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['广告棚', '电影宣传', '珠宝品牌活动', '杂志访问'],
    promptSafeProfile:
      '经常与广告、珠宝、时装和电影宣传绑定的女星；可用于高价值赞助、珠宝失窃、记者跟拍。',
    promptSafeHooks: ['珠宝赞助失窃', '广告棚有人冒充助理', '杂志访问夹带暗示'],
    eraTags: ['广告', '珠宝', '女星'],
    contactPolicy: 'contactable_seed',
    importance: 95
  }),
  seed({
    id: 'fig_michelle_yeo_action_queen',
    displayName: '杨紫琼',
    category: 'entertainment',
    sectors: ['film', 'action', 'star'],
    activeYears: { from: 1983, to: 1998 },
    recognitionAliases: ['紫琼姐', '选美出身打女', '高难度女动作星'],
    publicRole: '能亲身完成高难度动作的女星',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['动作片片场', '保险调查', '武指班底', '选美旧人脉'],
    promptSafeProfile:
      '罕见的高强度女动作明星，片场安全、保险、武师班和性别偏见都能围绕她展开。',
    promptSafeHooks: ['女动作星受伤被压下', '保险调查牵出假合同', '武师班轻视她反被识破'],
    eraTags: ['打女', '动作片', '保险', '选美'],
    contactPolicy: 'contactable_seed',
    importance: 92
  }),
  seed({
    id: 'fig_moon_lee_fighting_girl',
    displayName: '李赛凤',
    category: 'entertainment',
    sectors: ['film', 'action'],
    activeYears: { from: 1983, to: 1998 },
    recognitionAliases: ['赛凤妹', '灵巧打女', '少女动作星'],
    publicRole: '灵巧型动作女演员',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['动作片片场', '武师训练场', '医院急症室', '戏服间'],
    promptSafeProfile:
      '年轻灵巧的动作女演员，常在危险动作和低预算片场之间奔走；适合牵出片场保护不足。',
    promptSafeHooks: ['戏服间藏着恐吓信', '急症室不敢报真实伤因', '低预算片场出事'],
    eraTags: ['打女', '片场工伤', '低预算'],
    contactPolicy: 'contactable_seed',
    importance: 92
  }),
  seed({
    id: 'fig_action_policewoman_star',
    displayName: '杨丽菁',
    category: 'entertainment',
    sectors: ['film', 'action', 'police_genre'],
    activeYears: { from: 1987, to: 1998 },
    recognitionAliases: ['丽菁姐', '警花动作星', '制服打女'],
    publicRole: '警匪动作片里的女动作演员',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['警匪片片场', '武指班底', '制服道具组', '医院'],
    promptSafeProfile:
      '常演警匪动作戏的女星，容易让真实警察、道具枪、制服和片场安全边界发生混淆。',
    promptSafeHooks: ['道具枪被换', '制服流入街头', '片场警察顾问发现漏洞'],
    eraTags: ['警匪片', '打女', '道具枪'],
    contactPolicy: 'contactable_seed',
    importance: 92
  }),
  seed({
    id: 'fig_sammo_hung_action_big_brother',
    displayName: '洪金宝',
    category: 'entertainment',
    sectors: ['film', 'action', 'stunt', 'producer'],
    activeYears: { from: 1970, to: 1998 },
    recognitionAliases: ['洪大哥', '三毛大哥', '灵活胖武师', '动作班主'],
    publicRole: '动作片班主级演员和导演',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['武师班', '动作片片场', '饭局', '保险事故'],
    promptSafeProfile:
      '动作片班主级人物，身边有武师、兄弟、投资人和伤病；可作为片场秩序和武师江湖的关键锚点。',
    promptSafeHooks: ['武师兄弟顶罪', '片场事故被改口', '饭局谈出投资黑洞'],
    eraTags: ['武师', '导演', '动作片', '班主'],
    contactPolicy: 'contactable_seed',
    importance: 88
  }),
  seed({
    id: 'fig_yuen_biao_agile_stunt_star',
    displayName: '元彪',
    category: 'entertainment',
    sectors: ['film', 'action', 'stunt'],
    activeYears: { from: 1972, to: 1998 },
    recognitionAliases: ['敏捷师兄弟', '翻腾动作星', '戏班出身武师'],
    publicRole: '以敏捷和高难动作闻名的武师演员',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['武师班', '动作排练', '医院', '旧戏班人脉'],
    promptSafeProfile:
      '敏捷型武师演员，适合接入旧戏班、动作排练、工伤和师兄弟义气。',
    promptSafeHooks: ['动作排练发现陌生人', '师兄弟替人隐瞒伤因', '旧戏班名单牵出债务'],
    eraTags: ['武师', '戏班', '工伤'],
    contactPolicy: 'contactable_seed',
    importance: 76
  }),
  seed({
    id: 'fig_lam_ching_ying_taoist_star',
    displayName: '林正英',
    category: 'entertainment',
    sectors: ['film', 'action', 'ghost_comedy'],
    activeYears: { from: 1970, to: 1998 },
    recognitionAliases: ['英叔', '道袍师傅', '僵尸片师傅'],
    publicRole: '以民俗动作喜剧形象闻名的演员和武指',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['民俗片片场', '武师班', '旧楼外景', '道具组'],
    promptSafeProfile:
      '道袍师傅形象深入民心，现实里是武指和演员；适合让迷信、道具、旧楼外景和真实尸案形成错位。',
    promptSafeHooks: ['道具符纸夹着真地址', '旧楼外景挖出尸骨', '群众把演员当法师求助'],
    eraTags: ['民俗片', '武指', '旧楼'],
    contactPolicy: 'contactable_seed',
    importance: 78
  }),
  seed({
    id: 'fig_wu_ma_ghost_actor_director',
    displayName: '午马',
    category: 'entertainment',
    sectors: ['film', 'director', 'ghost_comedy'],
    activeYears: { from: 1963, to: 1998 },
    recognitionAliases: ['马叔', '鬼片老戏骨', '片场老江湖'],
    publicRole: '演员、导演和片场老江湖',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['鬼片片场', '副导演组', '旧片仓', '夜间外景'],
    promptSafeProfile:
      '懂片场规矩的老江湖，常在鬼片、旧片仓和夜外景里出现；他知道哪些怪事是道具，哪些不是。',
    promptSafeHooks: ['旧片仓胶片拍到不该出现的人', '夜外景群演失踪', '老戏骨认出假道具'],
    eraTags: ['鬼片', '老戏骨', '片仓'],
    contactPolicy: 'contactable_seed',
    importance: 70
  }),
  seed({
    id: 'fig_michael_hui_satire_comic',
    displayName: '许冠文',
    category: 'entertainment',
    sectors: ['film', 'comedy', 'writer'],
    activeYears: { from: 1972, to: 1998 },
    recognitionAliases: ['许氏大哥', '市民讽刺喜剧人', '冷面笑匠'],
    publicRole: '市民讽刺喜剧代表人物',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['喜剧片编剧室', '广告公司', '戏院宣传', '报纸专访'],
    promptSafeProfile:
      '擅长把小市民困境拍成喜剧的人物，适合把劳资、地产、保险、办公室压迫转成带刺的案件入口。',
    promptSafeHooks: ['喜剧桥段来自真实投诉', '广告公司藏着诈骗文案', '戏院宣传遇到抗议'],
    eraTags: ['喜剧', '小市民', '讽刺'],
    contactPolicy: 'contactable_seed',
    importance: 78
  }),
  seed({
    id: 'fig_ricky_hui_deadpan_comic',
    displayName: '许冠英',
    category: 'entertainment',
    sectors: ['film', 'comedy'],
    activeYears: { from: 1972, to: 1998 },
    recognitionAliases: ['冠英仔', '苦瓜脸喜剧人', '许氏兄弟之一', '倒霉小人物'],
    publicRole: '以小人物倒霉感见长的喜剧演员',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['喜剧片片场', '临记圈', '戏院门口', '茶餐厅'],
    promptSafeProfile:
      '常演倒霉小人物的喜剧演员，适合让玩家从片场边角、临记、茶餐厅听见城市底层消息。',
    promptSafeHooks: ['临记拿错道具包', '茶餐厅听到真案原型', '戏院门口有人闹事'],
    eraTags: ['喜剧', '临记', '茶餐厅'],
    contactPolicy: 'contactable_seed',
    importance: 66
  }),
  seed({
    id: 'fig_ng_man_tat_golden_support',
    displayName: '吴孟达',
    category: 'entertainment',
    sectors: ['tv', 'film', 'supporting_actor'],
    activeYears: { from: 1973, to: 1998 },
    recognitionAliases: ['达叔', '黄金配角', '欠债旧闻演员'],
    publicRole: '极有市井味的配角演员',
    usualPlaceIds: ['place_kln_tang_tvb_city', 'place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['电视台饭堂', '临记圈', '小制作片场', '债主传闻'],
    promptSafeProfile:
      '配角身份使他更接近市井和剧组底层，适合牵出债务、临记、片场小人物和人情债。',
    promptSafeHooks: ['债主追到片场', '配角听见主角不该说的话', '临记求他带话'],
    eraTags: ['配角', '债务', '市井'],
    contactPolicy: 'contactable_seed',
    importance: 72
  }),
  seed({
    id: 'fig_tsui_hark_new_wave_director',
    displayName: '徐克',
    category: 'entertainment',
    sectors: ['film', 'director', 'new_wave'],
    activeYears: { from: 1979, to: 1998 },
    recognitionAliases: ['徐老怪', '老怪导演', '怪才导演', '新派武侠推手'],
    publicRole: '不断改造类型片的怪才导演',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['导演组', '剪接室', '武指会议', '电影公司办公室'],
    promptSafeProfile:
      '脑子快、要求高、喜欢把旧类型拆开重装的导演；适合连接剪接室失窃、武指冲突、片商压力和新旧电影观念。',
    promptSafeHooks: ['剪接室胶片被偷', '武指会议爆发冲突', '片商要求改结局'],
    eraTags: ['导演', '新派武侠', '剪接室'],
    contactPolicy: 'contactable_seed',
    importance: 88
  }),
  seed({
    id: 'fig_john_woo_bullet_brotherhood',
    displayName: '吴宇森',
    category: 'entertainment',
    sectors: ['film', 'director', 'crime_genre'],
    activeYears: { from: 1973, to: 1998 },
    recognitionAliases: ['吴白鸽', '白鸽导演', '枪火兄弟情导演', '暴力美学片场'],
    publicRole: '以兄弟情和枪火场面著称的导演',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['枪战片片场', '道具枪库', '剪接室', '戏院宣传'],
    promptSafeProfile:
      '拍枪火和兄弟情的导演，道具枪、爆破、片场保安和社团模仿都可能牵出案件；不要直接复刻任何具体电影桥段。',
    promptSafeHooks: ['道具枪库少了一把', '群演模仿银幕犯罪', '宣传夜有人送白鸽'],
    eraTags: ['枪战片', '道具枪', '兄弟情'],
    contactPolicy: 'contactable_seed',
    importance: 86
  }),
  seed({
    id: 'fig_ringo_lam_city_fire_director',
    displayName: '林岭东',
    category: 'entertainment',
    sectors: ['film', 'director', 'crime_genre'],
    activeYears: { from: 1983, to: 1998 },
    recognitionAliases: ['卧底气质导演', '都市犯罪片导演'],
    publicRole: '拍都市犯罪和边缘人物的导演',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['犯罪片取材', '警察顾问', '夜间外景', '剪接室'],
    promptSafeProfile:
      '关注卧底、边缘人和城市压迫的导演；适合让真实警察与电影取材发生冲突。',
    promptSafeHooks: ['导演找警察取材', '外景队拍到真实交易', '剪接素材被警方扣押'],
    eraTags: ['犯罪片', '卧底', '外景'],
    contactPolicy: 'contactable_seed',
    importance: 80
  }),
  seed({
    id: 'fig_ann_hui_social_director',
    displayName: '许鞍华',
    category: 'entertainment',
    sectors: ['film', 'director', 'social_realism'],
    activeYears: { from: 1979, to: 1998 },
    recognitionAliases: ['许导', '社会写实女导演', '越境故事导演'],
    publicRole: '关注社会现实和边缘处境的导演',
    usualPlaceIds: ['place_kln_tang_tvb_city', 'place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['纪录素材', '社会服务机构', '电影公司', '采访对象'],
    promptSafeProfile:
      '擅长把移民、难民、家庭和女性处境拍进电影的导演；适合连接社会机构、真实采访和被隐藏的家庭故事。',
    promptSafeHooks: ['采访对象突然失踪', '纪录素材拍到走私', '社工要求停止拍摄'],
    eraTags: ['社会写实', '移民', '女性', '采访'],
    contactPolicy: 'contactable_seed',
    importance: 78
  }),
  seed({
    id: 'fig_stanley_kwan_melodrama_director',
    displayName: '关锦鹏',
    category: 'entertainment',
    sectors: ['film', 'director', 'melodrama'],
    activeYears: { from: 1985, to: 1998 },
    recognitionAliases: ['锦鹏导演', '旧梦导演', '女性命运题材导演'],
    publicRole: '擅长拍女性命运和旧时代情感的导演',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['旧照片资料', '女演员访问', '剪接室', '旧楼外景'],
    promptSafeProfile:
      '对旧时代情感和女性命运敏感的导演，适合把旧照片、旧楼、女演员和被遗忘的案卷连起来。',
    promptSafeHooks: ['旧照片认出失踪者', '女演员不愿再拍某场戏', '旧楼外景牵出旧案'],
    eraTags: ['女性命运', '旧照片', '外景'],
    contactPolicy: 'contactable_seed',
    importance: 74
  }),
  seed({
    id: 'fig_wong_kar_way_slow_neon_director',
    displayName: '王家卫',
    category: 'entertainment',
    sectors: ['film', 'director', 'urban_mood'],
    activeYears: { from: 1988, to: 1998 },
    recognitionAliases: ['王墨镜', '墨镜导演', '慢拍都市导演', '霓虹巷导演', 'Wong Kar Wai'],
    publicRole: '以都市情绪和碎片叙事冒头的导演',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest', 'place_mong_kok_portland_street'],
    accessRoutes: ['夜间外景', '编剧室', '摄影师朋友', '咖啡店'],
    promptSafeProfile:
      '刚冒头的都市导演，常在夜街、霓虹、咖啡店和剪接室里寻找故事；适合做氛围种子，不要让他喧宾夺主。',
    promptSafeHooks: ['夜街外景拍到跟踪者', '摄影底片失踪', '咖啡店听到分手与交易同桌发生'],
    eraTags: ['都市', '霓虹', '外景', '剪接'],
    contactPolicy: 'contactable_seed',
    importance: 72
  }),
  seed({
    id: 'fig_wong_jing_fast_director',
    displayName: '王晶',
    category: 'entertainment',
    sectors: ['film', 'director', 'commercial'],
    activeYears: { from: 1981, to: 1998 },
    recognitionAliases: ['快枪商业片导演', '赌片笑匠', '高产编导'],
    publicRole: '高产商业片编导',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['编剧室', '赌片片场', '电影公司饭局', '戏院票房'],
    promptSafeProfile:
      '商业嗅觉很强、产量很高的编导，适合牵出票房造假、赌片模仿、饭局和投资压力。',
    promptSafeHooks: ['票房数被人为抬高', '赌片道具变成真赌具', '饭局上有人逼改剧本'],
    eraTags: ['商业片', '赌片', '票房'],
    contactPolicy: 'contactable_seed',
    importance: 78
  }),
  seed({
    id: 'fig_ching_siu_tung_wirework_director',
    displayName: '程小东',
    category: 'entertainment',
    sectors: ['film', 'action', 'choreography'],
    activeYears: { from: 1972, to: 1998 },
    recognitionAliases: ['小东师傅', '吊威亚武指', '飘逸动作导演'],
    publicRole: '动作设计和奇幻武侠场面核心人物',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['吊威亚现场', '武指排练', '道具仓', '医院'],
    promptSafeProfile:
      '负责飘逸动作和吊威亚场面的武指导演，安全绳、道具、替身和保险是天然案件入口。',
    promptSafeHooks: ['威亚被人动过手脚', '替身摔伤不敢报警', '道具仓多了一套真兵器'],
    eraTags: ['武指', '威亚', '奇幻武侠'],
    contactPolicy: 'contactable_seed',
    importance: 78
  }),
  seed({
    id: 'fig_yuen_woo_ping_action_master',
    displayName: '袁和平',
    category: 'entertainment',
    sectors: ['film', 'action', 'choreography'],
    activeYears: { from: 1970, to: 1998 },
    recognitionAliases: ['袁八爷', '八爷', '北派动作师傅', '功夫设计名家'],
    publicRole: '动作设计大师和导演',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['动作排练', '武馆', '片场武师班', '功夫明星经纪人'],
    promptSafeProfile:
      '动作设计大师，能把功夫明星、武师班和片商串起来；适合作为功夫片行业网络的高价值锚点。',
    promptSafeHooks: ['武馆弟子卷入社团', '功夫明星合约压力', '动作排练有人换了保护垫'],
    eraTags: ['武指', '功夫片', '武馆'],
    contactPolicy: 'contactable_seed',
    importance: 84
  }),
  seed({
    id: 'fig_corey_yuen_action_director',
    displayName: '元奎',
    category: 'entertainment',
    sectors: ['film', 'action', 'director'],
    activeYears: { from: 1970, to: 1998 },
    recognitionAliases: ['元奎师傅', '动作导演师傅', '武师转导演'],
    publicRole: '武师出身的动作导演',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['动作片片场', '武师班', '低预算剧组', '剪接室'],
    promptSafeProfile:
      '懂武师也懂导演组的动作片人，适合连接低预算动作片、临时演员、替身和片场安全。',
    promptSafeHooks: ['替身名单被换', '低预算剧组隐瞒伤亡', '剪接室发现真打片段'],
    eraTags: ['动作导演', '替身', '低预算'],
    contactPolicy: 'contactable_seed',
    importance: 72
  }),
  seed({
    id: 'fig_lau_kar_leung_martial_master',
    displayName: '刘家良',
    category: 'entertainment',
    sectors: ['film', 'martial_arts', 'director'],
    activeYears: { from: 1965, to: 1998 },
    recognitionAliases: ['刘师傅', '南派功夫导演', '传统武术片掌门'],
    publicRole: '传统功夫片导演和武术家',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['武馆', '传统功夫片片场', '师门饭局', '旧片仓'],
    promptSafeProfile:
      '传统武术根基深的导演师傅，适合牵出师门、武馆、旧式片场规矩和新派动作片冲突。',
    promptSafeHooks: ['武馆徒弟被社团招揽', '师门信物失窃', '旧片仓发现未公开胶片'],
    eraTags: ['传统武术', '武馆', '师门'],
    contactPolicy: 'contactable_seed',
    importance: 78
  }),
  seed({
    id: 'fig_ti_lung_old_school_hero',
    displayName: '狄龙',
    category: 'entertainment',
    sectors: ['film', 'martial_arts', 'actor'],
    activeYears: { from: 1969, to: 1998 },
    recognitionAliases: ['龙哥旧派', '长身侠客', '旧派英雄男星'],
    publicRole: '从旧派武侠片走来的男星',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['旧片公司', '戏院宣传', '武侠片片场', '演员饭局'],
    promptSafeProfile:
      '旧派英雄气质的男星，适合连接老电影公司、武侠片黄金年代、退潮后的明星处境。',
    promptSafeHooks: ['旧片公司欠薪', '戏院宣传遇旧债主', '武侠片道具被盗'],
    eraTags: ['旧派武侠', '男星', '戏院'],
    contactPolicy: 'contactable_seed',
    importance: 72
  }),
  seed({
    id: 'fig_david_chiang_classic_swordsman',
    displayName: '姜大卫',
    category: 'entertainment',
    sectors: ['film', 'martial_arts', 'actor'],
    activeYears: { from: 1966, to: 1998 },
    recognitionAliases: ['大卫哥', '冷面侠客', '旧片场男星'],
    publicRole: '经典武侠片时代的男演员',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['旧片仓', '演员饭局', '武侠片片场', '电视台客串'],
    promptSafeProfile:
      '经典武侠时代走出的演员，适合带出旧片仓、老合约、旧同门和过气后的现实压力。',
    promptSafeHooks: ['旧合约被人翻出', '旧片仓失火', '老演员替新人挡事'],
    eraTags: ['旧派武侠', '演员', '旧片仓'],
    contactPolicy: 'contactable_seed',
    importance: 68
  }),
  seed({
    id: 'fig_gordon_liu_monk_fighter',
    displayName: '刘家辉',
    category: 'entertainment',
    sectors: ['film', 'martial_arts', 'actor'],
    activeYears: { from: 1973, to: 1998 },
    recognitionAliases: ['少林辉', '少林功夫男星'],
    publicRole: '以少林功夫形象闻名的演员',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['武馆', '旧式功夫片片场', '戏服间', '武师聚脚处'],
    promptSafeProfile:
      '少林功夫形象鲜明的演员，适合接入武馆、戏服、旧式功夫片和武师圈消息。',
    promptSafeHooks: ['戏服藏着账本', '武馆弟子失踪', '旧式兵器被换成真货'],
    eraTags: ['少林', '武馆', '功夫片'],
    contactPolicy: 'contactable_seed',
    importance: 66
  }),
  seed({
    id: 'fig_mabel_cheung_migration_director',
    displayName: '张婉婷',
    category: 'entertainment',
    sectors: ['film', 'director', 'migration'],
    activeYears: { from: 1985, to: 1998 },
    recognitionAliases: ['婉婷导演', '移民故事导演', '异乡爱情导演'],
    publicRole: '关注移民和异乡关系的女导演',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest', 'place_kai_tak_airport'],
    accessRoutes: ['机场外景', '移民中介', '电影公司', '编剧室'],
    promptSafeProfile:
      '常把移民、异乡和爱情拍进电影的导演，适合连接机场、移民中介、海外亲属和证人离港。',
    promptSafeHooks: ['机场外景拍到逃亡者', '移民中介资助电影', '海外信件变成线索'],
    eraTags: ['移民', '机场', '导演'],
    contactPolicy: 'contactable_seed',
    importance: 70
  }),
  seed({
    id: 'fig_alex_law_writer_director',
    displayName: '罗启锐',
    category: 'entertainment',
    sectors: ['film', 'writer', 'director'],
    activeYears: { from: 1985, to: 1998 },
    recognitionAliases: ['启锐编导', '移民电影拍档', '温情编剧'],
    publicRole: '编剧和导演',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest', 'place_kai_tak_airport'],
    accessRoutes: ['编剧室', '机场外景', '家庭访问', '电影公司'],
    promptSafeProfile:
      '擅长从家庭细节写大时代的人，适合把移民潮、家庭离散、机场分别和报纸旧闻连起来。',
    promptSafeHooks: ['家庭访问对象改口', '机场外景多出一个箱子', '旧闻剪报被藏进剧本'],
    eraTags: ['编剧', '移民', '家庭'],
    contactPolicy: 'contactable_seed',
    importance: 66
  }),
  seed({
    id: 'fig_tam_kar_ming_modernist',
    displayName: '谭家明',
    category: 'entertainment',
    sectors: ['film', 'director', 'new_wave'],
    activeYears: { from: 1976, to: 1998 },
    recognitionAliases: ['家明导演', '新浪潮影像人', '冷调都市导演'],
    publicRole: '香港新浪潮导演',
    usualPlaceIds: ['place_kln_tang_tvb_city', 'place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['电视台旧档', '电影学院朋友', '剪接室', '影评人饭局'],
    promptSafeProfile:
      '新浪潮影像人，适合让电视旧档、影评圈、剪接室和实验电影场景成为线索来源。',
    promptSafeHooks: ['电视旧档拍到失踪者', '影评人收到匿名胶片', '剪接室有人删去一格画面'],
    eraTags: ['新浪潮', '剪接', '影评'],
    contactPolicy: 'contactable_seed',
    importance: 66
  }),
  seed({
    id: 'fig_beyond_rooftop_band',
    displayName: 'Beyond乐队',
    category: 'entertainment',
    sectors: ['music', 'band', 'youth'],
    activeYears: { from: 1983, to: 1998 },
    recognitionAliases: ['阿驹和几个兄弟', '地下摇滚乐队', '屋邨青年乐队'],
    publicRole: '从地下和青年场景冒出的摇滚乐队',
    usualPlaceIds: ['place_kln_tang_broadcast_drive', 'place_mong_kok_portland_street'],
    accessRoutes: ['天台排练', '唱片店', '校园演出', '电台新歌节目'],
    promptSafeProfile:
      '从天台、屋邨和小场地冒出的青年乐队，适合接入青年失踪、唱片店、地下演出和时代不满。',
    promptSafeHooks: ['天台排练看到交易', '唱片店老板收到demo带', '校园演出后有人没回家'],
    eraTags: ['乐队', '青年', '天台', '唱片店'],
    contactPolicy: 'contactable_seed',
    importance: 78
  }),
  seed({
    id: 'fig_radio_dj_night_voice',
    displayName: '夜航DJ',
    category: 'entertainment',
    sectors: ['radio', 'music', 'media'],
    activeYears: { from: 1980, to: 1998 },
    recognitionAliases: ['深宵电台声', '点歌节目主持', '夜班DJ'],
    publicRole: '深夜电台主持',
    usualPlaceIds: ['place_kln_tang_broadcast_drive'],
    accessRoutes: ['深夜直播间', '听众来信', '唱片公司宣传', '电话点歌'],
    promptSafeProfile:
      '深夜电台主持不是固定名人，但全城失眠者都会打给他；适合把点歌、求救电话和城市孤独投进剧情。',
    promptSafeHooks: ['点歌像暗号', '听众直播中求救', '来信夹着照片'],
    eraTags: ['电台', '点歌', '深夜'],
    contactPolicy: 'contactable_seed',
    importance: 70
  }),
  seed({
    id: 'fig_variety_phone_host',
    displayName: '电话筹款主持',
    category: 'entertainment',
    sectors: ['tv', 'charity', 'hosting'],
    activeYears: { from: 1980, to: 1998 },
    recognitionAliases: ['善款热线主持', '台庆司仪', '笑面主持人'],
    publicRole: '大型晚会和热线节目的主持人',
    usualPlaceIds: ['place_kln_tang_tvb_city', 'place_kln_tang_broadcast_drive'],
    accessRoutes: ['筹款晚会后台', '电话接线区', '电视台财务室', '慈善机构'],
    promptSafeProfile:
      '大型筹款和热线节目的主持人，适合把娱乐圈、善款、接线员和公众信任连接起来。',
    promptSafeHooks: ['善款数字对不上', '接线员听见威胁', '主持稿被临时替换'],
    eraTags: ['筹款', '主持', '电视台'],
    contactPolicy: 'contactable_seed',
    importance: 68
  }),
  seed({
    id: 'fig_pageant_newcomer_seed',
    displayName: '选美新人阿莹',
    category: 'entertainment',
    sectors: ['tv', 'fashion', 'pageant'],
    activeYears: { from: 1980, to: 1998 },
    recognitionAliases: ['港姐新人', '选美三甲', '赞助商新宠'],
    publicRole: '从选美进入电视和广告圈的新人',
    usualPlaceIds: ['place_kln_tang_tvb_city'],
    accessRoutes: ['选美后台', '广告试镜', '赞助商饭局', '电视台训练班'],
    promptSafeProfile:
      '选美新人常被赞助商、电视台和广告商拉扯，适合呈现女性新人被包装、被保护或被利用。',
    promptSafeHooks: ['赞助商名单异常', '后台礼服被动手脚', '新人想报警但怕毁约'],
    eraTags: ['选美', '广告', '新人'],
    contactPolicy: 'contactable_seed',
    importance: 66
  }),
  seed({
    id: 'fig_stunt_double_sister',
    displayName: '替身阿敏',
    category: 'entertainment',
    sectors: ['film', 'stunt', 'labour'],
    activeYears: { from: 1980, to: 1998 },
    recognitionAliases: ['女替身', '跳楼替身', '无名武师妹'],
    publicRole: '不被观众记住名字的女性动作替身',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['武师班', '医院急症室', '低预算片场', '保险调查'],
    promptSafeProfile:
      '不是固定 NPC，而是一类可被实例化的种子人物：女替身承担危险动作却常没有署名和保障。',
    promptSafeHooks: ['替身摔伤被要求签保密', '保险表格写成路滑', '明星不知道替身真实伤势'],
    eraTags: ['替身', '工伤', '女性劳动'],
    contactPolicy: 'contactable_seed',
    importance: 70
  }),
  seed({
    id: 'fig_cha_sir_wuxia_publisher',
    displayName: '金庸',
    category: 'literature_media',
    sectors: ['publishing', 'newspaper', 'wuxia', 'public_affairs'],
    activeYears: { from: 1959, to: 1998 },
    recognitionAliases: ['查先生', '武侠报人', '明字号报馆老板', '查良镛', 'Louis Cha'],
    publicRole: '武侠小说宗师和报业人物',
    usualPlaceIds: ['place_central_legislative_council', 'place_kln_tang_broadcast_drive'],
    accessRoutes: ['报馆编辑部', '社论风波', '武侠版权', '基本法饭局'],
    promptSafeProfile:
      '报业和武侠文化双重分量极重的查先生，能连接报馆、武侠版权、政治观察和社会舆论；接触门槛高，通常先通过编辑、专栏、剪报和饭局出现。',
    promptSafeHooks: ['报馆匿名信', '武侠连载版权纠纷', '社论引来压力'],
    eraTags: ['报馆', '武侠', '社论', '版权'],
    contactPolicy: 'contactable_seed',
    importance: 96,
    sourceConfidence: 'high'
  }),
  seed({
    id: 'fig_gu_lung_wine_swordsman',
    displayName: '古龙',
    category: 'literature_media',
    sectors: ['wuxia', 'publishing', 'legacy'],
    activeYears: { from: 1960, to: 1998 },
    recognitionAliases: ['好酒的武侠小说家', '酒杯边的江湖笔名', '已故奇情剑客作者'],
    publicRole: '已故但影响仍在的武侠小说家',
    usualPlaceIds: ['place_kln_tang_broadcast_drive'],
    accessRoutes: ['出版社旧友', '酒吧传闻', '版权争议', '改编片场'],
    promptSafeProfile:
      '好酒、重朋友、文字里有浪子和刀光的武侠小说家；在1988更适合作为遗产、版权、旧友和酒局传闻出现，而不是活跃在场人物。',
    promptSafeHooks: ['旧酒局名单', '版权被人抢注', '改编剧组收到旧手稿'],
    eraTags: ['武侠', '酒局', '遗产', '版权'],
    contactPolicy: 'rumor_only',
    importance: 90,
    sourceConfidence: 'high'
  }),
  seed({
    id: 'fig_ni_kuang_sci_fi_writer',
    displayName: '倪匡',
    category: 'literature_media',
    sectors: ['publishing', 'screenwriting', 'science_fiction'],
    activeYears: { from: 1960, to: 1998 },
    recognitionAliases: ['卫斯理式奇谈作者', '怪谈编剧'],
    publicRole: '高产小说家和编剧',
    usualPlaceIds: ['place_kln_tang_broadcast_drive', 'place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['报馆专栏', '编剧室', '电影公司', '酒楼饭局'],
    promptSafeProfile:
      '极高产、想象力怪异的小说家和编剧，适合把都市怪谈、走私文物、外星传闻和真实刑案混成可疑线索。',
    promptSafeHooks: ['怪谈专栏像真实案情', '编剧室藏着警方没公开的细节', '酒楼饭局有人卖文物'],
    eraTags: ['科幻', '怪谈', '编剧', '专栏'],
    contactPolicy: 'contactable_seed',
    importance: 84
  }),
  seed({
    id: 'fig_leung_yu_sang_sword_serialist',
    displayName: '梁羽生',
    category: 'literature_media',
    sectors: ['wuxia', 'publishing', 'newspaper'],
    activeYears: { from: 1954, to: 1998 },
    recognitionAliases: ['梁先生', '新派武侠前辈', '报馆剑客'],
    publicRole: '新派武侠开山级作家',
    usualPlaceIds: ['place_kln_tang_broadcast_drive'],
    accessRoutes: ['报馆旧档', '出版社', '武侠迷聚会', '书店'],
    promptSafeProfile:
      '新派武侠前辈，常通过旧报纸连载、书店、武侠迷和版权改编影响剧情。',
    promptSafeHooks: ['旧连载剪报夹着暗号', '书店老板收到匿名包裹', '武侠迷聚会变成交易'],
    eraTags: ['武侠', '报纸连载', '书店'],
    contactPolicy: 'rumor_only',
    importance: 78
  }),
  seed({
    id: 'fig_yi_shu_city_novelist',
    displayName: '亦舒',
    category: 'literature_media',
    sectors: ['publishing', 'column', 'urban_women'],
    activeYears: { from: 1963, to: 1998 },
    recognitionAliases: ['都市女性小说家', '冷眼专栏作家'],
    publicRole: '写都市女性和中产处境的作家',
    usualPlaceIds: ['place_kln_tang_broadcast_drive', 'place_central_hsbc_building'],
    accessRoutes: ['杂志社', '报馆专栏', '咖啡店访问', '读者来信'],
    promptSafeProfile:
      '以冷静笔触写都市女性、中产焦虑和感情账的人，适合作为读者来信、杂志社、女性证词和家庭秘密入口。',
    promptSafeHooks: ['读者来信像求救', '杂志社收到匿名照片', '女编辑不愿交出信件'],
    eraTags: ['都市女性', '专栏', '读者来信'],
    contactPolicy: 'contactable_seed',
    importance: 78
  }),
  seed({
    id: 'fig_james_wong_lyric_trickster',
    displayName: '黄霑',
    category: 'literature_media',
    sectors: ['lyrics', 'advertising', 'music', 'media'],
    activeYears: { from: 1965, to: 1998 },
    recognitionAliases: ['鬼才填词人', '广告歌怪才'],
    publicRole: '填词人、广告人和传媒鬼才',
    usualPlaceIds: ['place_kln_tang_broadcast_drive'],
    accessRoutes: ['录音室', '广告公司', '电台节目', '酒楼饭局'],
    promptSafeProfile:
      '嘴毒、才快、懂广告和歌曲传播的填词人，适合把广告语、歌词、广播和饭局变成暗号或舆论事件。',
    promptSafeHooks: ['广告歌藏暗号', '歌词手稿被偷', '饭局上有人要求改词'],
    eraTags: ['填词', '广告', '广播', '饭局'],
    contactPolicy: 'contactable_seed',
    importance: 82
  }),
  seed({
    id: 'fig_choy_lam_food_film_critic',
    displayName: '蔡澜',
    category: 'literature_media',
    sectors: ['film', 'food', 'column'],
    activeYears: { from: 1960, to: 1998 },
    recognitionAliases: ['美食电影人', '风流专栏家', '片场饭局通'],
    publicRole: '电影监制、美食专栏和饭局人脉人物',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest', 'place_mong_kok_portland_street'],
    accessRoutes: ['片场饭局', '餐馆专栏', '电影公司', '酒楼包房'],
    promptSafeProfile:
      '懂电影、懂饭局、懂食物也懂人情的人，适合让餐馆、酒楼、片场和专栏成为线索交汇点。',
    promptSafeHooks: ['美食专栏提到一间不该开门的店', '片场饭局后有人失踪', '酒楼包房账单异常'],
    eraTags: ['饭局', '美食', '电影监制', '专栏'],
    contactPolicy: 'contactable_seed',
    importance: 78
  }),
  seed({
    id: 'fig_lam_yin_nee_columnist',
    displayName: '林燕妮',
    category: 'literature_media',
    sectors: ['column', 'publishing', 'socialite'],
    activeYears: { from: 1960, to: 1998 },
    recognitionAliases: ['燕妮姐', '才女专栏家', '情场观察者'],
    publicRole: '写情感、名流和城市女性的专栏作家',
    usualPlaceIds: ['place_central_hsbc_building', 'place_kln_tang_broadcast_drive'],
    accessRoutes: ['报馆专栏', '名流饭局', '读者来信', '杂志社'],
    promptSafeProfile:
      '笔下常有情感、名流、女性和社会气味，适合通过读者来信和名流饭局切入私密纠纷。',
    promptSafeHooks: ['读者来信提到勒索', '名流饭局有人改名', '专栏刊出后电话不断'],
    eraTags: ['专栏', '名流', '女性', '读者来信'],
    contactPolicy: 'contactable_seed',
    importance: 74
  }),
  seed({
    id: 'fig_film_critic_roka_archive',
    displayName: '罗卡',
    category: 'literature_media',
    sectors: ['film_criticism', 'archive', 'media'],
    activeYears: { from: 1970, to: 1998 },
    recognitionAliases: ['电影资料馆熟人', '旧片影评人', '片单先生'],
    publicRole: '影评人和电影资料整理者',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest', 'place_kln_tang_broadcast_drive'],
    accessRoutes: ['旧片仓', '影评人饭局', '电影资料室', '报纸副刊'],
    promptSafeProfile:
      '熟悉旧片、片单和电影史的人，不一定是大众明星，但能把一盘旧胶片、一张片单和一个失踪演员连起来。',
    promptSafeHooks: ['旧片单上多了一个不存在的名字', '胶片仓发现私人影像', '影评专栏被要求撤稿'],
    eraTags: ['影评', '旧片', '资料室'],
    contactPolicy: 'contactable_seed',
    importance: 66
  }),
  seed({
    id: 'fig_entertainment_tabloid_editor',
    displayName: '花边报阿丘',
    category: 'literature_media',
    sectors: ['tabloid', 'media', 'entertainment'],
    activeYears: { from: 1980, to: 1998 },
    recognitionAliases: ['娱乐版夜班编辑', '狗仔线人头', '花边报编辑'],
    publicRole: '娱乐小报编辑',
    usualPlaceIds: ['place_kln_tang_broadcast_drive', 'place_mong_kok_portland_street'],
    accessRoutes: ['报馆夜班', '狗仔底片', '夜场线人', '明星公寓楼下'],
    promptSafeProfile:
      '娱乐小报编辑掌握大量真假难辨的明星线索；适合提供照片、传闻、敲诈风险和媒体伦理冲突。',
    promptSafeHooks: ['底片拍到真案', '小报被人买版面', '狗仔失踪'],
    eraTags: ['小报', '狗仔', '底片', '夜场'],
    contactPolicy: 'contactable_seed',
    importance: 72
  }),
  seed({
    id: 'fig_radio_agony_aunt',
    displayName: '深夜知心姐',
    category: 'literature_media',
    sectors: ['radio', 'advice_column', 'public_emotion'],
    activeYears: { from: 1980, to: 1998 },
    recognitionAliases: ['电台情感主持', '知心姐姐', '热线主持人'],
    publicRole: '深夜情感热线主持',
    usualPlaceIds: ['place_kln_tang_broadcast_drive'],
    accessRoutes: ['深夜热线', '听众录音带', '节目来信', '电台导播间'],
    promptSafeProfile:
      '深夜情感热线主持能听见城市最脆弱的一面；适合把家庭暴力、债务、失踪和求救混在听众电话里。',
    promptSafeHooks: ['听众电话突然中断', '录音带里有第三个人呼吸声', '来信夹着医院单据'],
    eraTags: ['热线', '电台', '求救'],
    contactPolicy: 'contactable_seed',
    importance: 70
  }),
  seed({
    id: 'fig_newspaper_political_columnist',
    displayName: '社论老麦',
    category: 'literature_media',
    sectors: ['newspaper', 'politics', 'column'],
    activeYears: { from: 1980, to: 1998 },
    recognitionAliases: ['报馆主笔', '九七专栏人', '老麦社论'],
    publicRole: '关注前途问题和制度变化的报馆主笔',
    usualPlaceIds: ['place_central_legislative_council', 'place_kln_tang_broadcast_drive'],
    accessRoutes: ['报馆社论桌', '立法局走廊', '茶餐厅消息源', '匿名投稿'],
    promptSafeProfile:
      '写九七、移民、制度和舆论的主笔，不是明星但能让娱乐圈事件被政治压力放大。',
    promptSafeHooks: ['社论被要求改题', '匿名投稿牵出艺人移民', '主笔收到律师信'],
    eraTags: ['社论', '九七', '报馆', '匿名投稿'],
    contactPolicy: 'contactable_seed',
    importance: 72
  }),
  seed({
    id: 'fig_choi_manager_shadow',
    displayName: '蔡子明',
    category: 'business_backstage',
    sectors: ['film', 'management', 'underworld_pressure'],
    activeYears: { from: 1988, to: 1998 },
    recognitionAliases: ['功夫明星经纪人', '蔡经理', '片场保护伞', '被枪声盯上的经理人'],
    publicRole: '围绕功夫明星的强势经纪和投资人物',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest', 'place_mong_kok_portland_street'],
    accessRoutes: ['经纪公司办公室', '功夫片片场', '夜场饭局', '保镖安排'],
    promptSafeProfile:
      '强势经纪人，替功夫明星挡片商、饭局和江湖压力；围绕他的威胁、枪声、债务和合约最适合做重大事件种子。',
    promptSafeHooks: ['经纪人办公室外响枪', '功夫明星被迫换公司', '保镖突然失踪'],
    eraTags: ['经纪人', '功夫明星', '枪击', '片商'],
    contactPolicy: 'contactable_seed',
    importance: 92,
    copyRisk: 'high',
    sourceConfidence: 'high'
  }),
  seed({
    id: 'fig_six_uncle_tv_tycoon',
    displayName: '邵逸夫',
    category: 'business_backstage',
    sectors: ['tv', 'film', 'tycoon'],
    activeYears: { from: 1960, to: 1998 },
    recognitionAliases: ['六叔', '电视王国老人', '片厂大老板', '慈善楼宇命名人'],
    publicRole: '电视和电影工业巨头',
    usualPlaceIds: ['place_kln_tang_tvb_city', 'place_kln_tang_broadcast_drive'],
    accessRoutes: ['电视城高层', '台庆', '慈善晚会', '片厂旧人脉'],
    promptSafeProfile:
      '电视和电影工业的巨头级老人，通常不直接出场，但他的制度、慈善、片厂规矩和高层命令会压到每个艺人身上。',
    promptSafeHooks: ['高层命令压下新闻', '慈善捐款带来政治人情', '片厂旧账本重见天日'],
    eraTags: ['电视台', '片厂', '慈善', '高层'],
    contactPolicy: 'background_only',
    importance: 90
  }),
  seed({
    id: 'fig_golden_harvest_big_boss',
    displayName: '邹文怀',
    category: 'business_backstage',
    sectors: ['film_company', 'distribution', 'capital'],
    activeYears: { from: 1970, to: 1998 },
    recognitionAliases: ['嘉禾邹老板', '大片厂老板', '功夫片推手', '海外发行大佬'],
    publicRole: '电影公司和海外发行核心老板',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['电影公司办公室', '海外发行饭局', '戏院院线', '功夫明星合约'],
    promptSafeProfile:
      '大片厂老板，掌握发行、合约、明星和海外市场；适合把片场案扩大成商业和资本压力。',
    promptSafeHooks: ['海外发行账目异常', '明星合约被人抢', '戏院排片被威胁'],
    eraTags: ['电影公司', '发行', '合约', '院线'],
    contactPolicy: 'background_only',
    importance: 88
  }),
  seed({
    id: 'fig_cinema_chain_lady_boss',
    displayName: '方逸华',
    category: 'business_backstage',
    sectors: ['tv', 'cinema_chain', 'management'],
    activeYears: { from: 1970, to: 1998 },
    recognitionAliases: ['方小姐', '电视城女高层', '排片女老板', '艺员合约话事人'],
    publicRole: '电视和院线管理层人物',
    usualPlaceIds: ['place_kln_tang_tvb_city', 'place_kln_tang_broadcast_drive'],
    accessRoutes: ['艺员合约部', '台庆后台', '院线办公室', '高层秘书'],
    promptSafeProfile:
      '强势管理层女性，掌握艺员合约、排片和台内秩序；适合制造制度压力，而不是普通可约见 NPC。',
    promptSafeHooks: ['艺员合约被压住', '排片单被临时改', '高层秘书泄露名单'],
    eraTags: ['高层', '艺员合约', '排片'],
    contactPolicy: 'background_only',
    importance: 78
  }),
  seed({
    id: 'fig_music_label_contract_boss',
    displayName: '宝丽金何生',
    category: 'business_backstage',
    sectors: ['music', 'label', 'contract'],
    activeYears: { from: 1975, to: 1998 },
    recognitionAliases: ['唱片公司老板', '合约何生', '歌星包装人'],
    publicRole: '唱片公司合约和宣传负责人',
    usualPlaceIds: ['place_kln_tang_broadcast_drive'],
    accessRoutes: ['唱片公司', '录音室', '电台宣传', '歌迷会'],
    promptSafeProfile:
      '唱片公司合约负责人，能决定歌手宣传、派台和合约续签；适合牵出唱片合约、买榜、歌迷会资金。',
    promptSafeHooks: ['派台名单被买通', '歌手被迫续约', '歌迷会账目不清'],
    eraTags: ['唱片公司', '合约', '宣传'],
    contactPolicy: 'contactable_seed',
    importance: 74
  }),
  seed({
    id: 'fig_stunt_team_broker',
    displayName: '武师班阿标',
    category: 'business_backstage',
    sectors: ['film', 'stunt', 'labour_broker'],
    activeYears: { from: 1975, to: 1998 },
    recognitionAliases: ['武师中介', '替身班头', '片场判头'],
    publicRole: '武师和替身工作安排人',
    usualPlaceIds: ['place_lai_chi_kok_golden_harvest'],
    accessRoutes: ['武师饭局', '医院急症室', '低预算片场', '保险公司'],
    promptSafeProfile:
      '替片场找武师和替身的班头，知道谁受伤、谁欠钱、谁被迫顶上；适合把明星光环下面的劳动风险拉出来。',
    promptSafeHooks: ['替身顶名领工钱', '工伤被写成私斗', '武师班有人被社团借走'],
    eraTags: ['武师', '替身', '工伤', '判头'],
    contactPolicy: 'contactable_seed',
    importance: 76
  })
];

export const hkLateColonialEraSeedFigures: EraSeedFigureCard[] = [
  ...hkLateColonialCoreEraSeedFigures,
  ...hkLateColonialEntertainmentFigureExpansion
];
